import React,{memo,useState} from 'react';
import {Plus,Sparkles,Check} from 'lucide-react';
import {CreatorDialog} from '../CreatorDialogs.jsx';
import {ReferenceCardPicker} from './ReferencePanes.jsx';
import {Heading,AgentSelect,Panel,Field,Empty,Tag,NodeTools} from './FrameworkParts.jsx';

export const groupCode=index=>{let n=index+1,s='';while(n){n--;s=String.fromCharCode(65+n%26)+s;n=Math.floor(n/26);}return s;};
const id=()=>`component_${crypto.randomUUID()}`;

const StoryCard=memo(function StoryCard({node,type,code,command,index,count,locked,onSimulate,onExpand,children}){
 const content=type==='group'?node.goal:node.story||node.summary;
 const save=value=>command({type:`${type}.update`,id:node.id,draft:true,patch:{...(type==='group'?{goal:value}:{summary:value,story:value}),confirmed:false,analysisStale:true}});
 const notes=[['before','起点'],['after','结果'],['motive','动机'],['foreshadow','铺垫与伏笔']].filter(([key])=>node[key]);
 return <article className="fw-story-card" aria-label={`${code||'大事件'}卡片`}><header>{code&&<span className="fw-macro-code">{code}</span>}<Field label={`${code||node.title}标题`} draftKey={node.id+'title'} multiline={false} value={node.title} disabled={locked} onCommit={title=>command({type:`${type}.update`,id:node.id,draft:true,patch:{title,confirmed:false}})}/><Tag good={node.confirmed}>{node.locked?'已固定':node.confirmed?'已确认':'草稿'}</Tag></header>
 <Field draftKey={node.id+'prose'} label={`${code||node.title}完整事件`} value={content||''} disabled={locked} placeholder="直接写完整事件。人物行动、经过、结果都写在这里，随时修改。" onCommit={save}/>
 {notes.length>0&&<details className="fw-card-notes"><summary>{node.analysisStale?'历史整理信息 · 待重新核对':'已有整理信息'}</summary>{notes.map(([key,label])=><p key={key}><strong>{label}：</strong>{node[key]}</p>)}</details>}
 <footer><NodeTools node={node} locked={locked} command={command} type={type} index={index} count={count}/><div className="fw-actions fw-card-agent-actions">{(onExpand||onSimulate)&&<AgentSelect compact label={`${code||node.title}使用的接口`}/>} {onExpand&&<button className="ghost" disabled={locked} onClick={onExpand} title="Agent 整理完整事件">整理</button>}{onSimulate&&<button className="ghost" onClick={onSimulate} aria-label="推理后续" title="推理后续"><Sparkles size={14}/></button>}{children}</div></footer></article>;
});

function BulkEventDialog({f,command,run,busy,onClose}){
 const [text,setText]=useState(f.bulkDraft||'');
 return <CreatorDialog title="整段故事划分大事件" onClose={onClose} className="fw-bulk-dialog"><p>粘贴全部情节，Agent 会划分成多张大事件卡片。已有卡片保留，结果预览后再采用。</p><Field autoFocus label="待划分的故事内容" draftKey="bulk-events" value={f.bulkDraft||''} onDraftChange={setText} onCommit={text=>command({type:'bulk.draft',text})} placeholder="把一段故事或多件事一起写在这里…"/><footer><AgentSelect label="划分卡片接口"/><button className="secondary" onClick={onClose}>收起，保留草稿</button><button className="primary" disabled={busy||!text.trim()} onClick={async()=>{if(await run({task:'frameworkSplit',text}))onClose();}}><Sparkles size={16}/>Agent 划分卡片</button></footer></CreatorDialog>;
}
export function EventsPane({f,command,run,busy}){
 const [picker,setPicker]=useState(false),[bulk,setBulk]=useState(false);
 const add=()=>command({type:'group.add',group:{id:id(),title:'新大事件'}});
 return <><Heading title="大事件" help="一张卡片，一个完整大事件。也可以整段粘贴，由 Agent 划分卡片。"><button className="secondary" onClick={()=>setBulk(true)}><Sparkles size={15}/>整段内容划分</button><button className="secondary" onClick={()=>setPicker(true)}>从对标剧本添加</button><button className="primary" onClick={add}><Plus size={16}/>创建大事件</button></Heading>
 <div className="fw-story-board">{f.groups.map(g=><StoryCard key={g.id} node={g} type="group" command={command} locked={g.locked} onExpand={()=>!busy&&run({task:'frameworkCard',nodeType:'group',nodeId:g.id})}/>)}<button className="fw-add-card" onClick={add}><Plus size={24}/><strong>新建大事件</strong><span>直接写下完整情节</span></button></div>
 {picker&&<ReferenceCardPicker f={f} command={command} onClose={()=>setPicker(false)}/>}{bulk&&<BulkEventDialog f={f} command={command} run={run} busy={busy} onClose={()=>setBulk(false)}/>}</>;
}

export function MainlinePane({f,command,navigate,openSimulation,run,busy}){
 return <><Heading title="主线" help="按 A、B、C 排列故事顺序。模拟助手可检查因果、人物动机与伏笔。"><button className="secondary" disabled={!f.groups.length} onClick={()=>openSimulation({layer:'groups',mode:'reorder'})}><Sparkles size={16}/>模拟排序</button><button className="secondary" disabled={!f.groups.length} onClick={()=>openSimulation({layer:'groups',mode:'infer'})}>推理后续</button><button className="primary" disabled={!f.groups.length} onClick={()=>{if(command({type:'mainline.orderConfirm'}))navigate('smallEvents');}}><Check size={16}/>确认顺序，展开小事件</button></Heading>
 <div className="fw-story-board">{f.groups.map((g,i)=><StoryCard key={g.id} node={g} type="group" code={groupCode(i)} command={command} locked={g.locked} index={i} count={f.groups.length} onExpand={()=>!busy&&run({task:'frameworkCard',nodeType:'group',nodeId:g.id})} onSimulate={()=>openSimulation({layer:'groups',mode:'infer',afterGroupId:g.id})}/>)}</div>
 {!f.groups.length&&<Empty><button className="primary" onClick={()=>navigate('events')}>创建第一张大事件卡片</button></Empty>}</>;
}

export function SmallEventsPane({f,rows,command,run,busy,navigate,openSimulation}){
 const [groupId,setGroupId]=useState('');const g=f.groups.find(x=>x.id===groupId)||f.groups[0],groupRows=rows.filter(r=>r.group?.id===g?.id),groupIndex=f.groups.findIndex(x=>x.id===g?.id);
 const add=()=>command({type:'event.add',groupId:g.id,event:{id:id(),title:'新小事件'}});
 return <><Heading title="小事件" help="逐个完成大事件里的具体行动。卡片顺序就是情节顺序。"><button className="secondary" onClick={()=>openSimulation({layer:'group',groupId:g?.id,mode:'reorder'})} disabled={!g}><Sparkles size={15}/>模拟排序</button><button className="secondary" onClick={()=>openSimulation({layer:'group',groupId:g?.id,mode:'infer'})} disabled={!g}>推理后续</button><button className="primary" disabled={!rows.filter(r=>r.group).length} onClick={()=>{if(window.confirm('已审阅全部小事件及其前后衔接？确认后可划分集纲。')&&command({type:'mainline.confirmAll'}))navigate('plans');}}>确认故事，划分集纲</button></Heading>
 <div className="fw-group-tabs" aria-label="选择大事件">{f.groups.map((group,i)=><button className={g?.id===group.id?'active':''} key={group.id} onClick={()=>setGroupId(group.id)}><b>{groupCode(i)}</b><span>{group.title}</span><small>{rows.filter(r=>r.group?.id===group.id).length}</small></button>)}</div>
 {g?<><details className="fw-parent-context"><summary>{groupCode(groupIndex)} · {g.title} <span>查看大事件内容及前后衔接</span></summary><p>{g.goal}</p><p>{f.groups[groupIndex-1]?.title||'故事开端'} → {g.title} → {f.groups[groupIndex+1]?.title||'故事结局'}</p></details><div className={`fw-story-board ${!groupRows.length?'fw-empty-board':''}`}>{groupRows.map(r=><StoryCard key={r.event.id} node={r.event} type="event" code={r.code} locked={!!(g.locked||r.middle?.locked||r.event.locked)} command={c=>command(c.type==='event.move'?{...c,groupId:g.id,middleId:r.middle?.id||null}:c)} index={(r.middle?r.middle.events:g.events).findIndex(e=>e.id===r.event.id)} count={r.middle?r.middle.events.length:g.events.length} onSimulate={()=>openSimulation({layer:'group',groupId:g.id,mode:'infer',afterEventId:r.event.id})} onExpand={()=>{if(!busy)run({task:'frameworkCard',nodeType:'event',nodeId:r.event.id});}}><select aria-label={`${r.code}移动到大事件`} value={g.id} disabled={!!(g.locked||r.middle?.locked||r.event.locked)} onChange={e=>command({type:'event.move',id:r.event.id,groupId:e.target.value})}>{f.groups.map((group,i)=><option key={group.id} value={group.id} disabled={group.locked}>移至 {groupCode(i)}</option>)}</select></StoryCard>)}<button className="fw-add-card" disabled={g.locked} onClick={add}><Plus size={24}/><strong>添加小事件</strong><span>{groupCode(groupIndex)}{groupRows.length+1} · 直接写具体情节</span></button></div></>:<Empty><button className="primary" onClick={()=>navigate('events')}>先创建大事件</button></Empty>}
 <details className="fw-parent-context"><summary>衔接记录与未归组事件 · {f.mainline.links.length} / {f.looseEvents.length}</summary><div className="fw-inline-tools"><AgentSelect compact label="全剧检查接口"/><button className="secondary" disabled={busy} onClick={()=>run({task:'frameworkCheck'})}>Agent 检查全剧因果</button></div>{f.mainline.links.map(l=><div className="fw-note" key={l.id}><strong>{rows.find(r=>r.event.id===l.fromId)?.code||'已移除'} → {rows.find(r=>r.event.id===l.toId)?.code||'已移除'}</strong><p>{l.notes}</p><button className="ghost danger" onClick={()=>command({type:'mainline.unlink',id:l.id})}>移除这处衔接</button></div>)}{f.looseEvents.map(e=><article className="fw-note" key={e.id}><strong>{e.title}</strong><p>{e.story||e.summary}</p><select aria-label={`${e.title}归入大事件`} value="" onChange={ev=>{if(ev.target.value)command({type:'event.move',id:e.id,groupId:ev.target.value});}}><option value="">归入大事件</option>{f.groups.map(g=><option key={g.id} value={g.id} disabled={g.locked}>{g.title}</option>)}</select></article>)}</details></>;
}

export function MasterPane({f,rows,command,navigate,openExport}){
 const [tab,setTab]=useState('script'),plan=f.plans.find(p=>p.id===f.activePlanId);
 return <><Heading title="总剧本" help="各阶段的内容在这里汇总。正文编辑直接同步到当前分集，导出时可以选择草稿或终稿。"><button className="secondary" onClick={()=>navigate('plans')}>整理集纲</button><button className="primary" onClick={openExport}>导出剧本</button></Heading><div className="fw-seg"><button className={tab==='script'?'active':''} onClick={()=>setTab('script')}>分集正文</button><button className={tab==='story'?'active':''} onClick={()=>setTab('story')}>全部故事</button><button className={tab==='plan'?'active':''} onClick={()=>setTab('plan')}>集纲</button></div>
 {tab==='script'?plan?.episodes.length?<div className="fw-master-scroll">{plan.episodes.map((ep,i)=><Panel key={ep.id} title={`第${i+1}集 · ${ep.title}`} extra={<Tag good={ep.finalConfirmed}>{ep.finalConfirmed?'已确认':'草稿'}</Tag>}><Field draftKey={ep.id+'master'} label={`总剧本第${i+1}集正文`} rows={14} value={ep.result||''} placeholder="本集正文尚未写作，可以直接在这里编辑。" onCommit={result=>command({type:'episode.update',planId:plan.id,episodeId:ep.id,draft:true,patch:{result,finalConfirmed:false}})}/></Panel>)}</div>:<Empty>大事件和小事件可在“全部故事”查看。划分集纲并采用版本后，分集正文在这里汇总。</Empty>:tab==='story'?<div className="fw-master-scroll">{f.groups.map((g,i)=><Panel key={g.id} title={`${groupCode(i)} · ${g.title}`}><p>{g.goal}</p>{rows.filter(r=>r.group?.id===g.id).map(r=><article key={r.event.id}><h3>{r.code} · {r.event.title}</h3><Field draftKey={r.event.id+'master-story'} label={`${r.code} 完整故事`} rows={8} value={r.event.story||r.event.summary} disabled={!!(g.locked||r.middle?.locked||r.event.locked)} onCommit={story=>command({type:'event.update',id:r.event.id,draft:true,patch:{story}})}/></article>)}</Panel>)}</div>:plan?<div className="fw-master-scroll">{plan.episodes.map((ep,i)=><Panel key={ep.id} title={`第${i+1}集`}><p>{ep.content||ep.outline}</p><p><strong>集尾期待：</strong>{ep.hook||'待填写'}</p></Panel>)}</div>:<Empty>尚未采用集纲版本。</Empty>}</>;
}
