import React, {useEffect,useState} from 'react';
import {Plus,Check,Lock,Unlock,Trash2,ArrowUp,ArrowDown} from 'lucide-react';
import {CreatorDialog} from '../CreatorDialogs.jsx';

export function Heading({title,help,children}){return <div className="fw-heading"><div><h1>{title}</h1><p>{help}</p></div><div className="fw-actions">{children}</div></div>;}
export function Panel({title,extra,children,className=''}){return <section className={`fw-panel ${className}`}>{title&&<header><h3>{title}</h3><div className="fw-actions">{extra}</div></header>}<div className="fw-panel-body">{children}</div></section>;}
export function Empty({children}){return <div className="fw-empty">{children}</div>;}
export function Tag({children,good=false,warn=false}){return <span className={`fw-tag ${good?'good':''} ${warn?'warn':''}`}>{children}</span>;}
export function Field({label,value='',onCommit,multiline=true,rows=3,disabled=false,...rest}){const [draft,setDraft]=useState(value??'');useEffect(()=>setDraft(value??''),[value]);const props={...rest,'aria-label':label,value:draft,disabled,onChange:e=>setDraft(e.target.value),onBlur:()=>{if(draft!==(value??''))onCommit?.(draft);}};return <label className="fw-field"><span>{label}</span>{multiline?<textarea {...props} rows={rows}/>:<input {...props}/>}</label>;}
export function NodeTools({node,locked,command,type,index,count,edit,add}){return <div className="fw-actions fw-node-tools"><button className="ghost" title={node.locked?'解锁':'固定'} aria-label={`${node.title||'事件'}${node.locked?'解锁':'固定'}`} onClick={()=>command({type:'node.lock',id:node.id,locked:!node.locked})}>{node.locked?<Lock size={14}/>:<Unlock size={14}/>}</button>{edit&&<button className="secondary" disabled={locked} onClick={edit}>编辑</button>}{add&&<button className="ghost" disabled={locked} onClick={add}><Plus size={14}/></button>}{index!==undefined&&<><button className="ghost" disabled={locked||index===0} aria-label="向前移动" onClick={()=>command({type:`${type}.move`,id:node.id,index:index-1})}><ArrowUp size={14}/></button><button className="ghost" disabled={locked||index===count-1} aria-label="向后移动" onClick={()=>command({type:`${type}.move`,id:node.id,index:index+1})}><ArrowDown size={14}/></button></>}<button className="ghost" disabled={locked} title="确认内容" onClick={()=>command({type:'node.confirm',id:node.id,confirmed:true})}><Check size={14}/></button><button className="ghost danger" disabled={locked} title="删除" aria-label={`删除${node.title||'事件'}`} onClick={()=>{if(window.confirm('删除此项？关联资料与版本正文会保留，相关内容需重新复核。'))command({type:`${type}.remove`,id:node.id});}}><Trash2 size={14}/></button></div>;}
export function EditDialog({title,fields,initial={},onClose,onSubmit,children}){const [draft,setDraft]=useState(initial);return <CreatorDialog title={title} onClose={onClose} className="fw-edit-dialog"><form onSubmit={e=>{e.preventDefault();if(onSubmit(draft)!==false)onClose();}}><div className="fw-form-grid">{fields.map(([key,label,kind])=><label className={`fw-field ${kind==='long'?'fw-full':''}`} key={key}><span>{label}</span>{kind==='short'?<input aria-label={label} value={draft[key]??''} onChange={e=>setDraft({...draft,[key]:e.target.value})}/>:<textarea aria-label={label} rows={kind==='long'?6:3} value={draft[key]??''} onChange={e=>setDraft({...draft,[key]:e.target.value})}/>}</label>)}</div>{typeof children==='function'?children(draft,setDraft):children}<footer><button type="button" className="secondary" onClick={onClose}>取消</button><button className="primary">保存</button></footer></form></CreatorDialog>;}
export const eventFields=[['title','小事件名称','short'],['summary','事件内容'],['actualTime','实际时间','short'],['before','前置状态'],['after','行动结果'],['motive','人物动机'],['foreshadow','伏笔与回收']];
export const categories=['时代与背景','核心脑洞','世界规则','个人金手指'];
