import React,{useState} from 'react';
import {Plus,Sparkles,Trash2,Check} from 'lucide-react';
import {Heading,AgentSelect,Panel,Field,Empty,Tag,EditDialog,categories} from './FrameworkParts.jsx';

export function IdeasPane({f,command,run,busy}){
 const add=()=>{const text=f.ideaDraft?.trim();if(text&&command({type:'idea.add',idea:{text,included:true}}))command({type:'idea.draft',text:''});};
 return <><Heading title="灵感" help="想到什么就记下来，整理交给 Agent。"><button className="primary" disabled={busy||!f.ideas.some(i=>i.included)} onClick={()=>run({task:'frameworkIdeas'})}><Sparkles size={15}/>整理灵感</button></Heading>
 <div className="fw-ideas-layout"><Panel title="整理摘要" className="fw-summary-panel"><Field label="灵感整理摘要" rows={16} value={f.ideaSummary} placeholder="整理后的想法会显示在这里，也可以直接修改。" onCommit={text=>command({type:'idea.summary',text})}/></Panel>
 <div className="fw-idea-capture"><Panel title="随手记"><Field label="新的灵感" value={f.ideaDraft||''} rows={8} placeholder="一句话、一段情节、一个画面……直接写下来。" onCommit={text=>command({type:'idea.draft',text})}/><div className="fw-actions fw-end"><small>输入自动保存到本地</small><button className="primary" onClick={add}><Plus size={15}/>存入收集箱</button></div></Panel>
 <details className="fw-idea-archive"><summary>灵感收集箱 · {f.ideas.length} 条原始想法</summary><div>{f.ideas.map(idea=><article className="fw-note" key={idea.id}><Field draftKey={idea.id} label="原始灵感" value={idea.text} onCommit={text=>command({type:'idea.update',id:idea.id,patch:{text}})}/><div className="fw-row"><label className="fw-check"><input type="checkbox" checked={!!idea.included} onChange={e=>command({type:'idea.update',id:idea.id,patch:{included:e.target.checked}})}/>参与整理</label><button className="ghost danger" aria-label="删除灵感" onClick={()=>command({type:'idea.remove',id:idea.id})}><Trash2 size={14}/></button></div></article>)}{!f.ideas.length&&<Empty>记下的原始想法保留在这里。</Empty>}</div></details></div></div></>;
}

function SettingCandidate({item,f,command}){const [choice,setChoice]=useState('keep'),[text,setText]=useState(item.text||'');const previous=f.settings.items.filter(old=>(item.conflictsWith||[]).includes(old.id));return <article className="fw-conflict"><div className="fw-row"><strong>{item.category||'补充设定'}</strong><Tag warn>{previous.length?'冲突待选择':'候选待采用'}</Tag></div><div className="fw-two"><div><small>原有设定</small><p>{previous.map(x=>x.text).join('\n')||'没有匹配的旧条目'}</p></div><div><small>补充内容</small><p>{item.text}</p></div></div>{item.reason&&<p className="fw-muted">检查依据：{item.reason}</p>}{previous.length?<><label className="fw-check"><input type="radio" checked={choice==='keep'} onChange={()=>setChoice('keep')}/>保留旧条，不采用补充</label><label className="fw-check"><input type="radio" checked={choice==='replace'} onChange={()=>setChoice('replace')}/>用补充替换旧条</label><label className="fw-check"><input type="radio" checked={choice==='merge'} onChange={()=>setChoice('merge')}/>人工合并后采用</label>{choice==='merge'&&<label className="fw-field"><span>合并后的正式设定</span><textarea aria-label="合并后的正式设定" value={text} onChange={e=>setText(e.target.value)}/></label>}<button className="primary" onClick={()=>command({type:'settings.resolve',id:item.id,choice,...(choice==='merge'?{text}:{})})}>确认选择</button></>:<div className="fw-actions"><button className="primary" onClick={()=>command({type:'settings.resolve',id:item.id,choice:'replace'})}>采用补充设定</button><button className="secondary" onClick={()=>command({type:'settings.resolve',id:item.id,choice:'keep'})}>留存不采用</button></div>}</article>;}

export function SettingsPane({f,command,run,busy}){const [supplement,setSupplement]=useState(''),[add,setAdd]=useState(false);return <><Heading title="先把世界与人物的规则讲清楚" help="补充内容经检查成为候选。先明确处理冲突，再确认这一版设定。"><button className="secondary" onClick={()=>setAdd(true)}><Plus size={15}/>手动添加候选</button><button className="primary" disabled={!!f.settings.pending.length||!f.settings.items.length} onClick={()=>command({type:'settings.confirm'})}><Check size={15}/>确认设定</button></Heading><div className={`fw-info ${f.settings.confirmed&&!f.settings.pending.length?'good':'warn'}`}>设定 V{f.settings.revision} · {f.settings.confirmed&&!f.settings.pending.length?'已确认':'待确认'} · {f.settings.pending.length} 条补充待处理</div><div className="fw-two">{categories.map(category=><Panel key={category} title={category}>{f.settings.items.filter(x=>x.category===category).map(item=><article className="fw-note" key={item.id}><p>{item.text}</p><button className="secondary" onClick={()=>{setSupplement(item.text);}}>以这条为基础补充</button></article>)}{!f.settings.items.some(x=>x.category===category)&&<Empty>尚未确认{category}</Empty>}</Panel>)}</div>{f.settings.items.filter(x=>!categories.includes(x.category)).map(item=><Panel key={item.id} title={item.category||'其他设定'}><p>{item.text}</p></Panel>)}<Panel title="补充设定并检查"><label className="fw-field"><span>新的设定或调整要求</span><textarea aria-label="补充设定" rows={4} value={supplement} onChange={e=>setSupplement(e.target.value)} placeholder="描述新增规则，或指出哪条旧规则需要调整…"/></label><div className="fw-actions"><AgentSelect label="设定检查接口"/><button className="primary" disabled={busy||!supplement.trim()} onClick={()=>run({task:'frameworkSettingsCheck',text:supplement})}><Sparkles size={15}/>检查补充设定</button></div></Panel>{f.settings.pending.map(item=><SettingCandidate key={item.id} item={item} f={f} command={command}/>)}{add&&<EditDialog title="手动添加设定候选" fields={[["text","补充设定","long"]]} initial={{category:categories[0],conflictsWith:[]}} onClose={()=>setAdd(false)} onSubmit={item=>item.text?.trim()?command({type:'settings.propose',items:[item]}):false}>{(draft,setDraft)=><><label className="fw-field"><span>设定类别</span><select aria-label="设定类别" value={draft.category} onChange={e=>setDraft({...draft,category:e.target.value})}>{categories.map(c=><option key={c}>{c}</option>)}</select></label><span className="fw-muted">勾选需要替换或合并的旧条；保留为空会新增设定。</span>{f.settings.items.map(x=><label className="fw-check" key={x.id}><input type="checkbox" checked={draft.conflictsWith.includes(x.id)} onChange={e=>setDraft({...draft,conflictsWith:e.target.checked?[...draft.conflictsWith,x.id]:draft.conflictsWith.filter(id=>id!==x.id)})}/>{x.text}</label>)}</>}</EditDialog>}</>;}
