import React,{useEffect,useRef,useState} from 'react';
import {CreatorDialog} from '../CreatorDialogs.jsx';
import {FormattedText} from '../../components/FormattedText.jsx';
import {splitScreenplayScenes,screenplayCharacterCount} from '../../../core/screenplayScenes.js';
import {Plus,Sparkles,Check,Square,Trash2,RotateCcw,ArrowUp,ArrowDown} from 'lucide-react';
import {frameworkState} from '../../../core/frameworkWorkflow.js';
import {applyFrameworkRecord} from '../../../core/frameworkAi.js';
import {Heading,AgentSelect,Panel,Field,Empty,Tag} from './FrameworkParts.jsx';

const uid=()=>crypto.randomUUID();
const blankEpisode=i=>({id:uid(),title:`第${i+1}集`,content:'',eventIds:[],result:'',finalConfirmed:false});
export function PlansPane(props){return <EpisodeWorkspace {...props} mode="outline"/>;}
export function ScriptPane(props){return <EpisodeWorkspace {...props} mode="script"/>;}
function EpisodeWorkspace({project,f,rows,command,run,busy,agent,getState,setState,onError,navigate,mode,episodeSelection,setEpisodeSelection}){
 const [count,setCount]=useState(''),[batch,setBatch]=useState(null),[planDialog,setPlanDialog]=useState(false),[countMode,setCountMode]=useState('auto'),[planCount,setPlanCount]=useState('40'),[planRequirements,setPlanRequirements]=useState(''),[selectedScene,setSelectedScene]=useState('');
 const token=useRef(null),plan=f.plans.find(p=>p.id===f.activePlanId)||f.plans[0],episode=plan?.episodes.find(e=>e.id===(episodeSelection?.planId===plan?.id?episodeSelection.episodeId:''))||plan?.episodes[0],script=mode==='script';
 const [bodyDraft,setBodyDraft]=useState(episode?.result||'');
 useEffect(()=>{setBodyDraft(episode?.result||'');},[episode?.id,episode?.result]);
 useEffect(()=>{setSelectedScene('');},[episode?.id]);
 const sceneData=splitScreenplayScenes(bodyDraft),scene=sceneData.scenes.find(s=>s.id===selectedScene);
 useEffect(()=>{if(plan&&!f.plans.some(p=>p.id===f.activePlanId))command({type:'plan.activate',id:plan.id});},[plan?.id,f.activePlanId]);
 useEffect(()=>()=>{if(token.current)token.current.stopped=true;},[]);
 const setSelected=id=>setEpisodeSelection({planId:plan?.id,episodeId:id});
 useEffect(()=>{if(token.current&&token.current.planId!==plan?.id){token.current.stopped=true;agent.cancel('script',project.id);setBatch(null);}},[plan?.id]);
 const liveProject=()=>getState?.()?.scriptProjects?.find(p=>p.id===project.id)||project;
 const activate=id=>{if(token.current){token.current.stopped=true;agent.cancel('script',project.id);setBatch(null);}command({type:'plan.activate',id});setSelected('');};
 const create=()=>{const id=uid();if(command({type:'plan.add',draft:true,plan:{id,name:`手动版 ${f.plans.length+1}`,episodes:Array.from({length:Number(count)||1},(_,i)=>blankEpisode(i))}}))activate(id);};
 const add=()=>{const ep=blankEpisode(plan.episodes.length);if(command({type:'plan.update',id:plan.id,patch:{episodes:[...plan.episodes,ep]}}))setSelected(ep.id);};
 const update=patch=>command({type:'episode.update',planId:plan.id,episodeId:episode.id,draft:true,patch});
 const adopt=id=>{if(!id)return false;try{applyFrameworkRecord(getState?.()||{scriptProjects:[liveProject()]},project.id,id,{kind:'script'});setState(s=>{try{return applyFrameworkRecord(s,project.id,id,{kind:'script'});}catch(e){onError(e.message);return s;}});return true;}catch(e){onError(e.message);return false;}};
 const write=async ep=>{const targetPlan=plan.id;if(f.activePlanId!==targetPlan&&!command({type:'plan.activate',id:targetPlan}))return;const id=await run({task:'frameworkEpisode',planId:targetPlan,episodeId:ep.id});return adopt(id);};
 const stop=()=>{if(token.current)token.current.stopped=true;agent.cancel('script',project.id);setBatch(null);};
 const batchWrite=async()=>{if(!plan)return;if(f.activePlanId!==plan.id&&!command({type:'plan.activate',id:plan.id}))return;const job={stopped:false,planId:plan.id,failed:[]};token.current=job;setBatch({completed:0,total:plan.episodes.filter(e=>!e.result?.trim()).length});try{let completed=0;for(const ep of plan.episodes){if(ep.result?.trim())continue;if(job.stopped)break;const live=frameworkState(liveProject());if(live.activePlanId!==job.planId){job.terminalMessage='版本已切换，批量生成停止。已完成正文保留在原版本。';onError(job.terminalMessage);break;}setSelected(ep.id);const id=await run({task:'frameworkEpisode',planId:job.planId,episodeId:ep.id});if(job.stopped)break;if(!id){const failed=liveProject().creator.records.filter(r=>r.type==='ai').at(-1);if(failed?.errorCode==='FRAMEWORK_EPISODE_FORMAT'){job.failed.push(ep.title);continue;}job.terminalMessage=failed?.error||'任务未完成，请检查接口连接。';break;}if(!adopt(id)){job.failed.push(ep.title);continue;}setBatch(b=>b?{...b,completed:++completed}:b);}}finally{if(token.current===job){token.current=null;setBatch(null);if(job.failed.length)onError(`${job.stopped?'已停止生成，已完成正文保留。':job.terminalMessage||''}${job.stopped||job.terminalMessage?'\n':''}以下集保留原始结果待完善：${job.failed.join('、')}。可选择对应集更换接口再生成。`);}}};
 const move=delta=>{const episodes=[...plan.episodes],i=episodes.findIndex(e=>e.id===episode.id);[episodes[i],episodes[i+delta]]=[episodes[i+delta],episodes[i]];command({type:'plan.update',id:plan.id,patch:{episodes}});};
 const index=plan?.episodes.findIndex(e=>e.id===episode?.id)??0;
 return <><Heading title={script?'正文':'集纲'} help={script?'选择版本与集数，直接写作或让 Agent 生成。每个版本的正文独立保存。':'将完整故事划分成每集，安排详略、节奏和集尾期待。'}>
 {!script&&<><label className="fw-count">目标集数<input aria-label="目标集数" placeholder="自动" type="number" min="1" max="500" value={count} onChange={e=>setCount(e.target.value===''?'':Math.min(500,Math.max(1,Number(e.target.value)||1)))}/></label><button className="primary" disabled={busy} onClick={()=>{if(count){setCountMode('exact');setPlanCount(count);}setPlanDialog(true);}}><Sparkles size={15}/>AI 划分新版本</button></>}
 <button className="secondary" onClick={create}><Plus size={15}/>新建手动版</button>{script&&(batch?<button className="primary" onClick={stop}><Square size={15}/>停止 · {batch.completed}/{batch.total}</button>:<button className="primary" disabled={busy||!plan||plan.stale} onClick={batchWrite}><Sparkles size={15}/>生成未完成各集</button>)}</Heading>
 <div className="fw-episode-workspace"><nav className="fw-episode-directory" aria-label="版本与分集目录"><label className="fw-field"><span>集纲版本</span><select aria-label="选择集纲版本" value={plan?.id||''} onChange={e=>activate(e.target.value)}>{!f.plans.length&&<option value="">尚无版本</option>}{f.plans.map(p=><option key={p.id} value={p.id}>{p.name} · {p.episodes.length} 集</option>)}</select></label>
 {plan&&<><small>{plan.episodes.filter(e=>e.result?.trim()).length} / {plan.episodes.length} 集已有正文</small><div className="fw-episode-list">{plan.episodes.map((ep,i)=><button key={ep.id} className={episode?.id===ep.id?'active':''} onClick={()=>setSelected(ep.id)}><b>{String(i+1).padStart(2,'0')}</b><span>{ep.title||`第${i+1}集`}<small>{ep.result?.trim()?'已有正文':ep.content?'已有集纲':'待写作'}{ep.stale?' · 待复核':''}</small></span></button>)}</div><button className="secondary" onClick={add}><Plus size={15}/>添加集数</button><details className="fw-version-options"><summary>版本管理</summary><Field key={plan.id} draftKey={plan.id+'name'} label="版本名称" multiline={false} value={plan.name} onCommit={name=>command({type:'plan.update',id:plan.id,patch:{name}})}/><button className="ghost danger" onClick={()=>{if(window.confirm('删除这个版本？内容会保留在项目版本中，可恢复。'))command({type:'plan.delete',id:plan.id});}}>删除此版本</button></details></>}
 </nav><div className="fw-episode-page">{plan&&episode?<>
 <header><div className="fw-actions"><Tag>第 {index+1} 集</Tag><Field key={episode.id+'title'} draftKey={episode.id+'title'} label="本集标题" multiline={false} value={episode.title} onCommit={title=>update({title})}/></div><div className="fw-actions"><button className="ghost" aria-label="本集向前移动" disabled={index===0||!!batch} onClick={()=>move(-1)}><ArrowUp size={15}/></button><button className="ghost" aria-label="本集向后移动" disabled={index===plan.episodes.length-1||!!batch} onClick={()=>move(1)}><ArrowDown size={15}/></button><button className="ghost danger" aria-label="删除本集" disabled={plan.episodes.length===1||!!batch} onClick={()=>{if(window.confirm('删除本集？内容保留在项目历史中。'))command({type:'plan.update',id:plan.id,patch:{episodes:plan.episodes.filter(e=>e.id!==episode.id)}});}}><Trash2 size={15}/></button>{script&&<><AgentSelect compact label="本集生成接口"/><button className="primary" disabled={busy||!!batch||plan.stale} onClick={()=>write(episode)}><Sparkles size={15}/>{episode.result?.trim()?'重写本集':'生成本集'}</button></>}</div></header>
 {plan.stale&&<div className="fw-inline-notice">故事依据有变化，手动编辑仍可继续。<button className="secondary" onClick={()=>command({type:'plan.update',id:plan.id,patch:{stale:false}})}>已核对，继续使用本版</button></div>}
 <div className="fw-episode-tabs"><button className={!script?'active':''} onClick={()=>navigate('plans')}>本集集纲</button><button className={script?'active':''} onClick={()=>navigate('script')}>剧本正文</button><span>{episode.eventIds?.map(id=>rows.find(r=>r.event.id===id)?.code||'历史事件').join(' · ')}</span></div>
 {script&&<details className="fw-episode-outline"><summary>查看本集集纲</summary><p>{episode.content||episode.outline||'尚未填写'}</p>{episode.hook&&<p>集尾：{episode.hook}</p>}</details>}
 {script&&<div className="fw-scene-toolbar"><div className="fw-scene-heading"><span>本集场景</span><small>{sceneData.scenes.length} 个场景</small></div><div className="fw-scene-cards" role="group" aria-label="选择本集场景"><button type="button" aria-pressed={!scene} className={!scene?'active':''} onClick={()=>setSelectedScene('')}>完整正文</button>{sceneData.scenes.map((s,i)=><button type="button" key={i} aria-label={`场景 ${s.id}`} aria-pressed={scene?.id===s.id} title={s.header} className={scene?.id===s.id?'active':''} onClick={()=>setSelectedScene(s.id)}>{s.id}</button>)}</div></div>}
 {script&&scene?<section className="fw-scene-reading" aria-label={`场景${scene.id}`}><FormattedText text={scene.text}/></section>:<Field key={episode.id+mode} draftKey={episode.id+mode} label={script?'当前集剧本正文':'当前集提纲'} rows={16} value={script?episode.result:episode.content||episode.outline||''} onDraftChange={script?setBodyDraft:undefined} placeholder={script?'直接写本集正文，或点击“生成本集”。':'写下本集的完整内容、详略安排和结尾期待。'} onCommit={value=>update(script?{result:value,finalConfirmed:false}:{content:value})}/>}
 {script&&<div className="fw-script-stats" role="status">本集正文 {screenplayCharacterCount(bodyDraft).toLocaleString()} 字{scene?` · 当前场景 ${screenplayCharacterCount(scene.text).toLocaleString()} 字`:''}<small>不含空白字符</small></div>}
 {!script&&<details className="fw-episode-outline"><summary>事件分配与衔接</summary><div className="fw-event-picks">{rows.filter(r=>r.group).map(r=><label key={r.event.id}><input type="checkbox" checked={episode.eventIds?.includes(r.event.id)||false} onChange={e=>update({eventIds:e.target.checked?[...(episode.eventIds||[]),r.event.id]:(episode.eventIds||[]).filter(id=>id!==r.event.id)})}/>{r.code} {r.event.title}</label>)}</div><Field key={episode.id+'hook'} draftKey={episode.id+'hook'} label="集尾期待" value={episode.hook||''} onCommit={hook=>update({hook})}/><Field key={episode.id+'continuity'} draftKey={episode.id+'continuity'} label="与下一集衔接" value={episode.continuity||''} onCommit={continuity=>update({continuity})}/></details>}
 <footer><small>编辑自动保存到本地</small>{script?<div className="fw-actions"><AgentSelect compact label="本集检查接口"/><button className="secondary" disabled={busy} onClick={()=>run({task:'frameworkCheck',planId:plan.id,episodeId:episode.id})}>检查衔接</button><button className="secondary" disabled={!episode.result?.trim()||plan.stale} onClick={()=>update({finalConfirmed:true,stale:false})}><Check size={15}/>{episode.finalConfirmed?'本集已确认':'确认本集'}</button></div>:<button className="primary" onClick={()=>{activate(plan.id);navigate('script');}}>写本版正文</button>}</footer>
 </>:<div className="fw-reference-empty"><h3>{script?'从第一集开始写':'还没有集纲版本'}</h3><p>可以让 AI 划分完整故事，也可以先建一集，边写边增加。</p><button className="primary" onClick={create}>创建第一集</button></div>}</div></div>{planDialog&&<CreatorDialog title="划分新集纲版本" onClose={()=>setPlanDialog(false)} className="fw-assist-dialog fw-plan-requirements"><p>先说明集数和划分要求。Agent 将结合确认故事分集，结果先预览，再保存为新版本。</p><div className="fw-plan-count-options"><label>集数要求<select aria-label="集数要求方式" value={countMode} onChange={e=>setCountMode(e.target.value)}><option value="auto">按故事自动安排</option><option value="minimum">至少达到</option><option value="exact">准确集数</option></select></label>{countMode!=='auto'&&<label>集数<input aria-label="划分集数要求" type="number" min="1" max="500" value={planCount} onChange={e=>setPlanCount(e.target.value)}/></label>}</div><Field autoFocus label="集纲划分要求" draftKey="planRequirements" value="" onDraftChange={setPlanRequirements} onCommit={setPlanRequirements} placeholder="例如：至少40集，前三集完成穿越与第一次摆摊；感情推进放慢，每集结尾留期待，不增加新能力。"/><footer><AgentSelect label="集纲划分接口"/><button className="secondary" onClick={()=>setPlanDialog(false)}>收起，保留要求</button><button className="primary" disabled={busy||countMode!=='auto'&&(!Number.isInteger(Number(planCount))||Number(planCount)<1||Number(planCount)>500)} onClick={()=>{setPlanDialog(false);run({task:'frameworkPlan',...(countMode==='auto'?{}:countMode==='exact'?{episodeCount:Number(planCount)}:{minEpisodeCount:Number(planCount)})},planRequirements.trim()||'根据确认故事安排每集行动、节奏与结尾期待。');}}>开始划分</button></footer></CreatorDialog>}</>;
}

export function HistoryPane({f,command,records,review}){const [name,setName]=useState('');return <><Heading title="项目版本与旧资料" help="保存阶段版本，查看任务依据，恢复已删除集纲。旧项目资料完整保留。"/><Panel title="保存当前项目版本"><div className="fw-row"><input aria-label="项目版本名称" placeholder="为这一阶段起个名字" value={name} onChange={e=>setName(e.target.value)}/><button className="primary" onClick={()=>command({type:'version.snapshot',name:name.trim()||'手动保存版本'})}>保存版本</button></div></Panel><div className="fw-two">{f.archives.filter(a=>['version','plan'].includes(a.kind)).map(a=><Panel key={a.id} title={a.name||a.snapshot?.snapshotName||a.snapshot?.name||'已保存版本'} extra={<Tag>{a.kind==='plan'?'已删除集纲':'项目快照'}</Tag>}><small>{a.createdAt?new Date(a.createdAt).toLocaleString('zh-CN'):''}</small><p>保存的资料可恢复；当前正文仍按所属集纲版本保留。</p><button className="secondary" onClick={()=>{if(window.confirm('恢复此版本？当前资料会保留为历史。'))command({type:a.kind==='plan'?'plan.restore':'version.restore',id:a.id});}}><RotateCcw size={14}/>恢复</button></Panel>)}</div><Panel title="删除与修订的资料">{f.archives.filter(a=>!['version','plan'].includes(a.kind)).map(a=><details key={`${a.kind}:${a.id}:${a.createdAt}`}><summary>{a.snapshot?.title||a.snapshot?.name||'历史资料'} · {a.kind}</summary><pre className="fw-original">{JSON.stringify(a.snapshot,null,2)}</pre>{a.kind==='source'&&<button className="secondary" onClick={()=>command({type:'source.restore',id:a.id})}>恢复来源</button>}</details>)}</Panel><Panel title="任务与候选历史">{records.slice().reverse().map(r=><button className="fw-history-row" key={r.id} onClick={()=>review(r.id)}><span>{r.target?.task||'旧版任务'} · {r.model}</span><Tag warn={r.status==='failed'}>{r.status==='pending'?'待采用':r.status==='failed'?'失败':r.status==='cancelled'?'已停止':r.status==='adopted'?'已采用':r.status}</Tag><small>{r.createdAt?new Date(r.createdAt).toLocaleString('zh-CN'):''}</small></button>)}{!records.length&&<Empty>尚未运行任务。</Empty>}</Panel><Panel title="升级前保留的资料">{Object.entries(f.legacy||{}).map(([key,value])=><details key={key}><summary>{key}</summary><pre className="fw-original">{typeof value==='string'?value:JSON.stringify(value,null,2)}</pre></details>)}{!Object.keys(f.legacy||{}).length&&<Empty>本项目没有需要整理的旧版资料。</Empty>}</Panel></>;}
