// ============================================================
// apiProviders.js — API提供商配置
// ============================================================

export const API_PROVIDERS = {
  chatgptWeb: {
    name:'本机 ChatGPT（网页账号额度）',type:'chatgptWeb',defaultEndpoint:'',defaultModel:'auto',
    description:'通过独立浏览器使用 ChatGPT 网页默认模型，首次登录后测试后台正文',
    requiresApiKey:false,keyName:'apiKey',
  },
  doubaoWork: {
    name: '本机豆包工作（后台暂不可用）',
    type: 'doubaoWork',
    defaultEndpoint: '',
    defaultModel: 'auto',
    description: '前台自动操作已停用，后台账号连接暂不可用',
    requiresApiKey: false,
    keyName: 'apiKey',
  },
  geminiWeb: {
    name: '本机 Gemini（网页账号额度）',
    type: 'geminiWeb',
    defaultEndpoint: '',
    defaultModel: 'auto',
    description: '通过本机独立浏览器登录 Gemini 网页账号，模型从账号实时读取',
    requiresApiKey: false,
    keyName: 'apiKey',
  },
  codexLocal: {
    name: '本机 Codex（ChatGPT 额度）',
    type: 'codexLocal',
    defaultEndpoint: '',
    defaultModel: 'gpt-6-sol',
    description: '通过本机已登录的 Codex 处理文本，仅供这台电脑使用',
    requiresApiKey: false,
    keyName: 'apiKey',
  },
  hermesCompatible: {
    name: 'Hermes兼容',
    type: 'hermesCompatible',
    defaultEndpoint: 'http://localhost:11434/v1',
    defaultModel: '',
    description: '兼容 OpenAI API 格式的本地/自部署服务（如 Ollama、LM Studio 等）',
    requiresApiKey: false,
    keyName: 'apiKey',
  },
  openai: {
    name: 'OpenAI',
    type: 'openai',
    defaultEndpoint: 'https://api.openai.com/v1',
    defaultModel: 'gpt-4o',
    description: 'OpenAI 官方 API（GPT-4o, GPT-4, GPT-3.5 等）',
    requiresApiKey: true,
    keyName: 'apiKey',
  },
  deepseek: {
    name: 'DeepSeek',
    type: 'deepseek',
    defaultEndpoint: 'https://api.deepseek.com/v1',
    defaultModel: 'deepseek-chat',
    description: 'DeepSeek 官方 API（DeepSeek-V3, DeepSeek-R1 等）',
    requiresApiKey: true,
    keyName: 'apiKey',
  },
  openrouter: {
    name: 'OpenRouter',
    type: 'openrouter',
    defaultEndpoint: 'https://openrouter.ai/api/v1',
    defaultModel: '',
    description: 'OpenRouter 统一 API 网关，可访问多种模型',
    requiresApiKey: true,
    keyName: 'apiKey',
  },
  claudeCodePool: {
    name: 'Claude Code Pool',
    type: 'claudeCodePool',
    defaultEndpoint: 'https://api.anthropic.com/v1',
    defaultModel: 'claude-sonnet-4-20250514',
    description: 'Anthropic Claude 官方 API（Claude Opus, Sonnet, Haiku 等）',
    requiresApiKey: true,
    keyName: 'apiKey',
  },
  custom: {
    name: '自定义',
    type: 'custom',
    defaultEndpoint: '',
    defaultModel: '',
    description: '自定义 OpenAI 兼容 API 端点',
    requiresApiKey: false,
    keyName: 'apiKey',
  },
};
