import test from 'node:test';import assert from 'node:assert/strict';
import {recycleProject,restoreRecycledProject,purgeRecycledProjects,cleanupRecycle,setRecyclePolicy,recycleState} from './projectRecycle.js';
import {normalizeState,mergePersistedState,mergeDirectorSnapshot,deleteScriptProject,deleteFruitProject,deleteDirectorProject,deleteScriptLibraryItem} from './projectStore.js';
const day=86400000,at=Date.parse('2026-10-09T00:00:00Z');
const fixture=()=>({scriptProjects:[{id:'s',name:'洗稿',mode:'rewrite',groupId:'missing',creator:{records:[{output:'候选'}],worldSimulation:{worlds:[{name:'人生路线'}]}},episodes:[{id:'ep',result:'完整正文'}]}],fruitProjects:[{id:'f',name:'IP',creator:{mode:'ip'},episodes:[]}],directorProjects:[{id:'d',name:'导演',episodes:[{prompts:[{text:'提示词'}]}]}],scriptLibrary:[{id:'l',name:'收录',versions:[{content:'旧版'}]}]});
test('whole projects move to recycle with immutable snapshots, explicit dates, audit and default seven days',()=>{const s=fixture(),n=recycleProject(s,'script','s',{now:at});assert.equal(n.scriptProjects.length,0);assert.equal(s.scriptProjects.length,1);assert.equal(recycleState(n).policy.retentionDays,7);assert.equal(recycleState(n).items[0].deletedAt,new Date(at).toISOString());assert.deepEqual(recycleState(n).items[0].project,s.scriptProjects[0]);s.scriptProjects[0].episodes[0].result='later';assert.equal(recycleState(n).items[0].project.episodes[0].result,'完整正文');assert.equal(recycleState(n).audit[0].action,'trashed');assert.strictEqual(recycleProject(n,'script','s',{now:at}),n);});
test('all local project deletion helpers recycle and restore stable identities and original bodies',()=>{for(const [kind,fn,id,key] of [['script',deleteScriptProject,'s','scriptProjects'],['fruit',deleteFruitProject,'f','fruitProjects'],['director',deleteDirectorProject,'d','directorProjects'],['library',deleteScriptLibraryItem,'l','scriptLibrary']]){const s=fixture(),n=fn(s,id),item=recycleState(n).items[0],r=restoreRecycledProject(n,item.id,{now:at});assert.equal(r[key][0].id,id);assert.equal(recycleState(r).items.length,0);assert.equal(recycleState(r).tombstones.length,0);if(kind==='script'){assert.equal(r[key][0].groupId,null);assert.equal(r[key][0].episodes[0].result,'完整正文');}}});
test('restore never overwrites an existing same-id project and validates archive kinds',()=>{const n=recycleProject(fixture(),'script','s',{now:at}),item=recycleState(n).items[0];assert.throws(()=>restoreRecycledProject({...n,scriptProjects:[{id:'s',name:'现有项目'}]},item.id),/同编号/);assert.throws(()=>recycleProject(fixture(),'api','s'),/类型/);assert.throws(()=>recycleProject({...fixture(),directorProjects:[{id:'d',cloudProjectId:'cloud'}]},'director','d'),/云端/);});
test('expiry is inclusive at seven days, does not wipe younger items, and keeps bad/future timestamps',()=>{let n=recycleProject(fixture(),'script','s',{now:at});n=recycleProject(n,'fruit','f',{now:at+day});assert.strictEqual(cleanupRecycle(n,{now:at+7*day-1}),n);let cleaned=cleanupRecycle(n,{now:at+7*day});assert.equal(recycleState(cleaned).items.length,1);assert.equal(recycleState(cleaned).items[0].kind,'fruit');assert.equal(recycleState(cleaned).audit.at(-1).action,'expired');const bad={...n,projectRecycle:{...recycleState(n),items:recycleState(n).items.map(i=>({...i,deletedAt:'bad'}))}};assert.strictEqual(cleanupRecycle(bad,{now:at+100*day}),bad);assert.strictEqual(cleanupRecycle(n,{now:at-1}),n);});
test('manual-only mode never expires projects; rule updates are validated and affect existing items',()=>{let n=recycleProject(fixture(),'script','s',{now:at});n=setRecyclePolicy(n,{automatic:false,retentionDays:7},{now:at});assert.strictEqual(cleanupRecycle(n,{now:at+100*day}),n);n=setRecyclePolicy(n,{automatic:true,retentionDays:30},{now:at});assert.strictEqual(cleanupRecycle(n,{now:at+8*day}),n);assert.equal(recycleState(cleanupRecycle(n,{now:at+30*day})).items.length,0);for(const days of [0,-1,1.5,366,NaN])assert.throws(()=>setRecyclePolicy(n,{automatic:true,retentionDays:days}),/1.*365/);});
test('permanent clear records names without keeping payloads, leaves live projects and suppression metadata',()=>{let n=recycleProject(fixture(),'script','s',{now:at});n=recycleProject(n,'fruit','f',{now:at});const r=purgeRecycledProjects(n,recycleState(n).items.map(i=>i.id),{now:at});assert.equal(recycleState(r).items.length,0);assert.deepEqual(r.directorProjects,n.directorProjects);assert.equal(recycleState(r).tombstones.length,2);assert.ok(recycleState(r).audit.filter(a=>a.action==='purged').every(a=>a.name&&!a.project));});
test('director secondary files and stale cache cannot resurrect trashed or purged projects on reload',()=>{const s=fixture(),n=deleteDirectorProject(s,'d'),disk={...n,directorProjects:s.directorProjects};assert.equal(normalizeState(disk).directorProjects.length,0);assert.equal(mergePersistedState(s,disk).directorProjects.length,0);const cleared=purgeRecycledProjects(n,recycleState(n).items.map(i=>i.id));assert.equal(mergePersistedState(s,{...cleared,directorProjects:s.directorProjects}).directorProjects.length,0);assert.equal(normalizeState(restoreRecycledProject(n,recycleState(n).items[0].id)).directorProjects.length,1);});
test('old states gain an empty recycle bin without removing existing projects',()=>{const s=fixture(),n=normalizeState(s);assert.equal(n.scriptProjects.length,1);assert.equal(n.directorProjects.length,1);assert.equal(recycleState(n).items.length,0);assert.equal(recycleState(n).policy.retentionDays,7);});
test('newer cache recovers deletion, purge and restoration transactions against an older main file',()=>{
 for(const [kind,id,collection] of [['script','s','scriptProjects'],['fruit','f','fruitProjects'],['director','d','directorProjects'],['library','l','scriptLibrary']]){
  const old=fixture(),deleted=recycleProject(old,kind,id,{now:at});
  const merged=mergePersistedState(deleted,old);assert.equal(merged[collection].length,0);assert.equal(merged.projectRecycle.items.length,1);assert.equal(merged.projectRecycle.audit.at(-1).action,'trashed');
  const purged=purgeRecycledProjects(deleted,deleted.projectRecycle.items.map(i=>i.id),{now:at});
  assert.equal(mergePersistedState(purged,deleted).projectRecycle.items.length,0);assert.equal(mergePersistedState(deleted,purged).projectRecycle.items.length,0);
  const restored=restoreRecycledProject(deleted,deleted.projectRecycle.items[0].id,{now:at});
  const loaded=mergePersistedState(restored,deleted);assert.equal(loaded[collection].length,1);assert.equal(loaded[collection][0].id,id);assert.equal(loaded.projectRecycle.items.length,0);
 }
});
test('recycle recovery is excluded when loading a different data directory',()=>{const cached=recycleProject(fixture(),'script','s',{now:at}),destination=fixture();const loaded=mergePersistedState(cached,destination,{recoverRecycle:false});assert.equal(loaded.projectRecycle.items.length,0);assert.equal(loaded.scriptProjects.length,1);});
test('malformed recycle metadata fails closed rather than resetting automatic cleanup rules',()=>{for(const projectRecycle of [{version:2},{items:null},{policy:{automatic:true,retentionDays:0}},{policy:{retentionDays:7}},{audit:[null]},{tombstones:null},{items:[{id:'x',kind:'constructor',projectId:'s',project:{id:'s'}}]}])assert.throws(()=>normalizeState({...fixture(),projectRecycle}),/资料格式异常/);assert.throws(()=>recycleProject(fixture(),'constructor','s'),/类型/);});
test('director restoration in the main file survives an empty secondary file and an older deleted cache',()=>{const old=fixture(),trash=recycleProject(old,'director','d',{now:at}),restored=restoreRecycledProject(trash,trash.projectRecycle.items[0].id,{now:at+1});const loaded=mergePersistedState(trash,mergeDirectorSnapshot(restored,[]));assert.equal(loaded.directorProjects.length,1);assert.equal(loaded.directorProjects[0].id,'d');assert.equal(loaded.projectRecycle.items.length,0);assert.equal(mergePersistedState(old,mergeDirectorSnapshot(trash,old.directorProjects)).directorProjects.length,0);});
test('restored snapshots interrupt orphaned generation records and preserve partial output and world history',()=>{const s=fixture();s.scriptProjects[0].creator.records=[{id:'running',status:'running',output:'已生成半稿',generation:{status:'running'}}];s.scriptProjects[0].creator.worldSimulation.worlds[0].runs=[{id:'r',status:'running',output:'已有事件'}];const n=recycleProject(s,'script','s',{now:at}),r=restoreRecycledProject(n,n.projectRecycle.items[0].id,{now:at});assert.equal(r.scriptProjects[0].creator.records[0].status,'cancelled');assert.equal(r.scriptProjects[0].creator.records[0].output,'已生成半稿');assert.equal(r.scriptProjects[0].creator.records[0].generation.status,'interrupted');assert.equal(r.scriptProjects[0].creator.worldSimulation.worlds[0].runs[0].status,'interrupted');assert.equal(n.projectRecycle.items[0].project.creator.records[0].status,'running');});
