import React, { useEffect, useState } from 'react';
import { Bot, Play, Square, Check, History, Copy, Lock, Send } from 'lucide-react';
import { creatorModelOptions, CREATOR_TASK_RULES } from '../../core/creatorAi.js';
import { updateCreatorProject, adoptCreatorRecord, appendCreatorRecord } from '../../core/creatorWorkspace.js';
import { uid } from '../../core/projectStore.js';
import { CreatorDialog } from './CreatorDialogs.jsx';

export function CandidateList({records,project,kind,setState,onError,compact=false}) {
 const [view,setView]=useState(null),[selectedBranch,setSelectedBranch]=useState('');
 const adopt=(original,mode='replace',branch)=>{const record=branch===undefined?original:{...original,id:uid(),output:branch,status:'pending',sourceRecordId:original.id,selectedBranch:true};const apply=(s,allowStale=false)=>adoptCreatorRecord(branch===undefined?s:appendCreatorRecord(s,kind,project.id,record),kind,project.id,record.id,{mode,side:record.target?.side||'output',allowStale});try{setState(s=>apply(s));}catch(e){
  if(e.code==='CREATOR_STALE_RESULT'&&window.confirm('候选基于较早版本生成。请核对差异；仍要采用此候选替换当前内容吗？')){try{setState(s=>apply(s,true));}catch(err){onError(err.message);}}
  else onError(e.message);
 }};
 const reject=record=>setState(s=>{const p=s[kind==='fruit'?'fruitProjects':'scriptProjects'].find(p=>p.id===project.id);return updateCreatorProject(s,kind,project.id,{records:p.creator.records.map(r=>r.id===record.id?{...r,status:'rejected'}:r)});});
 const activeView=view?project.creator.records.find(r=>r.id===view.id)||view:null;
 return <div className={`creator-candidates ${compact?'compact':''}`}>{records.map(record=><article className="creator-candidate" key={record.id}><header><span>{record.status==='pending'?'待采用':record.status==='adopted'?'已采用':record.status==='failed'?'失败':record.status==='cancelled'?'已停止':record.status==='rejected'?'未采用':record.status==='running'?'运行中':'历史版本'}</span><small>{record.model||''} {record.createdAt?new Date(record.createdAt).toLocaleString('zh-CN',{hour12:false}):''}</small></header>{record.error&&<p className="creator-error">{record.error}</p>}{record.type==='story-history'&&<><pre>{record.output}</pre><button className="secondary" onClick={()=>{if(window.confirm('恢复这次操作之前的整套人物与事件？当前关联会保留为新的历史。'))adopt(record);}}>恢复人物事件版本</button></>}{record.type!=='story-history'&&record.output&&<><pre>{record.output}</pre><div className="creator-inline-actions"><button className="secondary" onClick={()=>{setView(record);setSelectedBranch('');}}><History size={14}/>查看／编辑</button>{record.status!=='running'&&record.status!=='failed'&&record.status!=='cancelled'&&(record.target?.section==='simulation'&&!record.selectedBranch?<button className="primary" onClick={()=>{setView(record);setSelectedBranch('');}}>选定分支</button>:<><button className="primary" onClick={()=>adopt(record)}><Check size={14}/>采用到{record.target?.side==='input'?'左侧':'成果'}</button><button className="secondary" onClick={()=>adopt(record,'append')}>追加</button>{record.status!=='adopted'&&<button className="ghost" onClick={()=>reject(record)}>留存不采用</button>}</>)}</div></>}</article>)}
 {activeView&&<CreatorDialog title="候选与当前内容对照" onClose={()=>setView(null)} className="creator-candidate-dialog"><p className="creator-muted">{activeView.target?.section==='simulation'&&!activeView.selectedBranch?'左侧保留完整推演。请在右侧仅填写选定分支的事件链及要采用的内容；其他分支继续保留为候选。':'当前内容在左，候选在右；只有选择采用后才写入。'}</p><div className="creator-pair"><textarea readOnly aria-label="当前内容对照" value={activeView.target?.section==='simulation'&&!activeView.selectedBranch?activeView.output||'':activeView.target?.section?project.creator.sections[activeView.target.section]?.[activeView.target.side||'output']||'':(()=>{const e=project.episodes.find(e=>e.id===activeView.target?.episodeId),input=activeView.target?.side==='input';return kind==='fruit'?(input?e?.rawText:e?.scriptText)||'':(input?e?.content:e?.result)||'';})()}/><textarea aria-label="编辑候选" value={activeView.target?.section==='simulation'&&!activeView.selectedBranch?selectedBranch:activeView.output||''} onChange={e=>{const output=e.target.value;if(activeView.target?.section==='simulation'&&!activeView.selectedBranch){setSelectedBranch(output);return;}setState(s=>{const p=s[kind==='fruit'?'fruitProjects':'scriptProjects'].find(p=>p.id===project.id);return updateCreatorProject(s,kind,project.id,{records:p.creator.records.map(r=>r.id===activeView.id?{...r,output}:r)});});}}/></div><footer><button className="secondary" onClick={()=>navigator.clipboard?.writeText(activeView.output||'')}><Copy size={14}/>复制</button><button className="primary" disabled={activeView.target?.section==='simulation'&&!activeView.selectedBranch&&!selectedBranch.trim()} onClick={()=>{adopt(activeView,'replace',activeView.target?.section==='simulation'&&!activeView.selectedBranch?selectedBranch:undefined);setView(null);}}>{activeView.target?.section==='simulation'&&!activeView.selectedBranch?'仅采用选定分支':'采用候选'}</button></footer></CreatorDialog>}
 </div>;
}

export function AgentPanel({project,kind,state,setState,agent,target,onError,chat=false,defaultInstruction='',actionLabel='生成候选',onRun}) {
 const key=target.section||target.episodeId||'project',options=creatorModelOptions(state.apiProfiles),saved=project.creator.runConfig?.[key]||{};
 const legacySkill=project.episodes.find(e=>e.id===target.episodeId)?.selectedSkill;
 const defaultSkill=state.skills.find(s=>s.id===legacySkill||s.name===legacySkill)?.id||(kind==='fruit'?state.skills[0]?.id||'':'');
 const [selection,setSelection]=useState(saved.selection||options[0]?.selectionId||''),[customModel,setCustomModel]=useState(saved.customModel||''),[skillId,setSkillId]=useState(saved.skillId??defaultSkill),[scope,setScope]=useState(saved.scope||'project'),[instruction,setInstruction]=useState(''),[skillView,setSkillView]=useState(false),[history,setHistory]=useState(false);
 useEffect(()=>{const c=project.creator.runConfig?.[key]||{};setSelection(c.selection||options[0]?.selectionId||'');setCustomModel(c.customModel||'');setSkillId(c.skillId??defaultSkill);setScope(c.scope||'project');setInstruction('');},[project.id,key]);
 const current=options.find(o=>o.selectionId===selection),profile=current?{...current,model:customModel.trim()||current.model}:null,skill=state.skills.find(s=>s.id===skillId),activity=agent.activity[`${kind}:${project.id}`]||{};
 const [loadingModels,setLoadingModels]=useState(false);
 const refreshModels=async()=>{setLoadingModels(true);try{const rows=await agent.discoverModels(current);if(!Array.isArray(rows)||!rows.length)throw new Error('接口未返回模型列表，可在下方手动指定模型');setState(s=>({...s,apiProfiles:s.apiProfiles.map(p=>p.id===current.id?{...p,models:rows}:p)}));}catch(e){onError(e.message);}finally{setLoadingModels(false);}};
 const configure=patch=>setState(s=>{const p=s[kind==='fruit'?'fruitProjects':'scriptProjects'].find(p=>p.id===project.id);return updateCreatorProject(s,kind,project.id,{runConfig:{...p.creator.runConfig,[key]:{selection,customModel,skillId,scope,...patch}}});});
 const run=async(request=instruction)=>{try{if(!profile)throw new Error('请先在 API 接口配置模型，或重新选择有效接口');if(kind==='fruit'&&!skillId)throw new Error('请选择完整 Skill 再转换');
  const config={selection,customModel,skillId,scope};setState(s=>{const p=s[kind==='fruit'?'fruitProjects':'scriptProjects'].find(p=>p.id===project.id);return updateCreatorProject(s,kind,project.id,{runConfig:{...p.creator.runConfig,[key]:config}});});
  const args={kind,projectId:project.id,target,instruction:request.trim()||defaultInstruction||CREATOR_TASK_RULES[target.task||key]||'按当前内容协同创作',profile,skillId,scope,chat};
  if(onRun)await onRun(args);else await agent.run(args);setInstruction('');
 }catch(e){onError(e.message);}};
 const records=project.creator.records.filter(r=>r.type==='ai'&&(r.target?.section===target.section&&target.section||r.target?.episodeId===target.episodeId&&target.episodeId));
 const messages=(project.creator.chat||[]).filter(m=>m.stage===key);
 return <aside className={`creator-agent ${chat?'creator-chat':''}`}><header><strong><Bot size={17}/>{chat?'项目协作':'Agent 辅助'}</strong><button className="ghost" onClick={()=>setHistory(true)}><History size={15}/>历史</button></header><div className="creator-agent-config">
 <label>接口与模型<select aria-label="创作模型" value={selection} onChange={e=>{setSelection(e.target.value);configure({selection:e.target.value});}}>{!current&&<option value="">请选择接口</option>}{options.map(o=><option key={o.selectionId} value={o.selectionId}>{o.name} · {o.model}</option>)}</select></label>
 <details><summary>查询或指定接口内的其他模型</summary><button className="secondary" disabled={!current||current.provider==='codexLocal'||loadingModels} onClick={refreshModels}>{loadingModels?'正在查询…':'查询此接口模型'}</button><input aria-label="自定义模型名称" placeholder="模型名称，留空使用上方选择" value={customModel} onChange={e=>{setCustomModel(e.target.value);configure({customModel:e.target.value});}}/></details>
 <label>Skill<select aria-label="创作 Skill" value={skillId} onChange={e=>{setSkillId(e.target.value);configure({skillId:e.target.value});}}><option value="">{kind==='fruit'?'请选择 Skill':'不附加 Skill'}</option>{state.skills.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></label>{skill&&<button className="ghost creator-skill-link" onClick={()=>setSkillView(true)}>完整 Skill · {1+(skill.files?.length||0)} 个文件</button>}
 <label>参考范围<select value={scope} onChange={e=>{setScope(e.target.value);configure({scope:e.target.value});}}><option value="project">当前内容＋全剧与项目资料</option><option value="current">当前内容＋已采用核心设定</option></select></label>
 </div>{chat&&<div className="creator-chat-messages">{!messages.length&&<p className="creator-muted">把你的想法说出来，我们一起整理。当前采用的设定与项目资料会随模型切换保留。</p>}{messages.map(m=><article key={m.id} className={m.role}><small>{m.role==='user'?'我':m.role==='decision'?'已采用决定':`Agent · ${m.model||''}`}</small><pre>{m.content}</pre></article>)}</div>}
 <textarea aria-label={chat?'与 Agent 对话':'本次创作要求'} className="creator-instruction" placeholder={chat?'补充灵感、讨论冲突，或描述想修改的地方…':'补充本次要求，可留空…'} value={instruction} onChange={e=>setInstruction(e.target.value)} onKeyDown={e=>{if((e.ctrlKey||e.metaKey)&&e.key==='Enter'&&!activity.running)run();}}/>
 <div className="creator-run-row">{activity.running?<><span role="status">{activity.label}</span><button className="secondary" onClick={()=>agent.cancel(kind,project.id)}><Square size={14}/>停止</button></>:<button className="primary" onClick={()=>run()} disabled={chat&&!instruction.trim()}>{chat?<Send size={15}/>:<Play size={15}/>} {chat?'发送并协作':actionLabel}</button>}</div>
 <CandidateList records={records.filter(r=>r.status==='pending').slice(-3).reverse()} project={project} kind={kind} setState={setState} onError={onError} compact/>
 {history&&<CreatorDialog title="项目任务与历史" onClose={()=>setHistory(false)} className="creator-history-dialog"><p className="creator-muted">所有任务均保留在项目资料中，采用后的内容才成为正式成果。</p><CandidateList records={project.creator.records.filter(r=>r.output||r.error).slice().reverse()} project={project} kind={kind} setState={setState} onError={onError}/></CreatorDialog>}
 {skillView&&skill&&<CreatorDialog title={skill.name} onClose={()=>setSkillView(false)}><pre className="creator-doc-view">{skill.content}{(skill.files||[]).map(f=>`\n\n【${f.path}】\n${f.content}`).join('')}</pre><p className="creator-muted">运行附加这些完整文件。文本文档中的脚本不会自动作为本地程序执行。</p></CreatorDialog>}
 </aside>;
}
