import { RewriteWorkspace } from './RewriteWorkspace.jsx';
import React, { useState, useEffect, useMemo } from 'react';
import { ArrowLeft, Plus, BookOpen, FileText, Download, Save, FolderOpen, Lock, History } from 'lucide-react';
import { ProjectCardHub } from '../v06/ProjectCardHub.jsx';
import { createProjectGroup,renameProjectGroup,deleteProjectGroup,organizeProject,uid } from '../../core/projectStore.js';
import { splitFullScript } from '../../core/scriptImport.js';
import { prepareCompletedProject,appendPreparedProject,projectNameFromFile,parseCompletedScript } from '../../core/creatorDirectImport.js';
import { normalizeCreatorProject,filterCreatorProjects,createCreatorProject,addCreatorEpisode,importCreatorSource,CREATOR_FRAMEWORK_STAGES,CREATOR_REWRITE_SECTIONS,adoptCreatorRecord,updateCreatorProject } from '../../core/creatorWorkspace.js';
import { creatorModelOptions,CREATOR_TASK_RULES } from '../../core/creatorAi.js';
import { useCreatorAgent } from './useCreatorAgent.js';
import { CreatorDialog,ExportDialog,SourceDialog } from './CreatorDialogs.jsx';
import { EpisodeEditor,MasterView,RewriteSection } from './CreatorEditor.jsx';
import { FrameworkWorkspace } from './FrameworkWorkspace.jsx';
import { FrameworkCreationWorkspace } from './FrameworkCreationWorkspace.jsx';
import { CreatorLibrary } from './CreatorLibrary.jsx';
import { CandidateList } from './AgentPanel.jsx';
import { IPWorkspace } from './IPWorkspace.jsx';
import { useIPAgent } from './useIPAgent.js';

const readMemory=(key,fallback)=>{try{return localStorage.getItem(key)||fallback;}catch{return fallback;}};
const remember=(key,value)=>{try{localStorage.setItem(key,value);}catch{}};
const names={fruit:'果子库',rewrite:'洗稿',free:'原创·自由创作',framework:'原创·框架式创作'};
export function CreatorWorkspace({area,state,setState,getState,api,onNavigate,onSave,saveStatus}) {
 const [channel,setChannel]=useState(readMemory('xz-creator-channel','rewrite')),[originalFilter,setOriginalFilter]=useState('all');
 const [fruitId,setFruitId]=useState(readMemory('xz-creator-fruit','')),[scriptId,setScriptId]=useState(readMemory('xz-creator-script','')),[active,setActive]=useState('master');
 const [create,setCreate]=useState(false),[name,setName]=useState(''),[newMode,setNewMode]=useState('free'),[newGroup,setNewGroup]=useState(''),[exportOpen,setExportOpen]=useState(false),[archiveOpen,setArchiveOpen]=useState(false),[sourceOpen,setSourceOpen]=useState(false),[pendingSource,setPendingSource]=useState(null),[error,setError]=useState(''),[addNode,setAddNode]=useState(false),[nodeTitle,setNodeTitle]=useState(''),[nodeType,setNodeType]=useState('episode'),[materials,setMaterials]=useState(false),[collapsed,setCollapsed]=useState(false);
 const [completedDoc,setCompletedDoc]=useState(null),[importingCompleted,setImportingCompleted]=useState(false);
 const uploadCompleted=async()=>{setError('');setImportingCompleted(true);try{const file=await api.importFullScript();if(file){if(!file.content?.trim())throw new Error('文档没有可读取的正文');setCompletedDoc(file);}}catch(e){setError(e.message);}finally{setImportingCompleted(false);}};
 const confirmCompleted=()=>{try{const prepared=prepareCompletedProject(completedDoc,{kind:'fruit'});setState(s=>appendPreparedProject(s,prepared));setFruitId(prepared.id);remember('xz-creator-fruit',prepared.id);setActive('master');setCompletedDoc(null);setError('');}catch(e){setError(e.message);}};
 const agent=useCreatorAgent({state,setState,getState,api});
 const ipAgent=useIPAgent({state,setState,getState,api});
 const [finishedTab,setFinishedTab]=useState(readMemory('xz-finished-tab','fruit'));
 const switchFinished=tab=>{setFinishedTab(tab);remember('xz-finished-tab',tab);setFruitId('');remember('xz-creator-fruit','');};
 const kind=area==='fruit'?'fruit':'script',selectedId=kind==='fruit'?fruitId:scriptId;
 const rawProject=state[kind==='fruit'?'fruitProjects':'scriptProjects'].find(p=>p.id===selectedId);
 const project=useMemo(()=>normalizeCreatorProject(rawProject,kind),[rawProject,kind]),framework=project?.creator.mode==='framework',rewrite=project?.creator.mode==='rewrite';
 useEffect(()=>{if(project)setActive(project.creator.mode==='framework'?'inspiration':project.creator.mode==='rewrite'&&!project.creator.source?'source':'master');},[kind,project?.id]);
 const select=(id,selectedKind=kind)=>{const p=state[selectedKind==='fruit'?'fruitProjects':'scriptProjects'].find(p=>p.id===id);if(selectedKind==='fruit'){setFruitId(id);remember('xz-creator-fruit',id);}else{setScriptId(id);remember('xz-creator-script',id);if(p){const next=normalizeCreatorProject(p,'script').creator.mode==='rewrite'?'rewrite':'original';setChannel(next);remember('xz-creator-channel',next);}}setActive(p?.creator?.mode==='framework'?'inspiration':p?.mode==='rewrite'&&!p?.creator?.source?'source':p?.episodes?.[0]?.id||'master');setError('');};
 const goBack=()=>{if(kind==='fruit'){setFruitId('');remember('xz-creator-fruit','');}else{setScriptId('');remember('xz-creator-script','');}setActive('master');};
 const setMode=next=>{setChannel(next);remember('xz-creator-channel',next);setScriptId('');remember('xz-creator-script','');};
 const runStage=async(section,instruction='',analysis=false)=>{try{
  const saved=project.creator.runConfig?.[section]||project.creator.runConfig?.[active]||{},options=creatorModelOptions(state.apiProfiles,state.activeApiId),choice=options.find(p=>p.selectionId===saved.selection)||options[0];if(!choice)throw new Error('先在 API 接口中添加模型');
  const profile=choice;
  const id=await agent.run({kind,projectId:project.id,target:{section,side:analysis?'input':'output'},instruction:instruction||`${CREATOR_TASK_RULES[section]||'整理当前阶段'}${analysis?'仅分析对标原稿，保留来源集号与原文依据，不写我的新作。':''}`,profile,skillId:saved.skillId||'',scope:saved.scope||'project',chat:!analysis});
  if(analysis)setState(s=>adoptCreatorRecord(s,kind,project.id,id,{side:'input'}));
 }catch(e){setError(e.message);throw e;}};
 const analyze=async keys=>{setError('');try{for(const key of keys)await runStage(key,'',true);}catch{/* error already shown; successful modules remain */}};
 const chooseSource=doc=>{setSourceOpen(false);setPendingSource({...doc});};
 const sourceChanged=rewrite&&project.creator.source?.sourceProjectId&&state.fruitProjects.find(p=>p.id===project.creator.source.sourceProjectId)?.updatedAt!==project.creator.source.sourceUpdatedAt;
 if(area==='scripts')return <CreatorLibrary state={state} setState={setState} api={api} onOpenProject={(id,sourceKind)=>{const k=sourceKind==='fruit'?'fruit':'script';if(k==='fruit'){const ip=state.fruitProjects.find(p=>p.id===id)?.creator?.mode==='ip';setFinishedTab(ip?'ip':'fruit');remember('xz-finished-tab',ip?'ip':'fruit');}select(id,k);onNavigate(k==='fruit'?'fruit':'studio');}}/>;
 if(area==='fruit'&&(finishedTab==='ip'||project?.creator.mode==='ip'))return <IPWorkspace state={state} setState={setState} api={api} agent={ipAgent} selectedId={fruitId} onSelect={id=>select(id,'fruit')} onBack={goBack} onSwitchFruit={()=>switchFinished('fruit')} onSave={onSave} saveStatus={saveStatus}/>;
 if(!project){const projects=filterCreatorProjects(state[kind==='fruit'?'fruitProjects':'scriptProjects'],{kind,channel,originalFilter});
 return <div className="creator-hub">{kind==='fruit'&&<div className="creator-channel-bar"><div className="seg"><button className="active">果子库</button><button onClick={()=>switchFinished('ip')}>IP 库</button></div><span className="creator-muted">成品库 · 已有剧本的提取与沉淀</span></div>}{kind==='script'&&<div className="creator-channel-bar"><div className="seg"><button className={channel==='rewrite'?'active':''} onClick={()=>setMode('rewrite')}>洗稿</button><button className={channel==='original'?'active':''} onClick={()=>setMode('original')}>原创</button></div>{channel==='original'&&<div className="seg compact">{[['all','全部原创'],['free','自由创作'],['framework','框架式创作']].map(([v,label])=><button className={originalFilter===v?'active':''} key={v} onClick={()=>setOriginalFilter(v)}>{label}</button>)}</div>}</div>}
 <ProjectCardHub onUpload={kind==='fruit'?()=>{if(!importingCompleted)uploadCompleted();}:undefined} kind={kind==='fruit'?'fruit':'script'} title={kind==='fruit'?'果子库':channel==='rewrite'?'洗稿项目':'原创项目'} projects={projects} groups={state[kind==='fruit'?'fruitGroups':'scriptGroups']} onCreate={()=>{setName('');setNewMode(kind==='fruit'?'fruit':channel==='rewrite'?'rewrite':originalFilter==='framework'?'framework':'free');setCreate(true);}} onOpen={select} onRename={(id,n)=>setState(s=>organizeProject(s,kind,id,{name:n}))} onMoveToGroup={(id,groupId)=>setState(s=>organizeProject(s,kind,id,{groupId:groupId||null}))} onCreateGroup={n=>setState(s=>createProjectGroup(s,kind,n))} onRenameGroup={(id,n)=>setState(s=>renameProjectGroup(s,kind,id,n))} onDeleteGroup={id=>setState(s=>deleteProjectGroup(s,kind,id))} onDelete={id=>setState(s=>({...s,[kind==='fruit'?'fruitProjects':'scriptProjects']:s[kind==='fruit'?'fruitProjects':'scriptProjects'].filter(p=>p.id!==id)}))}/>
 {create&&<CreatorDialog title="新建创作项目" onClose={()=>setCreate(false)}><form onSubmit={e=>{e.preventDefault();if(!name.trim())return;const key=newMode==='fruit'?'fruitProjects':'scriptProjects',prepared=createCreatorProject({fruitProjects:[],scriptProjects:[]},{name:name.trim(),mode:newMode,groupId:newGroup||null})[key][0],id=prepared.id;setState(s=>({...s,[key]:[...(s[key]||[]),prepared]}));if(newMode==='fruit'){setFruitId(id);remember('xz-creator-fruit',id);}else{setScriptId(id);remember('xz-creator-script',id);}setActive(newMode==='framework'?'inspiration':newMode==='rewrite'?'source':'master');setCreate(false);}}><label>项目名称<input autoFocus aria-label="项目名称" value={name} onChange={e=>setName(e.target.value)}/></label>{kind==='script'&&channel==='original'&&<label>创作模式<select aria-label="原创模式" value={newMode} onChange={e=>setNewMode(e.target.value)}><option value="free">自由创作</option><option value="framework">框架式创作</option></select></label>}<label>分组<select value={newGroup} onChange={e=>setNewGroup(e.target.value)}><option value="">未分组</option>{state[kind==='fruit'?'fruitGroups':'scriptGroups'].map(g=><option key={g.id} value={g.id}>{g.name}</option>)}</select></label><footer><button type="button" className="secondary" onClick={()=>setCreate(false)}>取消</button><button className="primary" disabled={!name.trim()}>创建项目</button></footer></form></CreatorDialog>}
 {completedDoc&&<CreatorDialog title="上传完成剧本" onClose={()=>setCompletedDoc(null)} className="creator-upload-dialog"><div className="creator-upload-summary"><BookOpen size={24}/><div><strong>{projectNameFromFile(completedDoc.fileName)}</strong><p>{completedDoc.fileName} · {completedDoc.content.length.toLocaleString()} 字符{completedDoc.encoding?` · ${completedDoc.encoding}`:''}</p></div></div><p className="creator-muted">识别到 {parseCompletedScript(completedDoc.content).episodes.filter(e=>e.type==='episode').length} 集，用文件名创建项目。原文与剧本保留相同内容，可直接查看、导出与收录。</p>{error&&<p role="alert" className="creator-error">{error}</p>}<footer><button className="secondary" onClick={()=>setCompletedDoc(null)}>取消</button><button className="primary" onClick={confirmCompleted}>确认导入剧本</button></footer></CreatorDialog>}
 {importingCompleted&&<p role="status" className="creator-muted">正在读取文档…</p>}{error&&!completedDoc&&<p role="alert" className="creator-error">{error}</p>}
 </div>;}
 if(rewrite)return <RewriteWorkspace key={project.id} project={project} state={state} setState={setState} getState={getState} api={api} agent={agent} onBack={goBack} onSave={onSave} saveStatus={saveStatus}/>;
 if(framework)return <FrameworkCreationWorkspace key={project.id} project={project} state={state} setState={setState} getState={getState} api={api} agent={agent} onBack={goBack} onSave={onSave} saveStatus={saveStatus}/>;
 const episode=project.episodes.find(e=>e.id===active),sections=framework?CREATOR_FRAMEWORK_STAGES:rewrite?CREATOR_REWRITE_SECTIONS:[];
 return <div className={`creator-shell ${collapsed?'creator-directory-collapsed':''}`}><nav className="creator-directory"><div className="project-directory-fixed"><button className="ghost creator-back" onClick={goBack}><ArrowLeft size={16}/>全部项目</button><strong>{project.name}</strong><small>{names[project.creator.mode]}</small><button className={active==='master'?'active':''} onClick={()=>setActive('master')}><FileText size={15}/>总剧本</button>{rewrite&&<button className={active==='source'?'active':''} onClick={()=>setActive('source')}><BookOpen size={15}/>对标原剧本</button>}</div><div className="project-directory-scroll">{sections.length>0&&<span className="creator-nav-label">{framework?'构思与故事':'对标拆解'}</span>}{sections.map(s=><button key={s.key} className={active===s.key?'active':''} onClick={()=>setActive(s.key)}>{s.label}{project.creator.sections[s.key]?.locked&&<Lock size={12}/>}<span className="creator-nav-status">{project.creator.sections[s.key]?.accepted?'●':''}</span></button>)}<span className="creator-nav-label">{framework?'正文与分场':'分集创作'}</span>{project.episodes.map((e,i)=><button key={e.id} className={active===e.id?'active':''} onClick={()=>setActive(e.id)}><span className="creator-episode-number">{e.type==='episode'?String(project.episodes.filter(n=>n.type==='episode').findIndex(n=>n.id===e.id)+1).padStart(2,'0'):'序'}</span><span>{e.title}</span>{e.finalConfirmed&&!e.stale&&<span>✓</span>}</button>)}<button className="creator-add-node" onClick={()=>{setNodeTitle('');setNodeType('episode');setAddNode(true);}}><Plus size={15}/>添加{project.creator.mode==='free'?'内容／集数':'集数'}</button></div></nav>
 <main className="creator-main"><header className="creator-toolbar"><button className="ghost" title="折叠／展开目录" aria-label="折叠项目目录" onClick={()=>setCollapsed(!collapsed)}><FolderOpen size={17}/></button><div><strong>{project.name}</strong><small>{names[project.creator.mode]}</small></div><span className="creator-save-status">{saveStatus?.error?'保存失败，请重试':saveStatus?.saving?'正在保存…':saveStatus?.saved?'已保存到本地':'自动保存中'}</span><button className="secondary" onClick={()=>setMaterials(true)}><History size={15}/>项目资料</button><button className="secondary" onClick={()=>onSave?.()}><Save size={15}/>保存</button><button className="secondary" onClick={()=>setExportOpen(true)}><Download size={15}/>导出</button><button className="primary" onClick={()=>setArchiveOpen(true)}>收录剧本库</button></header>
 {error&&<div role="alert" className="creator-error-bar"><span>{error}</span><button className="ghost" onClick={()=>setError('')}>关闭</button></div>}
 {active==='source'&&rewrite?<section className="creator-source-page"><div className="creator-section-head"><h2>对标原剧本</h2><div className="creator-inline-actions"><button className="secondary" onClick={()=>setSourceOpen(true)}>{project.creator.source?'更新来源':'选择果子／上传文档'}</button><button className="primary" disabled={!project.creator.source?.content||agent.activity[`script:${project.id}`]?.running} onClick={()=>analyze(CREATOR_REWRITE_SECTIONS.map(s=>s.key))}>一键拆解</button></div></div>{sourceChanged&&<p className="creator-warning">果子库来源已有更新。此项目保留导入时版本，选择“更新来源”后可核对。</p>}<p className="creator-muted">{project.creator.source?`${project.creator.source.name} · ${project.creator.source.episodes.length}集 · ${project.creator.source.content.length}字`:'先选择一部对标剧本。来源与右侧新作独立保存。'}</p>{project.creator.source?<pre className="creator-doc-view">{project.creator.source.content}</pre>:<button className="creator-empty" onClick={()=>setSourceOpen(true)}>从果子库选择或上传 TXT / DOCX</button>}{agent.activity[`script:${project.id}`]?.running&&<p role="status">{agent.activity[`script:${project.id}`].label}<button className="secondary" onClick={()=>agent.cancel('script',project.id)}>停止</button></p>}</section>:episode?<EpisodeEditor project={project} episode={episode} kind={kind} state={state} setState={setState} api={api} agent={agent} onError={setError}/>:active==='master'?<MasterView project={project} kind={kind} setState={setState} onError={setError}/>:framework?<FrameworkWorkspace project={project} sectionKey={active} state={state} setState={setState} api={api} agent={agent} onError={setError} onStageRun={(k,i)=>runStage(k,i).catch(()=>{})}/>:rewrite?<RewriteSection project={project} sectionKey={active} label={sections.find(s=>s.key===active)?.label||active} state={state} setState={setState} agent={agent} onError={setError} onAnalyze={analyze}/>:<MasterView project={project} kind={kind} setState={setState} onError={setError}/>}
 </main>
 {sourceOpen&&<SourceDialog state={state} api={api} onClose={()=>setSourceOpen(false)} onChoose={chooseSource} onError={setError}/>}
 {pendingSource&&<CreatorDialog title="核对导入与分集" onClose={()=>setPendingSource(null)} className="creator-source-preview"><label>来源名称<input value={pendingSource.name||''} onChange={e=>setPendingSource({...pendingSource,name:e.target.value})}/></label><p className="creator-muted">识别到 {splitFullScript(pendingSource.content||'').episodes.length} 集；可修正正文中的集号后导入。已有新作不会被覆盖。</p><textarea aria-label="来源导入预览" value={pendingSource.content||''} onChange={e=>setPendingSource({...pendingSource,content:e.target.value})}/><footer><button className="secondary" onClick={()=>setPendingSource(null)}>取消</button><button className="primary" onClick={()=>{try{setState(s=>importCreatorSource(s,project.id,pendingSource));setPendingSource(null);setActive('source');}catch(e){setError(e.message);}}}>确认导入来源</button></footer></CreatorDialog>}
 {addNode&&<CreatorDialog title="添加创作内容" onClose={()=>setAddNode(false)}><form onSubmit={e=>{e.preventDefault();let nodeId;setState(s=>{const next=addCreatorEpisode(s,kind,project.id,{title:nodeTitle,type:nodeType});nodeId=next[kind==='fruit'?'fruitProjects':'scriptProjects'].find(p=>p.id===project.id).episodes.at(-1).id;return next;});setActive(nodeId);setAddNode(false);}}>{project.creator.mode==='free'&&<label>内容类型<select value={nodeType} onChange={e=>setNodeType(e.target.value)}><option value="episode">分集</option><option value="settings">设定</option><option value="custom">自定义章节</option></select></label>}<label>名称（可留空）<input aria-label="新增内容名称" placeholder="第N集／人物设定／自定义名称" value={nodeTitle} onChange={e=>setNodeTitle(e.target.value)}/></label><footer><button type="button" className="secondary" onClick={()=>setAddNode(false)}>取消</button><button className="primary">添加</button></footer></form></CreatorDialog>}
 {exportOpen&&<ExportDialog project={project} kind={kind} api={api} setState={setState} onClose={()=>setExportOpen(false)}/>}{archiveOpen&&<ExportDialog project={project} kind={kind} api={api} setState={setState} archive onClose={()=>setArchiveOpen(false)}/>}
 {materials&&<CreatorDialog title="项目资料与全部沉淀" onClose={()=>setMaterials(false)} className="creator-history-dialog"><p className="creator-muted">素材、聊天、候选与历史保留在本项目，当前采用的内容供后续创作参考。</p>{project.creator.directImport&&<details><summary>{project.creator.directImport.fileName} · 导入原件</summary><pre className="creator-doc-view">{project.creator.directImport.content}</pre></details>}{Object.entries(project.creator.legacy||{}).map(([key,text])=><details key={key}><summary>升级前保留的总稿：{key}</summary><pre className="creator-doc-view">{text}</pre><button className="secondary" onClick={()=>navigator.clipboard?.writeText(text)}>复制旧稿核对</button></details>)}<details><summary>全项目聊天（{project.creator.chat.length}条）</summary>{project.creator.chat.map(m=><article key={m.id}><small>{m.stage} · {m.role}</small><pre className="creator-doc-view">{m.content}</pre></article>)}</details><CandidateList records={project.creator.records.filter(r=>r.output||r.error||r.type==='deleted-node').slice().reverse()} project={project} kind={kind} setState={setState} onError={setError}/>{project.creator.records.filter(r=>r.type==='deleted-node').map(r=><button className="secondary" key={r.id} onClick={()=>{try{setState(s=>adoptCreatorRecord(s,kind,project.id,r.id,{}));}catch(e){setError(e.message);}}}>恢复已移除内容</button>)}</CreatorDialog>}
 </div>;
}
