import React, { useState } from 'react';
import { Upload, Video, PenLine, Plus, Download, Check, ArrowUp, ArrowDown, Trash2, FileText } from 'lucide-react';
import { uid } from '../../core/projectStore.js';
import { updateCreatorEpisode, updateCreatorSection, editCreatorMaster, buildCreatorText, addCreatorEpisode, removeCreatorNode, updateCreatorProject } from '../../core/creatorWorkspace.js';
import { CreatorDialog, ExportDialog } from './CreatorDialogs.jsx';
import { StoryLedger } from './StoryLedger.jsx';
import { AgentPanel } from './AgentPanel.jsx';

export function TextPair({leftTitle,rightTitle,left,right,onLeft,onRight,leftReadOnly=false,leftTools,rightTools}) {
 return <div className="creator-pair"><section className="creator-text-pane"><header><strong>{leftTitle}</strong>{leftTools}</header><textarea aria-label={leftTitle} value={left||''} readOnly={leftReadOnly} placeholder={leftReadOnly?'暂无来源内容':'在这里输入或编辑…'} onChange={e=>onLeft?.(e.target.value)}/><small>{String(left||'').length} 字{leftReadOnly?' · 来源只读':''}</small></section><section className="creator-text-pane"><header><strong>{rightTitle}</strong>{rightTools}</header><textarea aria-label={rightTitle} value={right||''} placeholder="在这里编辑；Agent 候选采用后会写入此处…" onChange={e=>onRight?.(e.target.value)}/><small>{String(right||'').length} 字 · 独立保存</small></section></div>;
}
export function MasterView({project,kind,setState,onError}) {
 const [edit,setEdit]=useState(null),[side,setSide]=useState('output');
 const update=(episode,field,value)=>setState(s=>updateCreatorEpisode(s,kind,project.id,episode.id,{[field]:value}));
 const field=kind==='fruit'?(side==='input'?'rawText':'scriptText'):(side==='input'?'content':'result');
 return <div className="creator-master"><div className="creator-section-head"><div><h2>总剧本</h2><p className="creator-muted">以下编辑直接写入对应分集；分集修改也会在这里同步。</p></div><div className="creator-inline-actions"><select aria-label="总稿一侧" value={side} onChange={e=>setSide(e.target.value)}><option value="output">{project.creator.mode==='rewrite'?'我的新作':'转换稿／分场稿'}</option><option value="input">原始稿／故事正文</option></select><button className="secondary" onClick={()=>setEdit(buildCreatorText(project,kind,side,{}))}>整稿编辑</button></div></div>
 {project.episodes.map((episode,i)=><section className="creator-master-node" key={episode.id}><header><h3>{episode.title||`第${i+1}集`}</h3><span>{episode.type==='episode'?'分集':'资料章节'}{episode.stale?' · 需要复核':''}</span></header><textarea aria-label={`总稿-${episode.title}`} value={episode[field]||''} onChange={e=>update(episode,field,e.target.value)}/></section>)}{!project.episodes.length&&<p className="creator-muted">先添加集数或导入剧本，内容会在此汇总。</p>}
 {edit!==null&&<CreatorDialog title="编辑整部稿件" onClose={()=>setEdit(null)} className="creator-master-dialog"><p className="creator-muted">保持各集标题作为边界。保存会更新同一组分集，不创建第二份总稿。</p><textarea aria-label="整部稿件编辑" value={edit} onChange={e=>setEdit(e.target.value)}/><footer><button className="secondary" onClick={()=>setEdit(null)}>取消</button><button className="primary" onClick={()=>{try{setState(s=>editCreatorMaster(s,kind,project.id,side,edit));setEdit(null);}catch(e){onError(e.message);}}}>保存到分集</button></footer></CreatorDialog>}
 </div>;
}

export function EpisodeEditor({project,episode,kind,state,setState,api,agent,onError}) {
 const fruit=kind==='fruit',rewrite=project.creator.mode==='rewrite',framework=project.creator.mode==='framework';
 const [frameworkTask,setFrameworkTask]=useState('scene'),[episodeExport,setEpisodeExport]=useState(false);
 const inputKey=fruit?'rawText':'content',outputKey=fruit?'scriptText':'result';
 const update=patch=>setState(s=>updateCreatorEpisode(s,kind,project.id,episode.id,patch));
 const selected=project.creator.source?.episodes?.filter(e=>(episode.sourceEpisodeIds||[]).includes(e.id))||[];
 const left=rewrite?selected.map(e=>`${e.title}\n${e.content}`).join('\n\n'):episode[inputKey]||'';
 const upload=async()=>{try{const file=await api.importFullScript();if(file){if(!file.content.trim())throw new Error('文件没有可读取的文本');if(episode[inputKey]&&!window.confirm('导入文档将替换本集左侧内容，当前稿会保存到历史。继续导入吗？'))return;setState(s=>{let next=s;if(episode[inputKey]){const p=s[kind==='fruit'?'fruitProjects':'scriptProjects'].find(p=>p.id===project.id);next=updateCreatorProject(s,kind,project.id,{records:[...p.creator.records,{id:uid(),type:'manual',target:{episodeId:episode.id,side:'input'},output:episode[inputKey],status:'history',createdAt:new Date().toISOString()}]});}return updateCreatorEpisode(next,kind,project.id,episode.id,{[inputKey]:file.content,fileName:file.fileName,inputType:'document'});});}}catch(e){onError(e.message);}};
 const video=async()=>{try{if(!api.importCreatorVideo)throw new Error('请在桌面应用中上传视频');const file=await api.importCreatorVideo();if(file)update({videoSource:file,fileName:file.fileName,inputType:'video'});}catch(e){onError(e.message);}};
 const move=delta=>{const index=project.episodes.findIndex(e=>e.id===episode.id),other=project.episodes[index+delta];if(!other)return;setState(s=>{const key=kind==='fruit'?'fruitProjects':'scriptProjects';return {...s,[key]:s[key].map(p=>{if(p.id!==project.id)return p;const episodes=[...p.episodes];[episodes[index],episodes[index+delta]]=[episodes[index+delta],episodes[index]];return {...p,episodes:episodes.map((e,i)=>i>=Math.min(index,index+delta)&&e[outputKey]?.trim()?{...e,stale:true}:e),updatedAt:new Date().toISOString()};})};});};
 return <div className="creator-episode"><div className="creator-section-head"><input className="creator-node-title" aria-label="节点标题" value={episode.title} onChange={e=>update({title:e.target.value})}/><div className="creator-inline-actions"><button className="secondary" onClick={()=>setEpisodeExport(true)}><Download size={15}/>导出本集</button><button className="ghost" title="上移" aria-label="上移当前节点" onClick={()=>move(-1)}><ArrowUp size={15}/></button><button className="ghost" title="下移" aria-label="下移当前节点" onClick={()=>move(1)}><ArrowDown size={15}/></button><button className="ghost" aria-label="移除当前节点" onClick={()=>{if(window.confirm(`移除${episode.title}？内容将保留在历史，可恢复。`))setState(s=>removeCreatorNode(s,kind,project.id,episode.id));}}><Trash2 size={15}/></button></div></div>
 {!rewrite&&<div className="creator-source-bar">{fruit&&<button className="secondary" onClick={video}><Video size={15}/>视频上传</button>}<button className="secondary" onClick={upload}><Upload size={15}/>文档上传</button><button className="secondary" onClick={()=>document.querySelector('.creator-pair textarea')?.focus()}><PenLine size={15}/>直接输入</button>{episode.fileName&&<span className="creator-muted">{episode.fileName}</span>}</div>}
 {episode.videoSource&&<p className="creator-warning">视频源已记录。当前文字接口请先在左侧粘贴转录或反推内容，再按 Skill 转换。</p>}
 {rewrite&&<div className="creator-source-bar"><strong>本集参考</strong>{(project.creator.source?.episodes||[]).map(source=><label className="creator-check" key={source.id}><input type="checkbox" checked={(episode.sourceEpisodeIds||[]).includes(source.id)} onChange={e=>update({sourceEpisodeIds:e.target.checked?[...(episode.sourceEpisodeIds||[]),source.id]:(episode.sourceEpisodeIds||[]).filter(id=>id!==source.id)})}/>{source.title}</label>)}</div>}
 {episode.stale&&<p className="creator-warning">故事正文或上游资料已有改动，请复核右侧稿件。现有内容仍保留。</p>}
 <TextPair leftTitle={fruit?'原始内容／沉浸式对话':rewrite?'对标本集内容':framework?'本集故事正文':'我的原稿'} rightTitle={rewrite?'我的新作':framework?'本集分场剧本':'Skill 转换稿'} left={left} right={episode[outputKey]} leftReadOnly={rewrite} onLeft={v=>update({[inputKey]:v,finalConfirmed:false})} onRight={v=>update({[outputKey]:v,finalConfirmed:false})} rightTools={framework?<button className="secondary" disabled={!episode.result?.trim()} onClick={()=>update({finalConfirmed:true,stale:false})}><Check size={14}/>{episode.finalConfirmed&&!episode.stale?'已确认终稿':'确认本集终稿'}</button>:null}/>
 {framework&&<label className="creator-source-bar">协作任务<select aria-label="分集协作任务" value={frameworkTask} onChange={e=>setFrameworkTask(e.target.value)}><option value="episode">协作写故事正文（左侧）</option><option value="scene">按场整理剧本（右侧）</option></select></label>}
 {framework&&<section className="creator-warning">本集关联事件：{(project.creator.story?.events||[]).filter(e=>e.episodeIds?.includes(episode.id)).map(e=>e.title).join(' → ')||'尚未分配，可在细纲／分集大纲的事件条目中关联本集。'}</section>}
 <AgentPanel key={episode.id} project={project} kind={kind} state={state} setState={setState} agent={agent} target={{episodeId:episode.id,side:framework&&frameworkTask==='episode'?'input':'output',inputSide:'input',task:framework?frameworkTask:'episode'}} onError={onError} actionLabel={framework?(frameworkTask==='scene'?'按场整理候选':'协作正文候选'):'运行转换'}/>
 {episodeExport&&<ExportDialog project={{...project,name:`${project.name}-${episode.title}`,episodes:[episode]}} kind={kind} api={api} setState={setState} onClose={()=>setEpisodeExport(false)} single/>}
 </div>;
}
export function RewriteSection({project,sectionKey,state,setState,agent,onError,label,onAnalyze}) {
 const section=project.creator.sections[sectionKey]||{};
 const update=patch=>setState(s=>updateCreatorSection(s,'script',project.id,sectionKey,patch));
 return <div className="creator-rewrite-section"><div className="creator-section-head"><h2>{label}</h2><button className="secondary" onClick={()=>onAnalyze([sectionKey])}>分析对标{label}</button></div><TextPair leftTitle={`对标${label}`} rightTitle={`我的${label}`} left={section.input} right={section.output} onLeft={v=>update({input:v})} onRight={v=>update({output:v,accepted:true})} rightTools={<button className="secondary" onClick={()=>{if(section.output&&!window.confirm('沿用将替换右侧当前内容。继续吗？'))return;update({output:section.input||'',accepted:true});}}>沿用左侧</button>}/><AgentPanel project={project} kind="script" state={state} setState={setState} agent={agent} target={{section:sectionKey,side:'output'}} onError={onError} defaultInstruction={`参考左侧对标${label}和我的新作设定，提出适用于我的作品的${label}，避免把对标人物设定当成我的已定设定。`}/>{['events','characters','outline','detail','timeline'].includes(sectionKey)&&<StoryLedger project={project} setState={setState} onError={onError} stage={sectionKey} sectionText={section.output||''}/>}</div>;
}
