import React, { useState } from 'react';
import { BookOpen, Download, ArrowLeft, PenLine, Trash2 } from 'lucide-react';
import { CreatorDialog } from './CreatorDialogs.jsx';

export function CreatorLibrary({state,setState,api,onOpenProject}) {
 const [selected,setSelected]=useState(null),[versionId,setVersionId]=useState(''),[search,setSearch]=useState(''),[query,setQuery]=useState(''),[font,setFont]=useState(16),[error,setError]=useState('');
 const item=state.scriptLibrary.find(i=>i.id===selected),versions=item?.versions?.length?item.versions:[{id:item?.id,version:1,content:item?.content||'',createdAt:item?.createdAt}],version=versions.find(v=>v.id===versionId)||versions.at(-1),content=version?.content||'';
 const exportDoc=async format=>{try{if(api.saveCreatorDocument)await api.saveCreatorDocument({name:`${item.name}-v${version.version||versions.indexOf(version)+1}`,content,format});else if(format==='txt')await api.saveTxt({name:item.name,content});else throw new Error('请在桌面应用中导出 Word');}catch(e){setError(e.message);}};
 const lines=content.split('\n');const headings=lines.map((text,line)=>({text,line})).filter(h=>/^(?:【)?(?:第[零一二三四五六七八九十百\d]+集|\d+-\d+\s)/.test(h.text));
 const highlight=text=>query?text.split(new RegExp(`(${query.replace(/[.*+?^${}()|[\]\\]/g,'\\$&')})`,'gi')).map((s,i)=>s.toLowerCase()===query.toLowerCase()?<mark key={i}>{s}</mark>:s):text;
 if(item)return <section className="creator-library-reader"><header className="creator-toolbar"><button className="secondary" onClick={()=>setSelected(null)}><ArrowLeft size={16}/>作品列表</button><strong>{item.name}</strong><select aria-label="作品版本" value={version.id||''} onChange={e=>setVersionId(e.target.value)}>{versions.map((v,i)=><option key={v.id||i} value={v.id}>第{v.version||i+1}版 · {v.createdAt?new Date(v.createdAt).toLocaleDateString('zh-CN'):''}</option>)}</select><button className="secondary" onClick={()=>exportDoc('txt')}>TXT</button><button className="secondary" onClick={()=>exportDoc('docx')}><Download size={15}/>Word</button>{state.scriptProjects.some(p=>p.id===item.sourceProjectId)&&<button className="primary" onClick={()=>onOpenProject(item.sourceProjectId)}><PenLine size={15}/>返回创作</button>}</header><div className="creator-reader-body"><nav><strong>作品目录</strong>{headings.map(h=><button key={h.line} onClick={()=>document.getElementById(`creator-reader-line-${h.line}`)?.scrollIntoView({block:'start',behavior:'smooth'})}>{h.text.replace(/[【】]/g,'')}</button>)}{!headings.length&&<span>完整作品</span>}</nav><section><div className="creator-reader-tools"><input aria-label="作品全文搜索" placeholder="搜索全文" value={query} onChange={e=>setQuery(e.target.value)}/><label>字号<select value={font} onChange={e=>setFont(Number(e.target.value))}>{[14,16,18,20].map(n=><option key={n}>{n}</option>)}</select></label><small>收录版本 · 后续创作改动不会改变此内容</small></div><pre className="creator-reader-content" style={{fontSize:font}}>{lines.map((line,i)=><span id={`creator-reader-line-${i}`} className="creator-reader-line" key={i}>{highlight(line)||'\u00a0'}</span>)}</pre></section></div>{error&&<p role="alert" className="creator-error">{error}</p>}</section>;
 return <main className="creator-library-hub"><div className="creator-section-head"><div><h1>剧本库</h1><p>在这里阅读已经完成的作品及其收录版本。</p></div><input aria-label="搜索剧本库" placeholder="搜索作品" value={search} onChange={e=>setSearch(e.target.value)}/></div><div className="creator-library-grid">{state.scriptLibrary.filter(i=>i.name.includes(search)).map(i=><article key={i.id}><BookOpen size={24}/><small>{i.modeLabel||(i.sourceMode==='rewrite'?'洗稿创作':'原创创作')}</small><h3>{i.name}</h3><p>{i.versions?.length||1}个收录版本 · {String(i.content||'').length}字</p><div className="creator-inline-actions"><button className="primary" onClick={()=>{setSelected(i.id);setVersionId('');setQuery('');}}>阅读全文</button><button className="ghost" aria-label={`删除作品${i.name}`} onClick={()=>{if(window.confirm('删除剧本库中的此作品及其收录版本？创作项目会保留。'))setState(s=>({...s,scriptLibrary:s.scriptLibrary.filter(x=>x.id!==i.id)}));}}><Trash2 size={15}/></button></div></article>)}</div>{!state.scriptLibrary.length&&<p className="creator-empty">完成创作后，点击“收录剧本库”，作品就会出现在这里。</p>}</main>;
}
