import React, { useState } from 'react';
import { Plus, Lock, Unlock, Check, BookOpen, Sparkles, Trash2 } from 'lucide-react';
import { updateCreatorSection, updateCreatorProject, addCreatorReference } from '../../core/creatorWorkspace.js';
import { addSkill } from '../../core/projectStore.js';
import { AgentPanel, CandidateList } from './AgentPanel.jsx';
import { StoryLedger } from './StoryLedger.jsx';
import { SourceDialog } from './CreatorDialogs.jsx';

const stages={inspiration:['灵感与核心设定','把零碎的脑洞、人物想法、时代背景说出来。Agent 整理后，你选择哪些成为当前设定。'],events:['零碎事件与全部事件','先收集故事想法；后续将采用的具体事件编号，关联人物、前置事件和所属大事件。'],timeline:['时间线与因果','分别记录实际发生时间、叙事顺序和事件因果。'],experience:['核心对标与经验','阅读1—3份核心材料，提炼节奏、反转、伏笔和时间组织方法。'],outline:['总纲','记录准备采用的大事件及它们在故事中的作用。'],skeleton:['故事骨架','把大事件按时间与因果连接成开端、转折到结局的主线。'],characters:['人物与人物线','重要人物在前，记录人物从起点到结局的命运轨迹、动机、关系和知情状态。'],detail:['细纲','把大事件里的具体行动串起来，检查内外因果和人物状态。'],simulation:['大世界模拟','固定已经采用的世界与骨架，探索可替换的具体过程。结果保留为候选分支。'],episodeOutline:['细纲与分集','按集安排事件、目标、冲突与衔接，然后进入左侧分集写故事正文。']};
stages.settings=['核心设定','整理类型、题材、脑洞、世界背景和人物特点，明确能力边界与尚待讨论的问题。'];
export function FrameworkWorkspace({project,sectionKey,state,setState,api,agent,onError,onStageRun}) {
 const [referenceDialog,setReferenceDialog]=useState(false),[recordsOpen,setRecordsOpen]=useState(false),[notice,setNotice]=useState('');
 const section=project.creator.sections[sectionKey]||{},[title,help]=stages[sectionKey]||[sectionKey,''];
 const config=project.creator.simulationConfig||{branches:3,rounds:4,goal:'让事件更自然，人物动机更充分',variable:'探索相遇、冲突或过渡事件，保持已锁定骨架与结局'};
 const update=patch=>setState(s=>updateCreatorSection(s,'script',project.id,sectionKey,patch));
 const configure=patch=>setState(s=>updateCreatorProject(s,'script',project.id,{simulationConfig:{...config,...patch}}));
 const instruction=sectionKey==='simulation'?`进行大世界模拟，最多${config.branches}个候选分支，每个最多${config.rounds}轮交互。优化目标：${config.goal}。可变过程：${config.variable}。项目已采用世界、人设和锁定骨架为固定条件。给出每个分支的编号事件链、动机、成立条件、约束检查、优缺点与后续影响；不得自动采用。`:'';
 const saveSkill=()=>{if(!section.output?.trim())return;setState(s=>addSkill(s,{name:`${project.name}·对标创作经验`,description:'从本项目对标材料提炼，使用前核对适用边界。',content:`# ${project.name} 创作经验\n\n使用这些方法前先检查当前作品的设定与适用条件；参考例子不能当作当前故事事实。\n\n${section.output}`,files:project.creator.references.map((r,i)=>({path:`references/source-${i+1}.md`,content:`# ${r.name||r.fileName}\n\n${r.content}`})),sourceName:project.name}));setNotice('已将当前经验保存到 Skill 库，可在那里继续检查和修改。');};
 const addItem=()=>{const existing=section.output||'',count=(existing.match(/^\d+[.、)]/gm)||[]).length;update({output:`${existing}${existing?'\n\n':''}${count+1}. ${sectionKey==='characters'?'待编辑人物：身份、目标、关系、起点、轨迹、结局':'待编辑事件：行动、结果、人物、前置事件、所属大事件'}`,accepted:false});};
 return <div className="creator-framework"><section className="creator-framework-results"><div className="creator-section-head"><div><h2>{title}</h2><p className="creator-muted">{help}</p></div><button className="secondary" disabled={agent.activity[`script:${project.id}`]?.running} onClick={()=>onStageRun(sectionKey,instruction)}> {sectionKey==='simulation'?'开始推演':'整理当前阶段'}</button></div>
 {sectionKey==='experience'&&<section className="creator-references"><header><strong>核心对标 · {project.creator.references.length}/3</strong><button className="secondary" disabled={project.creator.references.length>=3} onClick={()=>setReferenceDialog(true)}><Plus size={15}/>添加对标</button></header>{project.creator.references.map((ref,i)=><article key={ref.id||i}><BookOpen size={17}/><div><strong>{ref.name||ref.fileName}</strong><span>{ref.content.length}字 · 原始材料保留</span></div><button className="ghost" aria-label={`移除对标${i+1}`} onClick={()=>{if(window.confirm('移除此参考材料？已有提炼结果会保留，后续需核对来源。'))setState(s=>updateCreatorProject(s,'script',project.id,{references:project.creator.references.filter((_,n)=>n!==i)}));}}><Trash2 size={15}/></button></article>)}{!project.creator.references.length&&<p className="creator-muted">可以选择果子库剧本或上传 TXT、DOCX，也可以继续无对标创作。</p>}</section>}
 {sectionKey==='simulation'&&<div className="creator-simulation-controls"><label>候选分支<select value={config.branches} onChange={e=>configure({branches:Number(e.target.value)})}>{[1,2,3,4].map(n=><option key={n} value={n}>{n}个</option>)}</select></label><label>每分支交互轮次<select value={config.rounds} onChange={e=>configure({rounds:Number(e.target.value)})}>{[2,4,6,8].map(n=><option key={n} value={n}>{n}轮</option>)}</select></label><label>优化目标<input value={config.goal} onChange={e=>configure({goal:e.target.value})}/></label><label>允许改变的过程<textarea value={config.variable} onChange={e=>configure({variable:e.target.value})}/></label><p className="creator-muted">已锁定的设定与骨架保持。推演使用当前资料快照，未选分支不会进入细纲。</p></div>}
 <label className="creator-stage-input"><span>{sectionKey==='inspiration'?'我的灵感输入':'本阶段补充想法／要求'}</span><textarea aria-label="本阶段输入" readOnly={!!section.locked} value={section.input||''} placeholder="直接写想法，或在右侧与 Agent 商量…" onChange={e=>update({input:e.target.value})}/></label>
 <section className="creator-stage-output"><header><strong>当前成果</strong><div className="creator-inline-actions">{['events','characters','outline'].includes(sectionKey)&&<button className="secondary" disabled={!!section.locked} onClick={addItem}><Plus size={14}/>添加{sectionKey==='characters'?'人物':'事件'}</button>}<button className="secondary" disabled={!!section.locked||!section.output?.trim()} onClick={()=>update({accepted:section.stale?true:!section.accepted,stale:false})}><Check size={14}/>{section.stale?'复核并采用':section.accepted?'已设为当前采用':'设为当前采用'}</button>{['inspiration','skeleton'].includes(sectionKey)&&<button className="secondary" disabled={!section.locked&&!section.output?.trim()} onClick={()=>update(section.locked?{locked:false}:{locked:true,accepted:true})}>{section.locked?<Lock size={14}/>:<Unlock size={14}/>} {section.locked?'已锁定':section.accepted?'锁定':'采用并锁定'}</button>}</div></header>
 {section.locked&&<p className="creator-warning">此阶段已锁定。解除锁定后可编辑；Agent 候选仍可讨论。</p>}
 <textarea aria-label="当前阶段成果" value={section.output||''} readOnly={!!section.locked} placeholder="整理后采用的成果在这里；也可以直接编辑自己的版本…" onChange={e=>update({output:e.target.value,accepted:false})}/><small>{section.accepted?'当前采用，供后续阶段读取':'编辑草稿；点击设为当前采用后成为后续依据'}{section.stale?' · 上游有改动，需要复核':''}</small></section>
 {['events','outline','skeleton','characters','timeline','detail','episodeOutline'].includes(sectionKey)&&<StoryLedger project={project} setState={setState} onError={onError} stage={sectionKey} sectionText={section.output||''}/>}
 {sectionKey==='experience'&&notice&&<p role="status" className="creator-notice">{notice}</p>}
 {sectionKey==='experience'&&<button className="secondary" disabled={!section.output?.trim()} onClick={saveSkill}><Sparkles size={15}/>保存为项目经验 Skill</button>}
 <button className="ghost" onClick={()=>setRecordsOpen(!recordsOpen)}>{recordsOpen?'收起':'展开'}本阶段全部沉淀</button>{recordsOpen&&<CandidateList records={project.creator.records.filter(r=>r.target?.section===sectionKey&&r.output).slice().reverse()} project={project} kind="script" setState={setState} onError={onError}/>}
 </section><AgentPanel key={`${project.id}:${sectionKey}`} project={project} kind="script" state={state} setState={setState} agent={agent} target={{section:sectionKey,side:'output'}} onError={onError} chat defaultInstruction={instruction}/>
 {referenceDialog&&<SourceDialog state={state} api={api} title="添加核心对标材料" onError={onError} onClose={()=>setReferenceDialog(false)} onChoose={doc=>{try{setState(s=>addCreatorReference(s,project.id,doc));setReferenceDialog(false);}catch(e){onError(e.message);}}}/>}
 </div>;
}
