import React,{useEffect,useRef,useState} from 'react';
import {ArrowLeft,Save,Download,Sparkles,History,Layers,FolderOpen,Check,BookOpen} from 'lucide-react';
import {normalizeFrameworkProject,frameworkState,frameworkEvents,applyFrameworkCommand} from '../../core/frameworkWorkflow.js';
import {creatorModelOptions} from '../../core/creatorAi.js';
import {CreatorDialog,ExportDialog} from './CreatorDialogs.jsx';
import {IdeasPane,SettingsPane} from './framework/IdeaSettingsPanes.jsx';
import {EventsPane,MainlinePane,CharactersPane} from './framework/EventPanes.jsx';
import {ReferencesPane,SimulationPane} from './framework/ReferencePanes.jsx';
import {PlansPane,ScriptPane,HistoryPane} from './framework/PlanScriptPanes.jsx';
import {FrameworkAgent,FrameworkRecordDialog,taskLabels} from './framework/FrameworkAgent.jsx';
import {Heading,Panel,Empty,Tag} from './framework/FrameworkParts.jsx';
import './framework/framework.css';

const stages=[['ideas','灵感'],['settings','设定'],['events','事件骨架'],['mainline','主线与衔接'],['characters','人物与人物线'],['plans','集纲版本'],['script','剧本正文']];
export function FrameworkCreationWorkspace({project:rawProject,state,setState,getState,api,agent,onBack,onSave,saveStatus}){
 const project=normalizeFrameworkProject(rawProject),f=frameworkState(project),rows=frameworkEvents(project);
 const [stage,setStage]=useState(f.groups.length?'events':'ideas'),[collapsed,setCollapsed]=useState(false),[agentOpen,setAgentOpen]=useState(false),[error,setError]=useState(''),[recordId,setRecordId]=useState(''),[exportMode,setExportMode]=useState(''),[overview,setOverview]=useState(false);
 const options=creatorModelOptions(state.apiProfiles||[],state.activeApiId),saved=project.creator.runConfig?.framework||{};
 const [selection,setSelectionLocal]=useState(saved.selection||options[0]?.selectionId||''),[skillId,setSkillIdLocal]=useState(saved.skillId||''),[scope,setScopeLocal]=useState(saved.scope||'project');
 const latest=useRef(state);latest.current=state;
 const currentState=()=>getState?.()||latest.current;
 const currentProject=()=>currentState().scriptProjects?.find(p=>p.id===project.id);
 useEffect(()=>{if(!options.some(o=>o.selectionId===selection))setSelectionLocal(options[0]?.selectionId||'');},[selection,options.map(o=>o.selectionId).join('|')]);
 const command=c=>{setError('');try{const current=currentProject();if(!current)throw new Error('项目已移除，请返回项目列表。');applyFrameworkCommand(current,c);setState(previous=>{try{return {...previous,scriptProjects:previous.scriptProjects.map(p=>p.id===project.id?applyFrameworkCommand(p,c):p)};}catch(e){setError(e.message);return previous;}});return true;}catch(e){setError(e.message);return false;}};
 const config=patch=>{const existing=currentProject()?.creator?.runConfig||{};command({type:'creator.config',patch:{runConfig:{...existing,framework:{selection,skillId,scope,...patch}}}});};
 const setSelection=value=>{setSelectionLocal(value);config({selection:value});},setSkillId=value=>{setSkillIdLocal(value);config({skillId:value});},setScope=value=>{setScopeLocal(value);config({scope:value});};
 const run=async(target,instruction='')=>{setError('');const profile=options.find(o=>o.selectionId===selection)||options[0];try{if(!profile){setAgentOpen(true);throw new Error('请先在 API 接口配置可用模型。');}const id=await agent.run({kind:'script',projectId:project.id,target,instruction:instruction||taskLabels[target.task]||'围绕当前作品协同创作',profile,skillId,scope,chat:target.task==='frameworkChat'});if(target.task!=='frameworkEpisode'){setAgentOpen(true);if(target.task!=='frameworkChat')setRecordId(id);}return id;}catch(e){setError(e.message);setAgentOpen(true);return null;}};
 const activity=Object.entries(agent.activity||{}).find(([key,a])=>key.startsWith(`script:${project.id}`)&&a.running)?.[1]||{},busy=!!activity.running;
 const records=project.creator.records||[],review=id=>{setRecordId(id);},common={project,state,setState,getState:currentState,api,agent,f,rows,command,run,busy,onError:setError,navigate:setStage,records,review};
 const record=records.find(r=>r.id===recordId);
 return <div className={`fw-workspace ${collapsed?'fw-nav-collapsed':''}`}>
 <nav className="fw-directory" aria-label="原创框架式创作目录"><button className="ghost fw-back" onClick={onBack}><ArrowLeft size={15}/>全部原创项目</button><div className="fw-project-title"><strong>{project.name}</strong><small>原创 · 框架式创作</small></div><button className="fw-nav-button" onClick={()=>setOverview(true)}><BookOpen size={15}/>总故事预览</button><span className="fw-nav-label">创作工作区</span>{stages.map(([key,label],i)=><button key={key} className={`fw-nav-button ${stage===key?'active':''}`} onClick={()=>setStage(key)}><span className="fw-step-number">{i+1}</span>{label}{(key==='settings'&&f.settings.confirmed&&!f.settings.pending.length||key==='mainline'&&f.mainline.confirmed)&&<Check size={12}/>}</button>)}<span className="fw-nav-label">辅助创作</span>{[['references','对标组件库',Layers],['simulation','大世界模拟',Sparkles],['history','项目版本',History]].map(([key,label,Icon])=><button key={key} className={`fw-nav-button ${stage===key?'active':''}`} onClick={()=>setStage(key)}><Icon size={15}/>{label}</button>)}<div className="fw-progress"><strong>故事组成</strong><p>{f.groups.length} 个大事件 · {rows.length} 个小事件</p><p>{f.settings.confirmed?'设定已确认':'设定待确认'} · {f.mainline.links.filter(l=>l.stale||!l.confirmed).length} 处衔接待复核</p><small>调整事件顺序，已有引用会保留。</small></div></nav>
 <main className="fw-main"><header className="fw-topbar"><button className="ghost" aria-label="折叠项目目录" onClick={()=>setCollapsed(!collapsed)}><FolderOpen size={17}/></button><div className="fw-breadcrumb"><span>原创</span><span>›</span><strong>框架式创作</strong></div><span className="fw-save-status">{saveStatus?.error?'保存失败，请重试':saveStatus?.saving?'正在保存…':saveStatus?.saved?'已保存到本地':'自动保存中'}</span><button className="secondary" onClick={()=>onSave?.()}><Save size={15}/>保存</button><button className="secondary" onClick={()=>setAgentOpen(!agentOpen)}><Sparkles size={15}/>写作 Agent{records.some(r=>r.status==='pending'&&!['frameworkChat','frameworkCheck'].includes(r.target?.task))&&<Tag>{records.filter(r=>r.status==='pending'&&!['frameworkChat','frameworkCheck'].includes(r.target?.task)).length}</Tag>}</button><button className="secondary" onClick={()=>setExportMode('export')}><Download size={15}/>导出</button><button className="primary" onClick={()=>setExportMode('archive')}>收录剧本库</button></header>
 {error&&<div className="fw-error" role="alert"><span>{error}</span><button className="ghost" onClick={()=>setError('')}>关闭</button></div>}{busy&&<div className="fw-running" role="status"><span>{activity.label||'Agent 正在生成候选…'}</span><button className="secondary" onClick={()=>agent.cancel('script',project.id)}>停止</button></div>}
 <div className="fw-content"><div className="fw-stepper" aria-label="创作步骤">{stages.filter(([key])=>key!=='characters').map(([key,label])=><button key={key} className={stage===key?'current':key==='settings'&&f.settings.confirmed?'past':''} onClick={()=>setStage(key)}>{label}</button>)}</div>
 {stage==='ideas'?<IdeasPane {...common}/>:stage==='settings'?<SettingsPane {...common}/>:stage==='events'?<EventsPane {...common}/>:stage==='mainline'?<MainlinePane {...common}/>:stage==='characters'?<CharactersPane {...common}/>:stage==='plans'?<PlansPane {...common}/>:stage==='script'?<ScriptPane {...common}/>:stage==='references'?<ReferencesPane {...common}/>:stage==='simulation'?<SimulationPane {...common}/>:<HistoryPane {...common}/>}<button className="fw-coach" onClick={()=>setAgentOpen(true)}><Sparkles size={16}/><span>与 Agent 沟通：补充行动、调整事件、核对衔接或推理下一步</span><span>打开沟通创作</span></button>
 </div></main>
 {agentOpen&&<FrameworkAgent {...common} options={options} selection={options.find(o=>o.selectionId===selection)?.selectionId||options[0]?.selectionId||''} setSelection={setSelection} skillId={skillId} setSkillId={setSkillId} scope={scope} setScope={setScope} activity={activity} stage={stage} onClose={()=>setAgentOpen(false)}/>}
 {record&&<FrameworkRecordDialog key={record.id} {...common} record={record} onClose={()=>setRecordId('')}/>}
 {exportMode&&<ExportDialog project={project} kind="script" api={api} setState={setState} archive={exportMode==='archive'} onClose={()=>setExportMode('')}/>}
 {overview&&<CreatorDialog title="总故事预览" onClose={()=>setOverview(false)} className="fw-record-dialog"><Heading title={project.name} help="汇总当前事件骨架与故事稿，未确认内容仍为草稿。"/><Panel title="本剧设定">{f.settings.items.map(s=><p key={s.id}><strong>{s.category}：</strong>{s.text}</p>)}</Panel>{f.groups.map(g=><Panel key={g.id} title={g.title} extra={<Tag good={g.confirmed}>{g.confirmed?'已确认':'草稿'}</Tag>}><p>{g.goal}</p>{rows.filter(r=>r.group?.id===g.id).map(r=><article key={r.event.id}><h4>{r.code} · {r.event.title}</h4><pre className="fw-original">{r.event.story||r.event.summary}</pre></article>)}</Panel>)}{!f.groups.length&&<Empty>尚未建立故事事件。</Empty>}<footer><button className="secondary" onClick={()=>setOverview(false)}>关闭</button></footer></CreatorDialog>}
 </div>;
}
