import { normalizeReadConcurrency } from '../../core/ipReading.js';
import { ipWorkStatus } from '../../core/ipTaskStatus.js';
import { formatIPScriptText } from '../../core/ipScenes.js';
import { countIPDisplayCharacters } from '../../core/ipTextStats.js';
import { IPSceneEditor } from './IPSceneEditor.jsx';
import { sourceRangeLabel,episodeSourceRanges } from '../../core/ipSourceRanges.js';
import React,{useState,useEffect,useLayoutEffect,useRef} from 'react';
import { ArrowLeft,Plus,FileText,BookOpen,Upload,Download,Save,History,Play,Square,Check,Trash2 } from 'lucide-react';
import { ProjectCardHub } from '../v06/ProjectCardHub.jsx';
import { createProjectGroup,renameProjectGroup,deleteProjectGroup,organizeProject,uid } from '../../core/projectStore.js';
import { creatorModelOptions } from '../../core/creatorAi.js';
import { prepareNovelProject,prepareCompletedProject,appendPreparedProject,projectNameFromFile } from '../../core/creatorDirectImport.js';
import { createIPProject,getIPProject,importIPNovel,applyIPPlan,mutateIP,updateIPMapping,ipOriginal,updateIPDraft,saveIPVersion,adoptIPVersion,deleteIPVersion,confirmIPEpisode,confirmAllIPEpisodes,assertIPConfirmationReady,ipConfirmationSummary,ipBodyCount,updateIPMeta,ipFingerprint,ipSourceFor,restoreRetiredIPEpisode,ipEditionRecords,applyIPEdition,deleteIPEdition } from '../../core/ipWorkspace.js';
import { CreatorDialog,ExportDialog } from './CreatorDialogs.jsx';
import { IPTaskHistory } from './IPTaskHistory.jsx';
import { countIPReadingCharacters } from './ipReadingProgress.js';

const usesSequentialWebReading=profile=>['geminiWeb','chatgptWeb','doubaoWork'].includes(profile?.provider);

export function IPWorkspace({state,setState,api,agent,selectedId,onSelect,onBack,onSwitchFruit,onSave,saveStatus}){
 const project=getIPProject(state,selectedId);
 const [active,setActive]=useState('source'),[create,setCreate]=useState(false),[name,setName]=useState(''),[duration,setDuration]=useState(60),[error,setError]=useState(''),[importDoc,setImportDoc]=useState(null),[exporting,setExporting]=useState(''),[mapping,setMapping]=useState(null),[planDraft,setPlanDraft]=useState(null),[planMeta,setPlanMeta]=useState(null),[history,setHistory]=useState(false),[docView,setDocView]=useState(null),[versionId,setVersionId]=useState(''),[instruction,setInstruction]=useState(''),[notice,setNotice]=useState('');
 const [hubDoc,setHubDoc]=useState(null),[hubImporting,setHubImporting]=useState(false),[startJob,setStartJob]=useState(null);
 const startedJobs=useRef(new Set());
 const toolbarRef=useRef(null),[toolbarHeight,setToolbarHeight]=useState(64);
 useLayoutEffect(()=>{
  const toolbar=toolbarRef.current;if(!toolbar)return;
  const measure=()=>setToolbarHeight(Math.ceil(toolbar.getBoundingClientRect().height));
  measure();
  const observer=typeof ResizeObserver==='function'?new ResizeObserver(measure):null;
  observer?.observe(toolbar);window.addEventListener('resize',measure);
  return ()=>{observer?.disconnect();window.removeEventListener('resize',measure);};
 },[project?.id]);
 useEffect(()=>{setActive(project?.creator.ip.plan||project?.creator.ip.completedImport?'master':'source');setError('');setNotice('');setVersionId('');},[project?.id]);
 useEffect(()=>{if(!startJob||project?.id!==startJob.id||startedJobs.current.has(startJob.id))return;startedJobs.current.add(startJob.id);setStartJob(null);setActive('source');agent.runAdaptation({projectId:startJob.id,profile:startJob.profile}).then(result=>{if(result.type==='firstDraft')setActive('master');}).catch(e=>setError(e.message));},[project?.id,startJob]);
 useEffect(()=>{setVersionId('');setInstruction('');},[active]);
 const safely=fn=>{try{fn();setError('');}catch(e){setError(e.message);}};
 const ip=project?.creator.ip,source=ip?.source,episode=project?.episodes.find(e=>e.id===active),version=episode?.ipVersions?.find(v=>v.id===versionId);
 const options=creatorModelOptions(state.apiProfiles,state.activeApiId),profile=options.find(o=>o.selectionId===ip?.selection)||options[0],activity=agent.activity[project?.id]||{},busy=!!activity.running,workStatus=ipWorkStatus(project,activity);
 const webReading=usesSequentialWebReading(profile),hubWebReading=usesSequentialWebReading(options.find(o=>o.selectionId===hubDoc?.selection)||options[0]);
 const confirmation=ipConfirmationSummary(project);
 const configure=patch=>safely(()=>setState(s=>updateIPMeta(s,project.id,patch)));
 const run=async(task,episodeId=episode?.id)=>{setError('');try{await agent.run({projectId:project.id,task,episodeId,profile,instruction});setInstruction('');}catch(e){setError(e.message);}};
 const startFlow=async({plan,continueDraft=false}={})=>{setError('');setNotice('');try{if(plan){if(planMeta?.sourceId&&planMeta.sourceId!==source?.id){const original=ip.sources.find(s=>s.id===planMeta.sourceId);if(!original)throw new Error('该规划的原文未找到');configure({source:original,reading:[]});}if(planMeta?.duration)configure({duration:planMeta.duration});if(planMeta?.requirements!==undefined)configure({requirements:planMeta.requirements});setPlanDraft(null);setPlanMeta(null);setActive('master');}const result=await agent.runAdaptation({projectId:project.id,profile,plan,continueDraft});if(result.type==='planCandidate')setNotice('新版规划已生成，采用后自动生成设定与全部正文。');else {setActive('master');setNotice(result.output);} }catch(e){setError(e.message);}};
 const runRemaining=()=>startFlow({continueDraft:true});
 const confirmAll=()=>safely(()=>{
  assertIPConfirmationReady(project);setState(s=>confirmAllIPEpisodes(s,project.id));
  setNotice(`已确认 ${confirmation.episodes} 集正文${confirmation.settings?'及设定与小传':''}。${confirmation.emptyEpisodes?`跳过 ${confirmation.emptyEpisodes} 个空集。`:''}${confirmation.emptySettings?'设定与小传尚未生成，未确认。':''}`);
 });
 const uploadHub=async type=>{setError('');setHubImporting(true);try{const file=await api.importFullScript();if(file){if(!file.content?.trim())throw new Error('文档没有可读取的正文');setHubDoc({...file,type,duration:60,readConcurrency:3,selection:options[0]?.selectionId||''});}}catch(e){setError(e.message);}finally{setHubImporting(false);}};
 const confirmHubUpload=()=>safely(()=>{const selected=options.find(o=>o.selectionId===hubDoc.selection)||options[0];if(hubDoc.type==='novel'&&!selected)throw new Error('先在 API 接口中添加可用模型');const prepared=hubDoc.type==='novel'?prepareNovelProject(hubDoc,{duration:hubDoc.duration,selection:selected.selectionId,readConcurrency:hubDoc.readConcurrency}):prepareCompletedProject(hubDoc,{kind:'ip'});setState(s=>appendPreparedProject(s,prepared));if(hubDoc.type==='novel')setStartJob({id:prepared.id,profile:selected});setHubDoc(null);onSelect(prepared.id);});
 const upload=async()=>{try{const file=await api.importFullScript();if(file)setImportDoc({name:file.fileName,content:file.content,filePath:file.filePath,encoding:file.encoding});}catch(e){setError(e.message);}};
 const modelSelect=<label className="ip-model-select">接口与模型<select aria-label="IP 创作模型" value={profile?.selectionId||''} disabled={busy} onChange={e=>configure({selection:e.target.value})}>{!options.length&&<option value="">请在 API 接口中添加模型</option>}{options.map(o=><option key={o.selectionId} value={o.selectionId}>{o.isDefault?'默认 · ':''}{o.name} · {o.model}</option>)}</select></label>;
 const pending=ip?.planCandidates||[],editions=ipEditionRecords(project);
 const openPlan=(plan,meta={})=>{setPlanDraft(structuredClone(plan));setPlanMeta(meta);};
 const restoreEdition=id=>safely(()=>{setState(s=>applyIPEdition(s,project.id,id));setActive('master');setNotice('已恢复该版本的规划、设定与全部正文。');});
 const audit=version||(episode?.ipVersions||[]).slice().reverse().find(v=>v.content===episode?.scriptText);
 const linkedSource=episode?ipSourceFor(project,version?.sourceId||episode.sourceId||source?.id):source;
 const original=episode?(ipOriginal(project,episode,version)||(!source&&ip.completedImport?episode.rawText||'':'')):'';
 if(!project)return <div className="creator-hub"><div className="creator-channel-bar"><div className="seg"><button onClick={onSwitchFruit}>果子库</button><button className="active">IP 库</button></div><span className="creator-muted">成品库 · 从小说原文到完整剧本</span></div>
 <ProjectCardHub key="ip" kind="ip" title="IP 库" projects={state.fruitProjects.filter(p=>p.creator?.mode==='ip')} groups={state.fruitGroups} onUpload={()=>{if(!hubImporting)uploadHub('novel');}} onUploadCompleted={()=>{if(!hubImporting)uploadHub('completed');}} onCreate={()=>{setName('');setDuration(60);setCreate(true);}} onOpen={onSelect} onDelete={id=>setState(s=>({...s,fruitProjects:s.fruitProjects.filter(p=>p.id!==id)}))} onRename={(id,name)=>setState(s=>organizeProject(s,'fruit',id,{name}))} onMoveToGroup={(id,groupId)=>setState(s=>organizeProject(s,'fruit',id,{groupId}))} onCreateGroup={name=>setState(s=>createProjectGroup(s,'fruit',name))} onRenameGroup={(id,name)=>setState(s=>renameProjectGroup(s,'fruit',id,name))} onDeleteGroup={id=>setState(s=>deleteProjectGroup(s,'fruit',id))}/>
 {create&&<CreatorDialog title="新建 IP 改编项目" onClose={()=>setCreate(false)}><form onSubmit={e=>{e.preventDefault();safely(()=>{const prepared=createIPProject({fruitProjects:[]},{name,duration}).fruitProjects[0];setState(s=>appendPreparedProject(s,prepared));onSelect(prepared.id);setCreate(false);});}}><label>项目名称<input autoFocus aria-label="IP 项目名称" value={name} onChange={e=>setName(e.target.value)}/></label><label>目标时长<select aria-label="IP 目标时长" value={duration} onChange={e=>setDuration(Number(e.target.value))}><option value={60}>60 分钟 · 至少 50 集 · 正文目标 4 万字</option><option value={120}>120 分钟 · 至少 80 集 · 正文目标 7 万字</option></select></label><footer><button type="button" className="secondary" onClick={()=>setCreate(false)}>取消</button><button className="primary" disabled={!name.trim()}>创建项目</button></footer></form></CreatorDialog>}
 {hubDoc&&<CreatorDialog title={hubDoc.type==='novel'?'上传小说并开始改编':'导入完成剧本'} onClose={()=>setHubDoc(null)} className="creator-upload-dialog"><div className="creator-upload-summary"><BookOpen size={24}/><div><strong>{projectNameFromFile(hubDoc.fileName)}</strong><p>{hubDoc.fileName} · {hubDoc.content.length.toLocaleString()} 字符{hubDoc.encoding?` · ${hubDoc.encoding}`:''}</p></div></div>{hubDoc.type==='novel'?<><label>目标时长<select aria-label="上传小说目标时长" value={hubDoc.duration} onChange={e=>setHubDoc({...hubDoc,duration:Number(e.target.value)})}><option value={60}>60 分钟 · 至少 50 集 · 正文目标 4 万字</option><option value={120}>120 分钟 · 至少 80 集 · 正文目标 7 万字</option></select></label><label>接口与模型<select aria-label="上传小说模型" value={hubDoc.selection} onChange={e=>setHubDoc({...hubDoc,selection:e.target.value})}>{!options.length&&<option value="">请先在 API 接口中添加模型</option>}{options.map(o=><option key={o.selectionId} value={o.selectionId}>{o.isDefault?'默认 · ':''}{o.name} · {o.model}</option>)}</select></label><label>通读并发<select aria-label="上传小说通读并发" value={hubWebReading?1:hubDoc.readConcurrency||3} disabled={hubWebReading} title={hubWebReading?"网页账号按顺序读取":"设置素材阅读并发"} onChange={e=>setHubDoc({...hubDoc,readConcurrency:Number(e.target.value)})}>{[1,2,3,4,5,6,7,8].map(n=><option key={n} value={n}>{n} 路</option>)}</select></label><p className="creator-muted">用文件名自动创建项目，开始通读与分集规划；生成的规划由你核对采用。</p></>:<p className="creator-muted">自动识别设定与分集，保留导入原文。完成稿可直接阅读、导出与收录，无需先上传小说。</p>}{error&&<p role="alert" className="creator-error">{error}</p>}<footer><button className="secondary" onClick={()=>setHubDoc(null)}>取消</button><button className="primary" disabled={hubDoc.type==='novel'&&!options.length} onClick={confirmHubUpload}>{hubDoc.type==='novel'?'开始改编':'确认导入剧本'}</button></footer></CreatorDialog>}
 {hubImporting&&<p role="status" className="creator-muted">正在读取文档…</p>}{error&&!hubDoc&&<p role="alert" className="creator-error">{error}</p>}</div>;
 return <div className="creator-shell ip-shell"><nav className="creator-directory"><button className="creator-back" onClick={onBack}><ArrowLeft size={18}/>全部 IP 项目</button><strong>{project.name}</strong><small>{ip.completedImport?'IP 库 · 已完成剧本':`IP 改编 · ${ip.duration} 分钟`}</small><div className="ip-control-nav"><button className={active==='source'?'active':''} aria-current={active==='source'?'page':undefined} onClick={()=>setActive('source')}><BookOpen size={17}/><span>分集规划<small>原著 · 模型 · 时长</small></span></button><button className={active==='master'?'active':''} aria-current={active==='master'?'page':undefined} onClick={()=>setActive('master')}><FileText size={17}/><span>总剧本编辑<small>设定 · 小传 · 正文</small></span></button></div><div className="ip-manuscript-nav"><span className="creator-nav-label">分集</span>{project.episodes.map((e,i)=><button key={e.id} className={`ip-directory-node ${active===e.id?'active':''}`} onClick={()=>setActive(e.id)}><span className="creator-episode-number">{e.type==='settings'?'序':String(project.episodes.filter(n=>n.type==='episode').findIndex(n=>n.id===e.id)+1).padStart(2,'0')}</span><span>{e.title}<small>{e.stale?'前文或来源变化，待复核':e.finalConfirmed?'已确认正文':e.scriptText?'编辑中':e.type==='settings'?'待提取设定':'待转写'} · {e.ipVersions?.length||0} 版</small></span></button>)}<button className="creator-add-node" disabled={busy} onClick={()=>safely(()=>{const id=uid();setState(s=>mutateIP(s,project.id,p=>({...p,episodes:[...p.episodes,{id,sourceId:p.creator.ip.source?.id,type:'episode',title:`第${p.episodes.filter(e=>e.type==='episode').length+1}集`,rawText:'',scriptText:'',chapterIds:[],ipVersions:[]}]})));setActive(id);})}><Plus size={16}/>添加集数</button></div></nav>
 <main className="creator-main" style={{'--ip-toolbar-height':`${toolbarHeight}px`}}><header className="creator-toolbar" ref={toolbarRef}><div><strong>{project.name}</strong><small>IP 库 · {ip.completedImport?'已完成剧本':'小说改编'}</small></div><span className="creator-save-status">{saveStatus?.error?'保存失败，请重试':saveStatus?.saving?'正在保存…':'自动保存到本地'}</span><button className="secondary" onClick={()=>setHistory(true)}><History size={17}/>项目记录</button><button className="secondary" onClick={onSave}><Save size={17}/>保存</button><button className="secondary" onClick={()=>setExporting('export')}><Download size={17}/>导出</button><button className="primary" onClick={()=>setExporting('archive')}>收录剧本库</button></header>
 {error&&<div role="alert" className="creator-error-bar"><span>{error}</span><button className="ghost" onClick={()=>setError('')}>关闭</button></div>}
 {notice&&<div className="creator-notice" role="status">{notice}</div>}
 {busy&&<div className="ip-progress" role="status"><span>{activity.label}</span><button className="secondary" onClick={()=>agent.cancel(project.id)}><Square size={15}/>停止任务</button></div>}
 {active==='source'?<section className="creator-source-page"><div className="creator-section-head"><div><h2>分集规划</h2><p className="creator-muted">通读原著后同步整理设定与小传，选定主线和真实终点，再按故事节点规划分集。</p></div><div className="creator-inline-actions"><button className="secondary" disabled={busy} onClick={upload}><Upload size={17}/>上传小说</button><button className="secondary" disabled={busy} onClick={()=>setImportDoc({name:'粘贴的小说',content:''})}>粘贴原文</button></div></div>
 <div className="ip-project-config ip-control-config">{modelSelect}<label>目标时长<select aria-label="改编时长" disabled={busy} value={ip.duration} onChange={e=>configure({duration:Number(e.target.value)})}><option value={60}>60 分钟 · 至少 50 集 · 正文目标 4 万字</option><option value={120}>120 分钟 · 至少 80 集 · 正文目标 7 万字</option></select></label><label>通读并发<select aria-label="小说通读并发" value={webReading?1:normalizeReadConcurrency(ip.readConcurrency)} disabled={busy||webReading} title={webReading?"网页账号按顺序读取":"设置素材阅读并发"} onChange={e=>configure({readConcurrency:Number(e.target.value)})}>{[1,2,3,4,5,6,7,8].map(n=><option key={n} value={n}>{n} 路{n===1?" · 顺序读取":""}</option>)}</select></label></div>
 {source?<><div className="ip-source-card"><BookOpen size={24}/><div><strong>{source.name}</strong><p>{source.chapters.length} 个原文段落／章节 · {source.content.length.toLocaleString()} 字符 · 已读取 {countIPReadingCharacters(ip.reading,source).toLocaleString()} 字符</p></div><button className="secondary" onClick={()=>setDocView({name:source.name,content:source.content})}>查看完整原文</button></div><label className="creator-stage-input"><span>改编要求（可选）</span><textarea aria-label="IP 规划要求" disabled={busy} value={ip.requirements||''} onChange={e=>configure({requirements:e.target.value})} placeholder="希望保留的主线、角色、原著场面或阶段终点…"/></label><div className="creator-inline-actions"><button className="primary" disabled={busy||!profile} onClick={()=>startFlow()}><Play size={17}/>{ip.plan||editions.length?'生成新版改编规划':'一键生成完整首版'}</button><span className="creator-muted">首版自动生成规划、设定与全部正文；新版规划采用后自动重跑，历史保留。</span></div>
 {ip.plan&&<div className="ip-plan-card"><h3>当前采用的改编规划</h3><p>{ip.plan.mainline}</p><p><strong>原著终点：</strong>{ip.plan.ending}</p><button className="secondary" disabled={busy} onClick={()=>openPlan(ip.plan,{duration:ip.duration,sourceId:source.id})}>查看／调整分集规划</button></div>}
 {editions.slice().reverse().map(v=><div className="ip-plan-card" key={v.id}><header><strong>{v.kind==='working-draft'?'工作稿':'改编版本'} {v.number} · {v.duration} 分钟 · {v.episodes.filter(e=>e.type==='episode').length} 集{v.id===ip.activeEditionId||v.id==='legacy-current'?' · 当前采用':''}</strong><small>{new Date(v.createdAt).toLocaleString()}</small></header><p>{v.plan?.mainline||'尚未采用分集规划，保留切换前的编辑内容。'}</p><p>{v.plan?.ending}</p><p className="creator-muted">已生成正文 {v.episodes.filter(e=>e.type==='episode'&&e.scriptText?.trim()).length} 集{v.requirements?` · 改编要求：${v.requirements}`:''}</p><button className="secondary" disabled={busy} onClick={()=>restoreEdition(v.id)}>{v.kind==='working-draft'?'恢复工作稿':'应用版本'} {v.number}</button><button className="ghost danger" disabled={busy} aria-label={`删除${v.kind==='working-draft'?'工作稿':'改编版本'} ${v.number}`} onClick={()=>{if(window.confirm('删除这条整剧版本记录？当前正在编辑的正文会保留，其他版本不受影响。删除后不能再通过这条记录恢复。'))safely(()=>setState(s=>deleteIPEdition(s,project.id,v.id)));}}><Trash2 size={14}/>删除版本</button></div>)}
 {pending.slice().reverse().map(p=><div className="ip-plan-card" key={p.id}><header><strong>规划候选 · {p.duration||ip.duration} 分钟 · {p.plan.episodes.length} 集</strong><small>{new Date(p.createdAt).toLocaleString()}</small></header><p>{p.plan.mainline}</p><p>{p.plan.ending}</p><button className="secondary" disabled={busy} onClick={()=>openPlan(p.plan,{duration:p.duration||ip.duration,requirements:p.requirements,sourceId:p.sourceId})}>核对分集与原文范围</button><button className="ghost danger" disabled={busy} onClick={()=>{if(window.confirm('删除这条规划候选？当前已采用规划和正文会保留。'))setState(s=>mutateIP(s,project.id,project=>({...project,creator:{...project.creator,ip:{...project.creator.ip,planCandidates:project.creator.ip.planCandidates.filter(item=>item.id!==p.id)}}})));}}><Trash2 size={14}/>删除候选</button></div>)}</>:<div className="ip-welcome"><BookOpen size={36}/><h3>先放入一本小说</h3><p>支持 TXT、Word（DOCX）和直接粘贴。导入后识别章节，分集规划会关联原文故事片段。</p><button className="primary" onClick={upload}>上传小说</button></div>}
 </section>:active==='master'?<section className="creator-master"><div className="ip-master-heading"><div className="creator-section-head"><div><h2>总剧本编辑</h2><p className="creator-muted">设定与各集正文使用同一份内容，修改后分集同步。小说、规划和对照记录不混入成稿。</p></div><div className="ip-master-controls"><div className="ip-master-buttons"><button className="secondary ip-confirm-all" disabled={busy||!confirmation.pending} onClick={confirmAll}><Check size={17}/>一键确认全部正文</button>{busy?<button className="secondary" onClick={()=>agent.cancel(project.id)}><Square size={17}/>停止任务</button>:<button className="primary" disabled={!ip.plan||(!profile&&!workStatus.needsSettingsReview)||!workStatus.pending} onClick={()=>workStatus.needsSettingsReview?setActive(project.episodes.find(e=>e.type==='settings')?.id):runRemaining()}><Play size={17}/>{workStatus.buttonLabel}</button>}</div><span className="ip-word-count">正文 {ipBodyCount(project).toLocaleString()}{!ip.completedImport&&` / ${ip.duration===120?'70,000':'40,000'}`} 字</span></div></div><p className={"ip-work-status "+workStatus.tone} role="status">{workStatus.message}</p></div>{project.episodes.map(e=><article className="creator-master-node" key={e.id}><header><h3>{e.type==='settings'?'序 · ':''}{e.title}</h3><button className="ghost" onClick={()=>setActive(e.id)}>打开原文对照</button></header><IPSceneEditor label={`IP 总稿 ${e.title}`} content={e.scriptText||''} settings={e.type==='settings'} onFocus={()=>setState(s=>saveIPVersion(s,project.id,e.id))} onChange={text=>setState(s=>updateIPDraft(s,project.id,e.id,text))} onBlur={()=>setState(s=>saveIPVersion(s,project.id,e.id))}/></article>)}<p className="creator-muted">正文统计为非空白字符，含场景标题与标点，不含设定和集标题。时长仍需试读核算。</p></section>:episode?<section className="creator-episode"><div className="creator-section-head"><div><h2>{episode.title}</h2><p className="creator-muted">{episode.type==='settings'?'从小说提取设定、梗概、标签和人物小传。':episode.outline||'先选择本集对应章节，再忠实转写。'}</p></div><div className="creator-inline-actions">{episode.type==='episode'&&<button className="secondary" disabled={busy} onClick={()=>setMapping({id:episode.id,chapterIds:[...(episode.chapterIds||[])],outline:episode.outline||'',sourceRanges:episodeSourceRanges(episode,source)})}>调整原文范围</button>}<button className="secondary" disabled={!episode.scriptText?.trim()||!!version} onClick={()=>safely(()=>setState(s=>confirmIPEpisode(s,project.id,episode.id)))}><Check size={16}/>{episode.finalConfirmed&&!episode.stale?'已确认':episode.type==='settings'?'确认设定与小传':'确认本集正文'}</button></div></div>
 {episode.stale&&<p className="creator-warning">前文、规划或原著已有变化。请核对本集的承接与来源，再确认正文。</p>}
 <div className="creator-pair ip-editor-pair"><div className="creator-text-pane"><header><strong>{episode.type==='settings'?'小说原文':'对应小说原文'}</strong><span className="creator-muted">{linkedSource?sourceRangeLabel(episode,linkedSource,version):'未关联小说原文'}</span></header><textarea readOnly aria-label="IP 对应小说原文" value={original} placeholder="选择原文章节后，完整内容会显示在这里"/><small>{countIPDisplayCharacters(original,{script:false}).toLocaleString()} 字符（含空白） · 原文独立保存</small></div><div className="creator-text-pane"><header><strong>{version?'历史／候选版本':'当前剧本正文'}</strong><select aria-label="IP 正文版本" value={versionId} onChange={e=>setVersionId(e.target.value)}><option value="">当前编辑稿</option>{(episode.ipVersions||[]).slice().reverse().map((v,i,all)=><option key={v.id} value={v.id}>第 {all.length-i} 版 · {v.label} · {new Date(v.createdAt).toLocaleTimeString()}</option>)}</select></header><IPSceneEditor label="IP 剧本正文" readOnly={!!version} content={version?.content??episode.scriptText??''} settings={episode.type==='settings'} onFocus={()=>{if(!version)setState(s=>saveIPVersion(s,project.id,episode.id));}} onChange={text=>setState(s=>updateIPDraft(s,project.id,episode.id,text))} onBlur={()=>{if(!version)setState(s=>saveIPVersion(s,project.id,episode.id));}} placeholder="转写后在这里展示，也可直接编辑…"/><small>{version?'版本内容只读；采用后可以继续编辑。':'编辑自动保存；每次 Agent 生成单独留版。'}</small></div></div>
 {version&&<div className="ip-version-actions"><span>{version.label} · {new Date(version.createdAt).toLocaleString()} {version.model||''}</span><button className="primary" disabled={busy} onClick={()=>safely(()=>{if(version.fingerprint&&version.fingerprint!==ipFingerprint(project,episode.id)&&!window.confirm('此版本依据的正文或来源已变化，仍采用为当前稿吗？'))return;setState(s=>adoptIPVersion(s,project.id,episode.id,version.id));setVersionId('');})}>采用此版并继续编辑</button><button className="ghost danger" onClick={()=>{if(window.confirm('永久删除这个历史版本？当前编辑稿和其他版本仍会保留。')){setState(s=>deleteIPVersion(s,project.id,episode.id,version.id));setVersionId('');}}}><Trash2 size={16}/>删除此版</button></div>}
 {(audit?.comparison||audit?.issues?.length>0)&&<details className="ip-comparison"><summary>本版原文对照与待核问题</summary><pre className="creator-doc-view">{audit.comparison}{audit.issues?.length?'\n\n待核问题：\n'+audit.issues.join('\n'):''}</pre></details>}
 <aside className="creator-agent ip-agent"><header><strong>Agent 协作 · {episode.type==='settings'?'设定与小传提取':'忠实转写与修订'}</strong></header>{modelSelect}<textarea className="creator-instruction" aria-label="IP 修改要求" value={instruction} onChange={e=>setInstruction(e.target.value)} placeholder="说明本集哪些地方需要调整。模型会读取对应小说、当前稿与此前最新正文，生成独立新版本。"/><div className="creator-run-row"><span className="creator-muted">{episode.type==='episode'?'新版本保留旧稿，核对后再采用。':'提取内容也可以手动修改并保存版本。'}</span><button className="primary" disabled={busy||!source||!profile} onClick={()=>run(episode.type==='settings'?'settings':'episode')}><Play size={17}/>{episode.type==='settings'?'提取设定与小传':episode.scriptText?'生成修改版本':'转写本集'}</button></div></aside>
 </section>:null}</main>
 {importDoc&&<CreatorDialog title="导入小说原文" onClose={()=>setImportDoc(null)} className="creator-source-preview"><label>小说名称<input value={importDoc.name||''} onChange={e=>setImportDoc({...importDoc,name:e.target.value})}/></label><p className="creator-muted">核对文字后导入{importDoc.encoding?`（${importDoc.encoding}）`:''}。原件与已保存版本保留，更新来源后需要重新核对分集。</p><textarea aria-label="小说导入预览" value={importDoc.content||''} onChange={e=>setImportDoc({...importDoc,content:e.target.value})}/><footer><button className="secondary" onClick={()=>setImportDoc(null)}>取消</button><button className="primary" disabled={!importDoc.content?.trim()} onClick={()=>safely(()=>{setState(s=>importIPNovel(s,project.id,importDoc));setImportDoc(null);})}>确认导入小说</button></footer></CreatorDialog>}
 {mapping&&<CreatorDialog title="本集对应原文" onClose={()=>setMapping(null)}><p className="creator-muted">章节用于回读上下文；按故事节点切分，允许从章内开始或结束。原文位置区间独立决定左侧展示范围。</p><div className="ip-chapter-picker">{source?.chapters.map(c=><label className="creator-check" key={c.id}><input type="checkbox" checked={mapping.chapterIds.includes(c.id)} onChange={e=>setMapping({...mapping,sourceRanges:undefined,chapterIds:e.target.checked?[...mapping.chapterIds,c.id]:mapping.chapterIds.filter(id=>id!==c.id)})}/>{c.title}</label>)}</div><div className="ip-range-inputs">{mapping.sourceRanges?.map((r,i)=><div key={i}><label>原文起点（字符位置）<input aria-label={`原文起点${i+1}`} type="number" min="0" value={r.start} onChange={ev=>setMapping({...mapping,sourceRanges:mapping.sourceRanges.map((v,j)=>j===i?{...v,start:Number(ev.target.value)}:v)})}/></label><label>原文终点（不含此位置）<input aria-label={`原文终点${i+1}`} type="number" min="1" value={r.end} onChange={ev=>setMapping({...mapping,sourceRanges:mapping.sourceRanges.map((v,j)=>j===i?{...v,end:Number(ev.target.value)}:v)})}/></label></div>)}</div><label>本集细纲<textarea value={mapping.outline} onChange={e=>setMapping({...mapping,outline:e.target.value})}/></label><footer><button className="primary" onClick={()=>safely(()=>{setState(s=>updateIPMapping(s,project.id,mapping.id,mapping.chapterIds,mapping.outline,mapping.sourceRanges));setMapping(null);})}>保存对应关系</button></footer></CreatorDialog>}
 {planDraft&&<CreatorDialog title="核对并采用分集规划" onClose={()=>setPlanDraft(null)} className="ip-plan-dialog" headerActions={<><button className="secondary" onClick={()=>setPlanDraft(null)}>暂不采用</button><button className="primary" disabled={busy} onClick={()=>startFlow({plan:planDraft})}>采用规划并生成全剧</button></>}><label>原著主线<textarea value={planDraft.mainline||''} onChange={e=>setPlanDraft({...planDraft,mainline:e.target.value})}/></label><label>真实终点与未决事项<textarea value={planDraft.ending||''} onChange={e=>setPlanDraft({...planDraft,ending:e.target.value})}/></label><p className="creator-muted">{planDraft.notes}</p><p className="creator-muted">当前 {planDraft.episodes.length} 集；{planMeta?.duration||ip.duration} 分钟要求至少 {(planMeta?.duration||ip.duration)===120?80:50} 集。按故事切分，可跨章或在章内结束，不要求完整章节。</p>{planDraft.episodes.map((e,i)=><article className="ip-plan-episode" key={i}><h3>第{i+1}集</h3><label>原文章节<select multiple aria-label={`第${i+1}集原文章节`} value={e.chapterIds} onChange={ev=>setPlanDraft({...planDraft,episodes:planDraft.episodes.map((v,j)=>j===i?{...v,sourceRanges:undefined,chapterIds:[...ev.target.selectedOptions].map(o=>o.value)}:v)})}>{(ip.sources.find(s=>s.id===planMeta?.sourceId)||source).chapters.map(c=><option key={c.id} value={c.id}>{c.title}</option>)}</select></label><label>分集细纲<textarea value={e.outline||''} onChange={ev=>setPlanDraft({...planDraft,episodes:planDraft.episodes.map((v,j)=>j===i?{...v,outline:ev.target.value}:v)})}/></label></article>)}<footer><button className="secondary" onClick={()=>setPlanDraft(null)}>暂不采用</button><button className="primary" disabled={busy} onClick={()=>startFlow({plan:planDraft})}>采用规划并生成全剧</button></footer></CreatorDialog>}
 {exporting&&<ExportDialog project={project} kind="fruit" api={api} setState={setState} archive={exporting==='archive'} onClose={()=>setExporting('')}/>}
 {docView&&<CreatorDialog title={docView.name} onClose={()=>setDocView(null)}><pre className="creator-doc-view">{docView.content}</pre></CreatorDialog>}
 {history&&<CreatorDialog title="IP 项目记录" onClose={()=>setHistory(false)} className="creator-history-dialog"><p className="creator-muted">阅读进度、改编任务和原文版本独立保留。正文版本在对应集右侧选择。</p>{project.creator.directImport&&<details><summary>{project.creator.directImport.fileName} · 导入的完整剧本原件</summary><pre className="creator-doc-view">{project.creator.directImport.content}</pre></details>}{(ip.sources||[]).map(s=><details key={s.id}><summary>{s.name} · {new Date(s.createdAt).toLocaleString()} · 原文版本</summary><pre className="creator-doc-view">{s.content}</pre></details>)}{(ip.retiredEpisodes||[]).map(e=><details key={e.id}><summary>{e.title} · 已从当前规划移出 · {e.ipVersions?.length||0} 版</summary><p className="creator-muted">旧集与版本仍保留；当前总稿和连续转写不包含这些内容。</p><pre className="creator-doc-view">{formatIPScriptText(e.scriptText)||'尚未写正文'}</pre>{(e.ipVersions||[]).map(v=><details key={v.id}><summary>{v.label} · {new Date(v.createdAt).toLocaleString()}</summary><pre className="creator-doc-view">{formatIPScriptText(v.content)}</pre></details>)}<button className="secondary" disabled={busy} onClick={()=>safely(()=>setState(s=>restoreRetiredIPEpisode(s,project.id,e.id)))}>恢复为末尾一集</button></details>)}<details><summary>小说通读记录（{ip.reading?.length||0} 段）</summary>{ip.reading?.map(r=><pre className="creator-doc-view" key={r.start}>字符 [{r.start},{r.end}){'\n'}{r.note}</pre>)}</details>{project.creator.records.filter(r=>r.type==='ip-task').slice().reverse().map(r=><IPTaskHistory key={r.id} record={r} onDelete={()=>{if(window.confirm('永久删除这条任务记录及其中的过程进度？已保存的正文版本会保留，删除后不能从此记录续接。'))setState(s=>mutateIP(s,project.id,p=>({...p,creator:{...p.creator,records:p.creator.records.filter(item=>item.id!==r.id)}})));}}/>)}</CreatorDialog>}
 </div>;
}
