import {RewriteOutlineCards} from './RewriteOutlineCards.jsx';
import {RewriteMainlineCards} from './RewriteMainlineCards.jsx';
import {REWRITE_MAINLINE_RULE,validateRewriteMainline,readRewriteMainline} from '../../core/rewriteMainline.js';
import {readRewriteOutline,validateRewriteOutline,copyOutlineGroups,REWRITE_OUTLINE_RULE} from '../../core/rewriteOutline.js';
import {FormattedText,FormattedEditor} from '../components/FormattedText.jsx';
import {ReferencePicker} from './ReferencePicker.jsx';
import React,{useState,useRef,useEffect} from 'react';
import {ArrowLeft,BookOpen,FileText,Plus,Play,Square,Save,Download,History,Check,Lock,Trash2,Bot,X} from 'lucide-react';
import {rewriteSources,rewriteState,REWRITE_STAGES,addRewriteSource,removeRewriteSource,saveRewriteAnalysis,selectRewriteSources,addRewritePlan,applyRewriteVersion,deleteRewriteVersion,addRewriteEpisode,removeRewriteEpisode,restoreRewriteEpisode,parseRewriteObject,validateRewritePlan,REWRITE_PLAN_RULE} from '../../core/rewriteWorkflow.js';
import {updateCreatorSection,updateCreatorEpisode,adoptCreatorRecord,updateCreatorProject,creatorInputFingerprint} from '../../core/creatorWorkspace.js';
import {creatorModelOptions} from '../../core/creatorAi.js';
import {CreatorDialog,SourceDialog,ExportDialog} from './CreatorDialogs.jsx';
import {AgentPanel,CandidateList} from './AgentPanel.jsx';
import {EpisodeEditor,MasterView} from './CreatorEditor.jsx';

const stageInstructions={
 macroOutline:`${REWRITE_OUTLINE_RULE} 协同用户创作新故事的骨架，可选择参考多个对标的大事件及小事件，重新排列、改变阶段目标、替换人物行动或原创小事件。按新作已采用设定和用户意图调整因果衔接，顺序打乱后仍需合理。只提出完整结构候选，人工采用前不覆盖现有大纲。`,
 settings:'协同用户设计新作设定：时代、地域风土和社会背景、世界规则、脑洞与个人金手指；明确世界共同能力和主角专属能力的区别。参考所选对标，但按用户意图修改，不能把对标事实当新作已定设定。',
 outline:`${REWRITE_MAINLINE_RULE} 协同用户编写新作主线，依据已采用的新作大纲真实编号组织 A1、A2、B1 等小事件对应的逐集提纲。允许原创、重排和改变剧情，遵守新作已采用设定与用户意图。不要照搬对标集数。`,
 characters:'依据已采用的新作设定和主线设计人物。主要人物详细写性格底色、由性格形成的动机、关系、知情状态、从开端到结局每一步个人事件与命运变化。次要人物简写，人物支线必须交织进主线，不擅自改写已定结局。',
};
export function RewriteWorkspace({project,state,setState,getState,api,agent,onBack,onSave,saveStatus}) {
 const [layout,setLayout]=useState(()=>{try{return localStorage.getItem('xz-rewrite-layout-preview')==='floating'?'floating':'sidebar';}catch{return 'sidebar';}}),[stageView,setStageView]=useState(()=>{try{return localStorage.getItem(`xz-rewrite-view:${project.id}`)==='own'?'own':'reference';}catch{return 'reference';}}),[agentOpen,setAgentOpen]=useState(false),[bookId,setBookId]=useState('');
 useEffect(()=>{try{localStorage.setItem(`xz-rewrite-view:${project.id}`,stageView);}catch{}},[project.id,stageView]);
 const switchLayout=next=>{setLayout(next);try{localStorage.setItem('xz-rewrite-layout-preview',next);}catch{}};
 const [addEpisodeOpen,setAddEpisodeOpen]=useState(false),[episodeName,setEpisodeName]=useState('');
 const [active,setActive]=useState(()=>{try{return localStorage.getItem(`xz-rewrite-pane:${project.id}`)||'source';}catch{return 'source';}}),[error,setError]=useState(''),[sourceOpen,setSourceOpen]=useState(false),[exportOpen,setExportOpen]=useState(false),[archiveOpen,setArchiveOpen]=useState(false),[history,setHistory]=useState(false),[legacy,setLegacy]=useState(false),[batch,setBatch]=useState(''),[selection,setSelection]=useState(project.creator.rewrite?.modelSelection||'');
 useEffect(()=>{try{localStorage.setItem(`xz-rewrite-pane:${project.id}`,active);}catch{}},[active,project.id]);
 useEffect(()=>{if(!['source','master',...REWRITE_STAGES.map(s=>s.key)].includes(active)&&!project.episodes.some(e=>e.id===active))setActive('detail');},[active,project.episodes]);
 const latest=useRef(state);latest.current=state;const stop=useRef(false),alive=useRef(true);useEffect(()=>{alive.current=true;return ()=>{alive.current=false;stop.current=true;};},[]);
 const agentToggle=useRef(null);
 const closeAgent=()=>{setAgentOpen(false);agentToggle.current?.focus();};
 const current=()=> (getState?.()||latest.current).scriptProjects.find(p=>p.id===project.id);
 const books=rewriteSources(project),workflow=rewriteState(project),options=creatorModelOptions(state.apiProfiles,state.activeApiId),profile=options.find(o=>o.selectionId===selection)||options[0];
 const activityTarget=['source','master',...REWRITE_STAGES.map(s=>s.key)].includes(active)?{section:active==='master'?'episode':active}:{episodeId:active};
 const activity=agent.getActivity?.('script',project.id,activityTarget)||agent.activity[`script:${project.id}`]||{},busy=!!batch||activity.running,episode=project.episodes.find(e=>e.id===active);
 const mutationBusy=!!batch||!!agent.getActivity?.('script',project.id,{section:'episode'})?.running||!!agent.getActivity?.('script',project.id,{section:'detail'})?.running;
 const deleteEpisode=ep=>{if(mutationBusy)return;if(window.confirm(`删除${ep.title}？正文与 Agent 功能保留在项目资料中，可恢复。`))attempt(()=>setState(s=>removeRewriteEpisode(s,project.id,ep.id)));};
 const attempt=fn=>{try{fn();setError('');}catch(e){setError(e.message);}};
 const pause=()=>new Promise(resolve=>setTimeout(resolve,0));
 const recordFor=(p,id)=>p.creator.records.find(r=>r.id===id);
 const config=()=>{if(!profile)throw new Error('先在 API 接口中添加并选择模型');return {kind:'script',projectId:project.id,profile,scope:'project',skillId:''};};
 const cancel=(kind='script',id=project.id,target=activityTarget)=>{if(batch)stop.current=true;agent.cancel(kind,id,batch?{section:'episode'}:target);};
 const displayAgent={...agent,getActivity:(kind,id,target)=>batch&&(target.episodeId||target.section==='detail')?{running:true,label:batch}:agent.getActivity?.(kind,id,target)||agent.activity[`${kind}:${id}`]||{},cancel};
 const runBatch=async(label,fn)=>{if(busy)return;stop.current=false;setBatch(label);setError('');try{await fn();}catch(e){setError(e.message);}finally{setBatch('');}};
 const analyze=async(ids,analysisStage)=>{
   setError('');let args;try{args=config();}catch(e){setError(e.message);return;}
   const results=await Promise.allSettled(ids.map(async id=>{
     if(analysisStage==='outline'&&!rewriteSources(current()).find(b=>b.id===id)?.analysis?.macroOutline)throw new Error('请先拆解本书大纲，再将主线集纲关联到 A1、A2 等小事件。也可以在对标剧本页一键拆解全部。');
     const target={section:'rewriteAnalysis',sourceId:id,task:'rewriteAnalyze',side:'input',...(analysisStage?{analysisStage}: {})};
     const recordId=await agent.run({...args,target,instruction:analysisStage?`只拆解本书的${REWRITE_STAGES.find(s=>s.key===analysisStage)?.label}，输出 JSON 字段 ${analysisStage}。`:'一键拆解设定、大纲、主线、人物，四个区域分别完整保存。大纲只按大事件及小事件组织，不分配集数。'});
     await pause();const record=recordFor(current(),recordId);
     if(!analysisStage)validateRewriteOutline(parseRewriteObject(record.output).macroOutline);
     if(!analysisStage||analysisStage==='outline')validateRewriteMainline(parseRewriteObject(record.output).outline,analysisStage?rewriteSources(current()).find(b=>b.id===id)?.analysis?.macroOutline:parseRewriteObject(record.output).macroOutline);
     if(record.inputFingerprint!==creatorInputFingerprint(current(),record.target))throw new Error('对标来源已变化，拆解留在任务历史，请复核后采用。');
     saveRewriteAnalysis(getState?.()||latest.current,project.id,id,record.output,analysisStage);
     setState(s=>saveRewriteAnalysis(s,project.id,id,record.output,analysisStage));await pause();
   }));
   const failures=results.filter(r=>r.status==='rejected');if(failures.length&&alive.current)setError([...new Set(failures.map(r=>r.reason.message))].join('；'));
 };
 const checkConstraints=()=>{const p=current();for(const key of ['settings',...(p.creator.sections.macroOutline?.output?.trim()?['macroOutline']:[]),'outline','characters']){const value=p.creator.sections[key];if(!value?.accepted||value.stale||!value.output?.trim())throw new Error(`请先确认新作${REWRITE_STAGES.find(k=>k.key===key).label}，再生成细纲或正文`);}return p;};
 const createPlan=async args=>{if(batch)throw new Error('正文任务正在运行');checkConstraints();const id=await agent.run({...args,target:{section:'detail',side:'output',task:'rewritePlan'},instruction:[REWRITE_PLAN_RULE,args.instruction].join('\n\n')});await pause();const raw=recordFor(current(),id)?.output;validateRewritePlan(raw);const record=recordFor(current(),id);if(record.inputFingerprint!==creatorInputFingerprint(current(),record.target))throw new Error('生成期间新作资料已变化，细纲保留在任务历史，请复核后再采用。');setState(s=>addRewritePlan(s,project.id,raw));await pause();};
 const generate=async ids=>runBatch('生成正文',async()=>{
   const args=config();checkConstraints();const versionId=rewriteState(current()).activeVersionId;if(!versionId&&ids.some(id=>!current().episodes.find(e=>e.id===id)?.manualRewrite))throw new Error('请先采用一个细纲版本');
   for(const id of ids){if(stop.current||!alive.current)break;
     if(rewriteState(current()).activeVersionId!==versionId)throw new Error('细纲版本已切换，已停止旧版本任务');
     const ep=current().episodes.find(e=>e.id===id);if(!ep)throw new Error('分集已移除');
     setBatch(`生成 ${ep.title}`);
     const recordId=await agent.run({...args,target:{episodeId:id,side:'output',inputSide:'input',task:'episode'},instruction:`按本集细纲写完整可表演的分场剧本，动作与对白充分展开，不是摘要。大纲骨架、主线、设定与人物以新作已采用内容为准。严格衔接已生成的前集事实、人物知情与关系状态；埋设并兑现伏笔，禁止割裂为无关联单元剧。只写${ep.title}，使用正确本集场号。\n本集悬念：${ep.hook||''}\n衔接要求：${ep.continuity||''}`});
     await pause();if(rewriteState(current()).activeVersionId!==versionId)throw new Error('细纲版本已变化，结果保留为候选');
     // Adoption uses the existing fingerprint check; a simultaneous user edit cannot be silently overwritten.
     adoptCreatorRecord(getState?.()||latest.current,'script',project.id,recordId);
     setState(s=>adoptCreatorRecord(s,'script',project.id,recordId));await pause();
   }
 });
 const applyVersion=id=>attempt(()=>{if(busy)throw new Error('请先停止任务再切换版本');setState(s=>applyRewriteVersion(s,project.id,id));setActive('detail');});
 const sourceChooser=key=>{
   const ids=workflow.selections[key]||[];
   return <ReferencePicker items={books.map(b=>({id:b.id,title:b.name}))} selected={ids} onChange={ids=>setState(s=>selectRewriteSources(s,project.id,key,ids))}/>;
 };
 const appendOutline=groups=>attempt(()=>{const own=readRewriteOutline(current().creator.sections.macroOutline?.output);setState(s=>updateCreatorSection(s,'script',project.id,'macroOutline',{output:JSON.stringify({groups:[...own.groups,...copyOutlineGroups(groups)]}),accepted:false}));});
 const bookCard=(b,key)=> <article className="rewrite-book-card" key={b.id}><header><strong><BookOpen size={16}/>{b.name}</strong><div className="rewrite-book-actions"><button className="ghost" disabled={busy} onClick={()=>analyze([b.id],key)}>{b.analysis?.[key]?'重新拆解':'拆解本书'}</button>{b.analysis?.[key]&&<button className="ghost" disabled={project.creator.sections[key]?.locked} onClick={()=>{if(project.creator.sections[key]?.output&&!window.confirm('引用本书拆解替换新作草稿？原稿保留在历史，引用后仍需确认采用。'))return;setState(s=>updateCreatorSection(s,'script',project.id,key,{output:key==='macroOutline'?JSON.stringify(readRewriteOutline(b.analysis[key])):typeof b.analysis[key]==='string'?b.analysis[key]:JSON.stringify(b.analysis[key]),accepted:false}));}}>引用到草稿</button>}</div></header>{b.analysis?.[key]?(key==='macroOutline'?<RewriteOutlineCards value={b.analysis[key]} readOnly navigate onReferenceGroup={project.creator.sections.macroOutline?.locked?undefined:g=>appendOutline([g])} onReferenceEvent={project.creator.sections.macroOutline?.locked?undefined:(g,e)=>appendOutline([{...g,events:[e]}])}/>:<>{key==='outline'?<RewriteMainlineCards value={b.analysis[key]} outline={b.analysis?.macroOutline} readOnly onReorganize={busy?undefined:()=>analyze([b.id],'outline')}/>:<FormattedText text={b.analysis[key]}/>}</>):<><p className="creator-muted">尚未拆解此书的{REWRITE_STAGES.find(s=>s.key===key)?.label}。可单本分析，或在顶部批量分析所选剧本。</p><FormattedText className="rewrite-source-excerpt" aria-label="对标原文预览" text={b.content.slice(0,12000)}/></>}</article>;
 const stage=REWRITE_STAGES.find(s=>s.key===active),value=project.creator.sections[active]||{};
 const modelConfig=<div className="rewrite-run-config"><label>接口与模型<select aria-label="洗稿模型" value={profile?.selectionId||''} onChange={e=>{setSelection(e.target.value);setState(s=>updateCreatorProject(s,'script',project.id,{rewrite:{...rewriteState(current()),modelSelection:e.target.value}}));}}>{!profile&&<option value="">请选择接口</option>}{options.map(o=><option key={o.selectionId} value={o.selectionId}>{o.name} · {o.model}</option>)}</select></label>{busy&&<div role="status"><span title={batch||activity.label}>{batch||`${activity.count||1} 项分析或创作任务运行中`}</span><button className="secondary" onClick={()=>cancel()}><Square size={14}/>停止</button></div>}</div>;
 return <div className="creator-shell rewrite-shell"><nav className="creator-directory"><div className="project-directory-fixed"><button className="ghost creator-back" onClick={onBack}><ArrowLeft size={16}/>全部项目</button><strong>{project.name}</strong><small>洗稿</small><button className={active==='master'?'active':''} onClick={()=>setActive('master')}><FileText size={15}/>总剧本</button><button className={active==='source'?'active':''} onClick={()=>setActive('source')}><BookOpen size={15}/>对标剧本</button><span className="creator-nav-label">拆解与新作</span>{REWRITE_STAGES.map(s=><button className={active===s.key?'active':''} key={s.key} onClick={()=>setActive(s.key)}>{s.label}{project.creator.sections[s.key]?.accepted&&<Check size={13}/>}</button>)}<span className="creator-nav-label">分集正文</span></div><div className="project-directory-scroll">{project.episodes.map((ep,i)=><div className="rewrite-episode-nav-row" key={ep.id}><button className={active===ep.id?'active':''} onClick={()=>setActive(ep.id)}><span className="creator-episode-number">{String(i+1).padStart(2,'0')}</span><span>{ep.title}</span>{ep.result?.trim()&&<Check size={12}/>}</button><button className="ghost danger" aria-label={`删除${ep.title}`} title={`删除${ep.title}`} disabled={mutationBusy} onClick={()=>deleteEpisode(ep)}><Trash2 size={12}/></button></div>)}<button className="creator-add-node" disabled={mutationBusy} onClick={()=>{setEpisodeName('');setAddEpisodeOpen(true);}}><Plus size={14}/>添加集数</button></div></nav>
 <main className="creator-main"><header className="creator-toolbar"><strong>{project.name}</strong><small>洗稿</small><span className="creator-save-status">{saveStatus?.saving?'正在保存…':saveStatus?.error?'保存失败，请重试':'自动保存到本地'}</span><button className="secondary" onClick={()=>setHistory(true)}><History size={15}/>项目资料</button><button className="secondary" onClick={onSave}><Save size={15}/>保存</button><button className="secondary" onClick={()=>setExportOpen(true)}><Download size={15}/>导出</button><button className="primary" onClick={()=>setArchiveOpen(true)}>收录剧本库</button></header>
 {error&&<div className="creator-error-bar" role="alert">{error}<button className="ghost" onClick={()=>setError('')}>关闭</button></div>}

 {active==='source'&&<section className="creator-source-page"><div className="creator-section-head"><h2>对标剧本</h2><div className="creator-inline-actions">{modelConfig}<button className="secondary" disabled={busy} onClick={()=>setSourceOpen(true)}><Plus size={15}/>添加对标剧本</button><button className="primary" disabled={busy||!books.length} onClick={()=>analyze(books.map(b=>b.id))}><Play size={15}/>一键拆解全部</button></div></div><div className="rewrite-books">{books.map(b=><article className="rewrite-book-card" key={b.id}><header><strong>{b.name}</strong><div className="creator-inline-actions"><button className="secondary" disabled={busy} onClick={()=>analyze([b.id])}>一键拆解</button><button className="secondary" disabled={busy} aria-label={`移除对标${b.name}`} onClick={()=>{if(window.confirm('移除此对标来源？新作与版本记录保留。'))setState(s=>removeRewriteSource(s,project.id,b.id));}}><Trash2 size={14}/>移除</button></div></header><p className="creator-muted">{b.episodes?.length||1}集 · {b.content.length.toLocaleString()}字 · {b.analysis?.settings&&b.analysis?.macroOutline&&b.analysis?.outline&&b.analysis?.characters?'设定、大纲、主线、人物已拆解':'待拆解'}</p><details><summary>查看原剧本</summary><pre>{b.content}</pre></details></article>)}{!books.length&&<button className="creator-empty" onClick={()=>setSourceOpen(true)}>添加对标剧本：从果子库选择或上传 TXT / Word</button>}</div></section>}
 {stage&&active!=='detail'&&<section className={`rewrite-stage rewrite-layout-${layout} ${active==='macroOutline'?'rewrite-stage-macro':''}`}>
  <div className="rewrite-stage-heading"><h2>{stage.label}</h2>{sourceChooser(active)}{modelConfig}<button className="primary" disabled={busy||!profile||!(workflow.selections[active]||[]).length} onClick={()=>analyze(workflow.selections[active]||[],active)}><Play size={14}/>一键分析所选</button></div>
  <div className="rewrite-view-toolbar"><div className="rewrite-view-tabs" role="group" aria-label="拆解与新作页面切换"><button aria-pressed={stageView==='reference'} className={stageView==='reference'?'active':''} onClick={()=>setStageView('reference')}><BookOpen size={15}/>对标拆解</button><button aria-pressed={stageView==='own'} className={stageView==='own'?'active':''} onClick={()=>setStageView('own')}><FileText size={15}/>新作{stage.label}</button></div><label className="rewrite-layout-picker">布局预览<select aria-label="布局预览方案" value={layout} onChange={e=>switchLayout(e.target.value)}><option value="sidebar">方案一 · 协作侧栏</option><option value="floating">方案二 · 协作浮窗</option></select></label>{layout==='floating'&&<button ref={agentToggle} className="secondary rewrite-agent-toggle" aria-controls={`rewrite-agent-${project.id}`} aria-expanded={agentOpen} onClick={()=>setAgentOpen(!agentOpen)}><Bot size={16}/>{agentOpen?'收起项目协作':'打开项目协作'}{activity.running&&<span className="rewrite-task-dot"/>}</button>}</div>
  {active==='macroOutline'&&<p className="creator-muted rewrite-outline-hint">A、B、C 是大事件；A1、A2 等是组内小事件。点击组号切换查看，按核心行动与作用整理，不划分集数。</p>}
  <div className={`rewrite-stage-columns rewrite-reading-columns ${stageView==='own'?'show-own':'show-reference'}`}>
   <div className="rewrite-analysis-column" hidden={stageView!=='reference'}>
    {books.length>1&&<nav className="rewrite-book-tabs" aria-label="对标书切换">{books.map(b=><button key={b.id} aria-pressed={b.id===(books.some(b=>b.id===bookId)?bookId:books[0]?.id)} className={b.id===(books.some(b=>b.id===bookId)?bookId:books[0]?.id)?'active':''} onClick={()=>setBookId(b.id)} title={b.name}>{b.name}</button>)}</nav>}
    {books.map(b=><div key={b.id} hidden={b.id!==(books.some(b=>b.id===bookId)?bookId:books[0]?.id)}>{bookCard(b,active)}</div>)}{!books.length&&<p>请先添加对标剧本。</p>}
   </div>
   <section className="creator-text-pane" hidden={stageView!=='own'}><header><strong>新作{stage.label}</strong><div className="creator-inline-actions"><button className="secondary" disabled={!value.output?.trim()||value.locked} onClick={()=>attempt(()=>{if(active==='macroOutline')validateRewriteOutline(value.output);if(active==='outline'&&(!readRewriteMainline(value.output).legacyText||readRewriteMainline(value.output).eventGroups.length))validateRewriteMainline(value.output,project.creator.sections.macroOutline?.output);setState(s=>updateCreatorSection(s,'script',project.id,active,{accepted:true,stale:false}));})}><Check size={14}/>{value.accepted&&!value.stale?'已采用':'确认采用'}</button><button className="secondary" disabled={!value.output?.trim()||!value.accepted} onClick={()=>setState(s=>updateCreatorSection(s,'script',project.id,active,{locked:!value.locked}))}><Lock size={13}/>{value.locked?'解锁':'锁定'}</button></div></header>{value.stale&&<p className="creator-warning">上游已变化，请核对后确认采用。</p>}
    {active==='macroOutline'?<div className="rewrite-outline-editor"><RewriteOutlineCards value={value.output} navigate readOnly={value.locked} onChange={output=>attempt(()=>setState(s=>updateCreatorSection(s,'script',project.id,'macroOutline',{output,accepted:false})))}/></div>:active==='outline'?<div className="rewrite-outline-editor"><RewriteMainlineCards value={value.output} outline={project.creator.sections.macroOutline?.output} readOnly={value.locked} onReorganize={busy||value.locked?undefined:()=>{setAgentOpen(true);agent.run({...config(),chat:true,target:{section:'outline',side:'output',format:'rewriteMainline'},instruction:`${stageInstructions.outline}\n请将当前原有主线整理为对应大纲小事件的逐集提纲，保留原有内容和证据。`,displayInstruction:'将原有主线整理为对应大纲小事件的逐集提纲'}).catch(e=>setError(e.message));}} onChange={output=>attempt(()=>setState(s=>updateCreatorSection(s,'script',project.id,'outline',{output,accepted:false})))}/></div>:<FormattedEditor aria-label={`新作${stage.label}`} readOnly={value.locked} value={value.output||''} placeholder="选择参考剧本，与 Agent 协作修改；确认采用后供后续阶段读取。" onChange={e=>setState(s=>updateCreatorSection(s,'script',project.id,active,{output:e.target.value,accepted:false}))}/>}</section>
   <div id={`rewrite-agent-${project.id}`} className="rewrite-agent-dock" role={layout==='floating'?'dialog':undefined} aria-label={layout==='floating'?`项目协作浮窗 · ${stage.label}`:undefined} hidden={layout==='floating'&&!agentOpen} onKeyDown={e=>{if(layout==='floating'&&e.key==='Escape'){e.stopPropagation();closeAgent();}}}>
    {layout==='floating'&&<div className="rewrite-agent-window-bar"><span>项目协作 · {stage.label}</span><button className="ghost" aria-label="关闭协作浮窗" onClick={closeAgent}><X size={17}/></button></div>}
    <AgentPanel defaultSelection={profile?.selectionId} key={active} project={project} kind="script" state={state} setState={setState} agent={displayAgent} target={{section:active,side:'output',...(active==='outline'?{format:'rewriteMainline'}:{})}} onError={setError} chat defaultInstruction={stageInstructions[active]} onRun={args=>agent.run({...args,displayInstruction:args.instruction,instruction:`${stageInstructions[active]}\n用户意见：${args.instruction}`,profile:args.profile})}/>
   </div>
  </div>
 </section>}
 {active==='detail'&&<section className="rewrite-detail"><div className="creator-section-head"><div><h2>细纲与版本</h2><p className="creator-muted">主要事件分配集数，每集落实小事件、人物交织和衔接。</p></div><div className="creator-inline-actions">{modelConfig}<button className="primary" disabled={busy||!workflow.activeVersionId} onClick={()=>generate(project.episodes.filter(e=>!e.result?.trim()||e.stale).map(e=>e.id))}><Play size={15}/>生成全部未完成正文</button></div></div>{sourceChooser('episode')}<AgentPanel defaultSelection={profile?.selectionId} project={project} kind="script" state={state} setState={setState} agent={displayAgent} hideCandidates target={{section:'detail',side:'output',task:'rewritePlan'}} onError={setError} actionLabel="生成新细纲版本" defaultInstruction={REWRITE_PLAN_RULE} onRun={createPlan}/><div className="rewrite-versions">{workflow.versions.slice().reverse().map(v=><article className={`rewrite-book-card ${workflow.activeVersionId===v.id?'active':''}`} key={v.id}><header><strong>{v.name||`第${v.number}版`} · {workflow.activeVersionId===v.id?project.episodes.length:v.snapshot.episodes.length}集</strong><div className="creator-inline-actions"><button className="primary" disabled={busy||workflow.activeVersionId===v.id} onClick={()=>applyVersion(v.id)}>{workflow.activeVersionId===v.id?'当前采用':'采用此版本'}</button><button className="secondary" disabled={busy||workflow.activeVersionId===v.id} onClick={()=>{if(window.confirm('删除此细纲版本及其中保存的正文？'))setState(s=>deleteRewriteVersion(s,project.id,v.id));}}><Trash2 size={14}/>删除</button></div></header><small>{new Date(v.createdAt).toLocaleString('zh-CN')}</small>{v.plan?.majorEvents.map(event=><p key={event.id}><strong>{event.title} · 第{event.startEpisode}—{event.endEpisode}集</strong><br/>{event.events}<br/>{event.timeline}</p>)}<details><summary>各集细纲与正文</summary>{(workflow.activeVersionId===v.id?project.episodes:v.snapshot.episodes).map(ep=><article key={ep.id}><h4>{ep.title}{ep.manualRewrite?' · 人工新增':''} · {ep.result?.trim()?'已生成正文':'待生成'}</h4><FormattedText text={ep.content}/>{ep.result?.trim()&&<details><summary>查看正文</summary><FormattedText text={ep.result}/></details>}</article>)}</details></article>)}</div></section>}
 {episode&&<EpisodeEditor key={episode.id} project={project} episode={episode} onRemove={()=>deleteEpisode(episode)} removeDisabled={mutationBusy} kind="script" state={state} setState={setState} api={api} agent={displayAgent} onError={setError} toolbarActions={<> {modelConfig}<button className="primary" disabled={busy||(!workflow.activeVersionId&&!episode.manualRewrite)} onClick={()=>generate([episode.id])}><Play size={15}/>{episode.result?.trim()?'重新生成本集正文':'生成本集正文'}</button><button className="secondary" disabled={busy||!episode.result?.trim()} onClick={()=>setState(s=>updateCreatorEpisode(s,'script',project.id,episode.id,{finalConfirmed:true,stale:false}))}><Check size={14}/>{episode.finalConfirmed&&!episode.stale?'已确认终稿':'确认本集终稿'}</button> </>}/> }
 {active==='master'&&<MasterView project={project} kind="script" setState={setState} onError={setError} toolbarActions={<>{modelConfig}<button className="primary" disabled={busy||!workflow.activeVersionId} onClick={()=>generate(project.episodes.filter(e=>!e.result?.trim()||e.stale).map(e=>e.id))}>生成全部未完成正文</button></>}/>}

 </main>
 {addEpisodeOpen&&<CreatorDialog title="添加集数" onClose={()=>setAddEpisodeOpen(false)}><form onSubmit={e=>{e.preventDefault();attempt(()=>{setState(s=>addRewriteEpisode(s,project.id,episodeName));setAddEpisodeOpen(false);/* Use the persisted node ID from the committed state. */setTimeout(()=>setActive(current().episodes.at(-1).id),0);});}}><p className="creator-muted">在末尾增加一集，可编辑自己的提纲与正文，继续使用 Agent。采用的细纲版本会保留新增分集。</p><label>本集名称<input aria-label="新增分集名称" placeholder="留空自动命名" value={episodeName} onChange={e=>setEpisodeName(e.target.value)}/></label><footer><button type="button" className="secondary" onClick={()=>setAddEpisodeOpen(false)}>取消</button><button className="primary" type="submit">添加并编辑</button></footer></form></CreatorDialog>}
 {sourceOpen&&<SourceDialog state={state} api={api} onClose={()=>setSourceOpen(false)} onError={setError} onChoose={doc=>{attempt(()=>{setState(s=>addRewriteSource(s,project.id,doc));setSourceOpen(false);});}}/>}
 {exportOpen&&<ExportDialog project={project} kind="script" api={api} setState={setState} onClose={()=>setExportOpen(false)}/>}{archiveOpen&&<ExportDialog project={project} kind="script" api={api} setState={setState} archive onClose={()=>setArchiveOpen(false)}/>}
 {history&&<CreatorDialog title="项目资料与历史" onClose={()=>setHistory(false)} className="creator-history-dialog"><button className="secondary" onClick={()=>setLegacy(!legacy)}>查看旧版拆解与新作资料</button>{legacy&&Object.entries(project.creator.sections).map(([key,s])=><details key={key}><summary>{key}</summary>{key==='macroOutline'?<RewriteOutlineCards value={s.output} readOnly navigate/>:<FormattedText className="creator-doc-view" text={`${s.input||''}\n${s.output||''}`}/>}</details>)}{project.creator.records.filter(r=>r.target?.task==='rewriteAnalyze'&&r.output).map(r=><details key={r.id}><summary>拆解原始结果 · {books.find(b=>b.id===r.target.sourceId)?.name||'旧来源'}</summary><textarea aria-label="编辑拆解结果" defaultValue={r.output} onChange={e=>setState(s=>updateCreatorProject(s,'script',project.id,{records:current().creator.records.map(item=>item.id===r.id?{...item,output:e.target.value}:item)}))}/><button className="secondary" onClick={()=>attempt(()=>{const raw=recordFor(current(),r.id).output;saveRewriteAnalysis(getState?.()||latest.current,project.id,r.target.sourceId,raw,r.target.analysisStage);setState(s=>saveRewriteAnalysis(s,project.id,r.target.sourceId,raw,r.target.analysisStage));})}>采用本书拆解</button></details>)}{project.creator.records.filter(r=>r.target?.task==='rewritePlan'&&r.output).map(r=><details key={r.id}><summary>细纲原始结果 · {r.createdAt}</summary><textarea aria-label="编辑细纲结果" defaultValue={r.output} onChange={e=>setState(s=>updateCreatorProject(s,'script',project.id,{records:current().creator.records.map(item=>item.id===r.id?{...item,output:e.target.value}:item)}))}/><button className="secondary" onClick={()=>attempt(()=>{const raw=recordFor(current(),r.id).output;validateRewritePlan(raw);setState(s=>addRewritePlan(s,project.id,raw));})}>保存为细纲版本</button></details>)}<div className="rewrite-deleted-episodes">{project.creator.records.filter(r=>r.type==='deleted-node').map(r=><div key={r.id}><span>{r.node?.title} · {r.status==='restored'?'已恢复':'已删除'}</span><button className="secondary" disabled={mutationBusy||project.episodes.some(e=>e.id===r.node?.id)} onClick={()=>attempt(()=>setState(s=>restoreRewriteEpisode(s,project.id,r.id)))}>恢复{r.node?.title}</button></div>)}</div><CandidateList records={project.creator.records.filter(r=>(r.output||r.error)&&!['rewriteAnalyze','rewritePlan'].includes(r.target?.task)).slice().reverse()} project={project} kind="script" setState={setState} onError={setError}/></CreatorDialog>}
 </div>;
}
