import React,{useState,useRef} from 'react';
import {Sparkles,Check,Trash2,Lock,Square} from 'lucide-react';
import {CreatorDialog} from './CreatorDialogs.jsx';
import {Field,FrameworkDraftContext} from './framework/FrameworkParts.jsx';
import {FormattedText} from '../components/FormattedText.jsx';
import {rewriteIdentity,identityBooks,identitySummary,changeRewriteIdentity,readIdentityObject,validateIdentityCandidate,actorKey} from '../../core/rewriteIdentity.js';
import {groupIdentityReady,assertRewriteIdentityReady,validateIdentityConversion} from '../../core/rewriteConversion.js';
import {readRewriteOutline,validateRewriteOutline} from '../../core/rewriteOutline.js';
import {adoptCreatorRecord,creatorInputFingerprint,updateCreatorSection,updateCreatorProject} from '../../core/creatorWorkspace.js';
import './rewrite-identity.css';

const roles={femaleLead:'女主',maleLead:'男主',lead:'主角',support:'关系人物'};
const relations={mother:'母亲',father:'父亲',stepmother:'继母',stepfather:'继父',adoptiveMother:'养母',adoptiveFather:'养父'};
const display=p=>p?.name||p?.label||'待确认人物';
function IdentityPreview({value,project}){
 if(!value||typeof value!=='object')return <FormattedText text={String(value)}/>;
 const identity=rewriteIdentity(project),people=Array.isArray(value.people)?value.people:identity.people,name=id=>display(people.find(p=>p.id===id));
 if(Array.isArray(value.people))return <div className="rewrite-identity-preview"><h3>新作人物</h3>{value.people.map((p,i)=><article key={p.id||i}><strong>{display(p)} · {roles[p.role]||p.role}</strong>{p.notes&&<p>{p.notes}</p>}</article>)}<h3>新作关系</h3>{(value.relations||[]).map((r,i)=><p key={r.id||i}>{name(r.fromId)} → {relations[r.type]||r.type}：{name(r.toId)}</p>)}<h3>来源角色对应</h3>{(value.bindings||[]).map((b,i)=>{const actor=value.sourceActors?.find(a=>a.sourceId===b.sourceId&&a.id===b.actorId),book=identityBooks(project).find(s=>s.id===b.sourceId);return <article key={i}><strong>{book?.name||'已移除来源'} · {actor?.name||'待核对角色'} → {b.personId?name(b.personId):'待确认对应'}</strong><p>{b.reason||actor?.evidence||'请核对主角关系对应'}</p></article>;})}{value.reasoning&&<p>{value.reasoning}</p>}</div>;
 if(Array.isArray(value.groups))return <div className="rewrite-identity-preview"><p>{value.reasoning}</p>{value.groups.map((g,i)=><section key={g.groupId||i}><h3>{g.title}</h3><p>{g.goal}</p><small>人物：{(g.participantIds||[]).map(name).join('、')}</small>{(g.events||[]).map((e,j)=><article key={e.eventId||j}><strong>{j+1} · {e.title}</strong><p>{e.summary}</p><p>作用与因果：{e.purpose}</p><small>人物：{(e.participantIds||[]).map(name).join('、')}</small></article>)}</section>)}</div>;
 return <FormattedText text={JSON.stringify(value,null,2)}/>;
}

export function RewriteIdentityPane({project,state,setState,getState,agent,profile,modelConfig,onError}){
 const latest=useRef(state);latest.current=state;
 const current=()=> (getState?.()||latest.current).scriptProjects.find(p=>p.id===project.id);
 const f=rewriteIdentity(project),books=identityBooks(project),locked=!!project.creator.sections.characters?.locked;
 const [requirements,setRequirements]=useState(project.creator.rewrite?.identityDraft||''),[recordId,setRecordId]=useState(''),[refine,setRefine]=useState(''),[localError,setLocalError]=useState('');
 const activity=agent.getActivity?.('script',project.id,{section:'characters'})||{},conversionActivity=agent.getActivity?.('script',project.id,{section:'macroOutline'})||{},busy=!!(activity.running||conversionActivity.running);
 let outline,error='';try{outline=readRewriteOutline(project.creator.sections.macroOutline?.output);}catch(e){error=e.message;outline={groups:[]};}
 const ready=outline.groups.filter(g=>groupIdentityReady(project,g)).length,unresolved=f.bindings.filter(b=>b.status==='unresolved'||b.conflict).length;
 const record=project.creator.records.find(r=>r.id===recordId),records=project.creator.records.filter(r=>['rewriteIdentity','rewriteConvert'].includes(r.target?.task));
 const attempt=fn=>{try{fn();onError('');setLocalError('');return true;}catch(e){onError(e.message);setLocalError(e.message);return false;}};
 const mutate=command=>attempt(()=>{changeRewriteIdentity(current(),command);setState(s=>{try{return {...s,scriptProjects:s.scriptProjects.map(p=>p.id===project.id?{...changeRewriteIdentity(p,command),updatedAt:new Date().toISOString()}:p)};}catch(e){setLocalError(e.message);onError(e.message);return s;}});});
 const run=async(target,instruction)=>{
  if(busy)return;
  try{if(!profile)throw new Error('请先选择可用接口。');const id=await agent.run({kind:'script',projectId:project.id,target,profile,scope:'project',instruction:instruction||requirements.trim()||'从确认设定整理新作主角和关系，将所引用事件的不同书籍角色对应到这套身份；不确定关系留为待确认。'});await new Promise(r=>setTimeout(r,0));setRefine('');setRecordId(id);onError('');}catch(e){onError(e.message);setLocalError(e.message);}
 };
 const confirmOutline=()=>attempt(()=>{const p=current();validateRewriteOutline(p.creator.sections.macroOutline.output);assertRewriteIdentityReady(p);updateCreatorSection(getState?.()||latest.current,'script',project.id,'macroOutline',{accepted:true,stale:false});setState(s=>{try{return updateCreatorSection(s,'script',project.id,'macroOutline',{accepted:true,stale:false});}catch(e){setLocalError(e.message);return s;}});});
 let preview=record?.output||'暂无完整输出',stale=true,previewError='';try{if(record){stale=record.inputFingerprint!==creatorInputFingerprint(project,record.target);preview=record.target.task==='rewriteIdentity'?validateIdentityCandidate(project,record.output):validateIdentityConversion(project,record.target,record.output);}}catch(e){previewError=e.message;}
 const adopt=()=>attempt(()=>{adoptCreatorRecord(getState?.()||latest.current,'script',project.id,record.id);setState(s=>{try{return adoptCreatorRecord(s,'script',project.id,record.id);}catch(e){setLocalError(e.message);onError(e.message);return s;}});setRecordId('');});
 return <FrameworkDraftContext.Provider value={`rewrite-identity:${project.id}`}><section className="rewrite-identity-workspace">
  <div className="creator-section-head"><div><h2>人物与关系</h2><p className="creator-muted">先统一新作主角和关系，再转换大小事件；来源名字只作为证据。</p></div><div className="creator-inline-actions">{modelConfig}<button className="secondary" disabled={!f.people.length||locked||busy} onClick={()=>mutate({type:'confirm'})}><Check size={15}/>一键确认人物与对应</button>{project.creator.sections.characters.output&&<button className="secondary" disabled={busy} onClick={()=>attempt(()=>{updateCreatorSection(getState?.()||latest.current,'script',project.id,'characters',{locked:!locked});setState(s=>updateCreatorSection(s,'script',project.id,'characters',{locked:!locked}));})}><Lock size={14}/>{locked?'解锁':'锁定'}</button>}</div></div>
  <div className="rewrite-identity-status"><span>{f.accepted&&!project.creator.sections.characters.stale?'新作人物已确认':'新作人物待确认/复核'} · {f.people.length} 人物 · {unresolved} 条对应待处理</span><span>事件转换 {ready} / {outline.groups.length} 组</span></div>
  <div className="rewrite-identity-layout">
   <section className="rewrite-identity-panel"><header><h3>新作人物库</h3><small>角色身份由编号保持，名字可独立修改</small></header><div className="rewrite-identity-scroll">
    {!f.people.length&&<p className="creator-muted">在右侧说明主角和关系，Agent 会结合已确认设定整理。旧分析保留在下方资料中。</p>}
    <div className="rewrite-person-grid">{f.people.map(p=><article className="rewrite-person-card" key={p.id}><header><strong>{roles[p.role]||p.role}</strong><button className="ghost danger" aria-label={`删除人物${display(p)}`} disabled={locked||busy} onClick={()=>{if(window.confirm('删除此人物？已被事件使用的人物需要先重新绑定。'))mutate({type:'person.remove',id:p.id});}}><Trash2 size={14}/></button></header><Field multiline={false} label={`${display(p)}新作姓名`} draftKey={`${p.id}:name`} value={p.name} disabled={locked||busy} placeholder="未命名可留空" onCommit={name=>mutate({type:'person.update',id:p.id,patch:{name}})}/><Field multiline={false} label={`${display(p)}关系称谓`} draftKey={`${p.id}:label`} value={p.label} disabled={locked||busy} placeholder="例如：女主母亲" onCommit={label=>mutate({type:'person.update',id:p.id,patch:{label}})}/>{f.relations.filter(r=>r.fromId===p.id).map(r=><p key={r.id}>{relations[r.type]||r.type}：{display(f.people.find(v=>v.id===r.toId))}</p>)}</article>)}</div>
    {Array.from(new Set(f.sourceActors.map(a=>a.sourceId))).map(sourceId=>{const book=books.find(b=>b.id===sourceId),actors=f.sourceActors.filter(a=>a.sourceId===sourceId);return <details className="rewrite-source-bindings" key={sourceId}><summary>{book?.name||'已移除来源'} · {actors.length} 个来源角色</summary>{actors.map(a=>{const binding=f.bindings.find(b=>actorKey(b.sourceId,b.actorId)===actorKey(a.sourceId,a.id)),anchor=f.sourceActors.find(v=>v.sourceId===a.sourceId&&v.id===a.anchorActorId);return <div className={`rewrite-binding-row ${binding?.status==='unresolved'?'unresolved':''}`} key={a.id}><div><strong>{a.name}</strong><small>{a.relation?`${anchor?.name||'主角'}的${relations[a.relation]||a.relation}`:roles[a.role]||'来源人物'}</small><small>{a.evidence}</small></div><span>→</span><select aria-label={`${book?.name||'历史来源'} ${a.name} ${a.id}对应新作人物`} disabled={locked||busy||!book} value={binding?.personId||''} onChange={e=>mutate({type:'binding.update',sourceId:a.sourceId,actorId:a.id,personId:e.target.value})}><option value="">待确认对应</option>{f.people.map(p=><option key={p.id} value={p.id}>{display(p)}</option>)}</select>{binding?.conflict&&<button className="secondary" disabled={locked||busy} onClick={()=>mutate({type:'binding.update',sourceId:a.sourceId,actorId:a.id,personId:binding.personId,approveRelationshipChange:true})}>确认按此新关系改写</button>}{binding?.reason&&<p>{binding.reason}</p>}</div>;})}</details>;})}
    <details><summary>原有人物资料与历史</summary>{f.history.length?f.history.slice().reverse().map(h=><article className="rewrite-identity-history" key={h.id}><small>{new Date(h.createdAt).toLocaleString('zh-CN')}</small><FormattedText text={h.characterText||identitySummary(h.snapshot)||'初始人物资料'}/><button className="secondary" disabled={locked||busy} onClick={()=>{if(window.confirm('恢复此时人物资料？当前正文保留，并标为需复核。'))mutate({type:'restore',id:h.id});}}>恢复此人物版本</button></article>):<FormattedText text={project.creator.sections.characters.output||'暂无旧资料'}/>}</details>
   </div></section>
   <section className="rewrite-identity-panel rewrite-identity-compose"><header><h3>告诉 Agent 怎样统一人物</h3></header><div className="rewrite-identity-scroll"><Field autoFocus label="人物与关系要求" draftKey="requirements" value={project.creator.rewrite?.identityDraft||''} onDraftChange={setRequirements} onCommit={text=>mutate({type:'draft',text})} placeholder="例如：新作女主夏初雪、男主陆舟。两本书的女主都对应夏初雪；来源女主的母亲统一为女主母亲，暂不命名。"/>{project.creator.sections.settings.output&&<details><summary>查看当前设定</summary><FormattedText text={project.creator.sections.settings.output}/></details>}<p className="creator-muted">对应关系不明时保留待确认。母亲、继母、养母不会自动混为同一关系。你可以在左侧选择对应人物，或补充要求让 Agent 调整。</p><div className="rewrite-identity-run"><button className="primary" disabled={busy||locked||!profile} onClick={()=>run({section:'characters',task:'rewriteIdentity'},requirements)}><Sparkles size={15}/>整理人物与对应</button></div>
    {(error||localError)&&<p className="creator-error" role="alert">{error||localError}</p>}
    <div className="rewrite-conversion-actions"><h3>把事件转为新作</h3><p className="creator-muted">先确认人物对应，再转换事件。原稿保留，候选采用后才生效；转换完成后可在这里确认大纲。</p><button className="primary" disabled={busy||!profile||!f.accepted||!outline.groups.length||project.creator.sections.macroOutline.locked} onClick={()=>run({section:'macroOutline',task:'rewriteConvert',onlyPending:true},'按已确认的新作人物及主角关系转换所有待处理大小事件，保留故事作用、顺序和出处。'+requirements)}>转换全部待处理事件</button><div className="rewrite-conversion-groups">{outline.groups.map((g,i)=><React.Fragment key={g.id}><div><span>{i+1} · {g.title}</span><small>{groupIdentityReady(project,g)?'已转换':'待转换/复核'}</small><button className="secondary" disabled={busy||!profile||!f.accepted||g.locked||project.creator.sections.macroOutline.locked} onClick={()=>run({section:'macroOutline',task:'rewriteConvert',groupIds:[g.id]},requirements||'只转换此大事件及其小事件，保持其他事件不变。')}>转换本组</button></div><details><summary>本组 {g.events.length} 个小事件</summary>{g.events.map(e=><div className="rewrite-single-conversion" key={e.id}><span>{e.title}</span><button className="secondary" disabled={busy||!profile||!f.accepted||g.locked||e.locked||project.creator.sections.macroOutline.locked} onClick={()=>run({section:'macroOutline',task:'rewriteConvert',eventIds:[e.id]},requirements||'只转换选中的小事件及其必要的大事件称谓，其他小事件内容保留。')}>转换此小事件</button></div>)}</details></React.Fragment>)}</div><button className="secondary" disabled={busy||!outline.groups.length||ready!==outline.groups.length||!f.accepted||project.creator.sections.macroOutline.locked} onClick={confirmOutline}><Check size={15}/>{project.creator.sections.macroOutline.accepted&&!project.creator.sections.macroOutline.stale?'新作大纲已确认':'确认转换后的大纲'}</button></div>
    <details><summary>本项目人物与转换候选 · {records.length}</summary>{records.slice().reverse().map(r=><button className="secondary rewrite-identity-record" key={r.id} onClick={()=>{setRecordId(r.id);setRefine('');}}>{r.target.task==='rewriteIdentity'?'人物与对应':'事件转换'} · {r.status==='adopted'?'已采用':r.status==='pending'?'待采用':r.status}</button>)}</details>
   </div>{busy&&<footer><span role="status">{activity.label||conversionActivity.label||'Agent 正在生成候选'}</span><button className="secondary" onClick={()=>agent.cancel('script',project.id,conversionActivity.running?{section:'macroOutline'}:{section:'characters'})}><Square size={14}/>停止</button></footer>}</section>
  </div>
  {record&&<CreatorDialog title={record.target.task==='rewriteIdentity'?'新作人物与关系候选':'新作事件转换候选'} onClose={()=>setRecordId('')} className="rewrite-identity-dialog"><p className="creator-muted">{record.model} · {stale?'当前依据已变化，结果保留供核对':'采用前不会改动现有稿件'}</p>{record.error&&<p className="creator-error">{record.error}</p>}<>{(previewError||localError)&&<p className="creator-error" role="alert">{previewError||localError}</p>}<IdentityPreview value={preview} project={project}/></><Field label="继续修改的要求" draftKey={`${record.id}:refine`} value="" onDraftChange={setRefine} placeholder="不满意的关系、称谓或事件改写，直接告诉 Agent…"/><footer>{modelConfig}<button className="secondary" disabled={busy||!refine.trim()} onClick={()=>run({...record.target,revisionCandidate:record.output,revisionInstructions:[...(record.target.revisionInstructions||[]),record.instruction].filter(Boolean)},refine)}>按要求继续修改</button><button className="secondary" onClick={()=>setRecordId('')}>保留，暂不采用</button><button className="primary" disabled={busy||stale||!!previewError||record.status!=='pending'} onClick={adopt}><Check size={15}/>采用候选</button></footer></CreatorDialog>}
 </section></FrameworkDraftContext.Provider>;
}
