import {FormattedText,FormattedEditor} from '../components/FormattedText.jsx';
import React, {useState} from 'react';
import {Plus, ArrowUp, ArrowDown, Trash2, PenLine} from 'lucide-react';
import {upsertCreatorStoryItem,removeCreatorStoryItem,reorderCreatorStoryItems,splitCreatorEvent,mergeCreatorEvents} from '../../core/creatorWorkspace.js';
import {CreatorDialog} from './CreatorDialogs.jsx';

// Every stage points to these same items. Text drafts remain separate until reviewed.
export function StoryLedger({project,setState,onError,stage,sectionText=''}) {
 const characters=project.creator.story?.characters||[],events=project.creator.story?.events||[];
 const characterMode=stage==='characters',type=characterMode?'character':'event',items=characterMode?characters:events;
 const [edit,setEdit]=useState(null),[selected,setSelected]=useState([]),[split,setSplit]=useState(null),[splitText,setSplitText]=useState(''),[imported,setImported]=useState(null),[query,setQuery]=useState('');
 const attempt=action=>{try{setState(action);return true;}catch(e){onError(e.message);return false;}};
 const blank=()=>characterMode?{name:'',description:'',start:'',end:'',accepted:false}:{title:'',content:'',result:'',characterIds:[],predecessorIds:[],parentEventId:null,episodeIds:[],actualTime:'',accepted:false};
 const reorder=(item,delta)=>{const ids=items.map(i=>i.id),index=ids.indexOf(item.id);if(index+delta<0||index+delta>=ids.length)return;[ids[index],ids[index+delta]]=[ids[index+delta],ids[index]];attempt(s=>reorderCreatorStoryItems(s,'script',project.id,type,ids));};
 const toggle=(field,id,checked)=>setEdit({...edit,[field]:checked?[...(edit[field]||[]),id]:(edit[field]||[]).filter(i=>i!==id)});
 const parseDraft=()=>{const blocks=sectionText.trim().split(/\n(?=\s*(?:\d+[.、)]|#{1,3}\s))/).filter(s=>s.trim());setImported(blocks.map(s=>({...blank(),[characterMode?'name':'title']:s.split('\n')[0].replace(/^\s*(?:\d+[.、)]|#{1,3}\s)\s*/,'').slice(0,100),[characterMode?'description':'content']:s,accepted:false})));};
 const beginMerge=()=>{const chosen=events.filter(i=>selected.includes(i.id)),parents=[...new Set(chosen.map(i=>i.parentEventId).filter(id=>id&&!selected.includes(id)))],union=field=>[...new Set(chosen.flatMap(i=>i[field]||[]))];setEdit({...blank(),mergeIds:selected,parentEventId:parents.length===1?parents[0]:null,title:chosen.map(i=>i.title).join('＋'),content:chosen.map(i=>i.content).filter(Boolean).join('\n\n'),result:chosen.map(i=>i.result).filter(Boolean).join('\n\n'),characterIds:union('characterIds'),episodeIds:union('episodeIds'),predecessorIds:union('predecessorIds').filter(id=>!selected.includes(id)),actualTime:chosen.map(i=>i.actualTime).filter(Boolean).join(' → ')});};
 const eventName=id=>events.find(e=>e.id===id)?.title||'待复核关联';
 return <details className="creator-story-ledger" open><summary>{characterMode?'统一人物档案':'统一事件与关联'} · {items.length}项</summary><p className="creator-muted">这里的条目在人物、骨架、细纲、时间线和分集中共用。修改已采用条目会提示终稿复核。</p><div className="creator-inline-actions"><button className="secondary" onClick={()=>setEdit(blank())}><Plus size={14}/>新建{characterMode?'人物':'事件'}</button><button className="secondary" disabled={!sectionText.trim()} onClick={parseDraft}>从当前成果整理条目</button>{!characterMode&&<button className="secondary" disabled={selected.length<2} onClick={beginMerge}>合并所选事件</button>}<input aria-label="筛选故事条目" placeholder="筛选条目" value={query} onChange={e=>setQuery(e.target.value)}/></div>
 <div className="creator-story-items">{items.filter(i=>(i.name||i.title||'').includes(query)).map((item,index)=><article key={item.id}><header>{!characterMode&&<input aria-label={`选择事件${item.title}`} type="checkbox" checked={selected.includes(item.id)} onChange={e=>setSelected(e.target.checked?[...selected,item.id]:selected.filter(id=>id!==item.id))}/>}<strong>{index+1}. {item.name||item.title}</strong><small>{item.accepted?'当前采用':'备选'} · {item.id.slice(-6)}</small><button className="ghost" aria-label={`编辑条目${item.name||item.title}`} onClick={()=>setEdit({...item})}><PenLine size={14}/></button></header><p>{item.description||item.content}</p>{!characterMode&&<small>结果：{item.result||'待补充'}<br/>人物：{(item.characterIds||[]).map(id=>characters.find(c=>c.id===id)?.name).filter(Boolean).join('、')||'未关联'} · 前置：{(item.predecessorIds||[]).map(eventName).join('、')||'无'}{item.parentEventId&&` · 大事件：${eventName(item.parentEventId)}`}<br/>发生时间：{item.actualTime||'未定'} · 分集：{(item.episodeIds||[]).map(id=>project.episodes.find(e=>e.id===id)?.title).filter(Boolean).join('、')||'未分配'}</small>}{characterMode&&<small>起点：{item.start||'未定'} · 结局：{item.end||'未定'}<br/>人物线：{events.filter(e=>e.characterIds?.includes(item.id)).map(e=>e.title).join(' → ')||'暂无关联事件'}</small>}<footer><button className="secondary" onClick={()=>attempt(s=>upsertCreatorStoryItem(s,'script',project.id,type,{id:item.id,accepted:!item.accepted}))}>{item.accepted?'留作备选':'采用条目'}</button>{!characterMode&&<button className="secondary" onClick={()=>{setSplit(item);setSplitText('');}}>拆分事件</button>}<button className="ghost" aria-label={`上移条目${item.name||item.title}`} onClick={()=>reorder(item,-1)}><ArrowUp size={14}/></button><button className="ghost" aria-label={`下移条目${item.name||item.title}`} onClick={()=>reorder(item,1)}><ArrowDown size={14}/></button><button className="ghost" aria-label={`删除条目${item.name||item.title}`} onClick={()=>{if(window.confirm('移除此条目并清理它的关联？旧条目会留在项目资料中。'))attempt(s=>removeCreatorStoryItem(s,'script',project.id,type,item.id));}}><Trash2 size={14}/></button></footer></article>)}</div>
 {edit&&<CreatorDialog title={characterMode?'编辑人物档案':'编辑事件及关联'} onClose={()=>setEdit(null)}><form onSubmit={e=>{e.preventDefault();const {mergeIds,...patch}=edit;if(attempt(s=>mergeIds?mergeCreatorEvents(s,'script',project.id,mergeIds,patch):upsertCreatorStoryItem(s,'script',project.id,type,patch))){setEdit(null);setSelected([]);}}}><label>{characterMode?'姓名':'事件名称'}<input aria-label="故事条目名称" required value={edit.name??edit.title??''} onChange={e=>setEdit({...edit,[characterMode?'name':'title']:e.target.value})}/></label><label>{characterMode?'身份、性格、目标与知情状态':'行动与过程'}<textarea aria-label="故事条目内容" value={edit.description??edit.content??''} onChange={e=>setEdit({...edit,[characterMode?'description':'content']:e.target.value})}/></label>{characterMode?<><label>起点与初始状态<input value={edit.start||''} onChange={e=>setEdit({...edit,start:e.target.value})}/></label><label>结局与最终状态<input value={edit.end||''} onChange={e=>setEdit({...edit,end:e.target.value})}/></label></>:<><label>结果与故事作用<textarea value={edit.result||''} onChange={e=>setEdit({...edit,result:e.target.value})}/></label><label>实际发生时间<input value={edit.actualTime||''} placeholder="如第2天早晨；叙事顺序用条目上下移动" onChange={e=>setEdit({...edit,actualTime:e.target.value})}/></label><label>所属大事件<select value={edit.parentEventId||''} onChange={e=>setEdit({...edit,parentEventId:e.target.value||null})}><option value="">无／独立大事件</option>{events.filter(i=>i.id!==edit.id&&!edit.mergeIds?.includes(i.id)).map(i=><option key={i.id} value={i.id}>{i.title}</option>)}</select></label><fieldset><legend>出场人物</legend>{characters.map(i=><label className="creator-check" key={i.id}><input type="checkbox" checked={(edit.characterIds||[]).includes(i.id)} onChange={e=>toggle('characterIds',i.id,e.target.checked)}/>{i.name}</label>)}</fieldset><fieldset><legend>前置事件／因果</legend>{events.filter(i=>i.id!==edit.id&&!edit.mergeIds?.includes(i.id)).map(i=><label className="creator-check" key={i.id}><input type="checkbox" checked={(edit.predecessorIds||[]).includes(i.id)} onChange={e=>toggle('predecessorIds',i.id,e.target.checked)}/>{i.title}</label>)}</fieldset><fieldset><legend>所属分集</legend>{project.episodes.filter(i=>i.type==='episode').map(i=><label className="creator-check" key={i.id}><input type="checkbox" checked={(edit.episodeIds||[]).includes(i.id)} onChange={e=>toggle('episodeIds',i.id,e.target.checked)}/>{i.title}</label>)}</fieldset></>}<label className="creator-check"><input type="checkbox" checked={!!edit.accepted} onChange={e=>setEdit({...edit,accepted:e.target.checked})}/>设为当前采用，供后续创作使用</label><footer><button type="button" className="secondary" onClick={()=>setEdit(null)}>取消</button><button className="primary">保存条目</button></footer></form></CreatorDialog>}
 {split&&<CreatorDialog title="拆分为具体事件" onClose={()=>setSplit(null)}><p className="creator-muted">每行一个子事件。原事件保留为大事件，子事件共享人物和分集关联，待人工采用。</p><textarea aria-label="子事件清单" style={{width:'100%',minHeight:180}} value={splitText} onChange={e=>setSplitText(e.target.value)}/><footer><button className="primary" disabled={splitText.split('\n').filter(s=>s.trim()).length<2} onClick={()=>{const children=splitText.split('\n').filter(s=>s.trim()).map(s=>({title:s.trim(),content:s.trim(),accepted:false}));if(attempt(s=>splitCreatorEvent(s,'script',project.id,split.id,children)))setSplit(null);}}>确认拆分</button></footer></CreatorDialog>}
 {imported&&<CreatorDialog title="核对待入库条目" onClose={()=>setImported(null)}><p className="creator-muted">仅按编号分段，未经核实的条目先作为备选。保存后可逐条修改和关联。</p>{imported.map((item,index)=><section key={index}><label>名称<input value={item.name||item.title} onChange={e=>setImported(imported.map((i,n)=>n===index?{...i,[characterMode?'name':'title']:e.target.value}:i))}/></label><FormattedText className="creator-doc-view" text={item.description||item.content}/></section>)}<footer><button className="primary" disabled={!imported.length} onClick={()=>{if(attempt(s=>imported.reduce((next,item)=>upsertCreatorStoryItem(next,'script',project.id,type,item),s)))setImported(null);}}>保存为备选条目</button></footer></CreatorDialog>}
 </details>;
}
