import React,{useEffect,useRef,useState} from 'react';
import {Sparkles,Square,Plus,GitBranch,Check,Download,RefreshCw,Globe,FileText} from 'lucide-react';
import {CreatorDialog} from './CreatorDialogs.jsx';
import {creatorModelOptions} from '../../core/creatorAi.js';
import {assertMessageCapacity} from '../../core/skillExecution.js';
import {projectWorldSeed,projectWorldPlan,sourceFingerprint,worldWorkspace,putWorld,applyWorldStory} from '../../core/worldSimulationAdapter.js';
import {createWorld,uid,copy,getBranch,branchState,addCandidate,commitCandidate,forkAt,forkBranch,compareBranches,exportLife,worldFingerprint} from '../../world-simulation/engine.js';
import {proposeNext} from '../../world-simulation/runner.js';
import {chunkDocument} from '../../world-simulation/documents.js';
import './world-simulation.css';

const defaults={horizon:1440,candidateCount:3,maxCalls:20,rounds:2,instruction:'',actorIds:null,selection:'',protagonistId:''};
const timeLabel=t=>`第${Math.floor(t/1440)+1}天 ${Math.floor(t%1440/60)}:${String(t%60).padStart(2,'0')}`;
export function WorldSimulationWorkbench({project,state,setState,getState,api,externalBusy=false}){
 const latest=useRef({state,project}),job=useRef(null),alive=useRef(true);latest.current={state,project};
 const ws=worldWorkspace(project),world=ws.worlds.find(w=>w.id===ws.activeWorldId)||ws.worlds[0],branch=world?getBranch(world):null;
 const [error,setError]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState(null),[editor,setEditor]=useState(null),[draft,setDraft]=useState(''),[heroName,setHeroName]=useState(''),[heroGoal,setHeroGoal]=useState(''),[compareId,setCompareId]=useState('');
 const cfg={...defaults,...world?.config},options=creatorModelOptions(state.apiProfiles,state.activeApiId),profile=options.find(o=>o.selectionId===cfg.selection)||options[0];
 const source=projectWorldSeed(project),currentState=()=>getState?.()||latest.current.state,currentProject=()=>currentState().scriptProjects.find(p=>p.id===project.id);
 const currentWorld=id=>worldWorkspace(currentProject()).worlds.find(w=>w.id===(id||world?.id));
 const modifyProject=fn=>setState(s=>({...s,scriptProjects:s.scriptProjects.map(p=>p.id===project.id?fn(p):p)}));
 const saveWorld=next=>modifyProject(p=>putWorld(p,next));
 const updateWorld=fn=>{const next=fn(currentWorld());saveWorld(next);return next;};
 const configure=patch=>updateWorld(w=>({...w,config:{...defaults,...w.config,...patch}}));
 const attempt=fn=>{setError('');setNotice('');try{return fn();}catch(e){setError(e.message);}};
 const stop=()=>{const task=job.current;if(task){task.controller.abort();for(const taskId of task.ids)api.cancelAiTask?.({taskId})?.catch(()=>{});}};
 useEffect(()=>{alive.current=true;return()=>{alive.current=false;stop();};},[]);
 // A crashed app cannot resume a paid request silently. Completed rounds stay.
 useEffect(()=>{if(world?.runs.some(r=>r.status==='running')&&!job.current)updateWorld(w=>({...w,runs:w.runs.map(r=>r.status==='running'?{...r,status:'interrupted',error:'上次任务中断，已有进展保留，可继续推演'}:r)}));},[world?.id]);
 const selectWorld=id=>{stop();modifyProject(p=>({...p,creator:{...p.creator,worldSimulation:{...worldWorkspace(p),activeWorldId:id}}}));setCompareId('');};
 const startWorld=seed=>{
  if(!seed.characters.length){if(!heroName.trim())throw new Error('请填写一个主角，或先在新作人物区确认人物');seed={...seed,characters:[{id:'hero-'+uid(),name:heroName.trim(),goal:heroGoal,resources:{},relations:{},knowledge:[]}]};}
  for(const c of source.seed.characters){const found=seed.characters.find(v=>v.id===c.id);if(!found||found.name!==c.name)throw new Error('已确认新作人物编号与姓名必须保留');}
  for(const r of source.seed.rules){const found=seed.rules.find(v=>v.id===r.id);if(!found||found.text!==r.text)throw new Error('已确认新作规则必须保留，请先在设定区修改');}
  const next=createWorld(seed,{name:`${project.name} · 世界${ws.worlds.length+1}`,source:{projectId:project.id,fingerprint:sourceFingerprint(currentProject()),anchors:source.anchors}});next.config={...defaults,protagonistId:seed.characters[0].id};saveWorld(next);selectWorld(next.id);setEditor(null);setNotice('世界起点已保存；大纲是未来计划，尚未当成已经发生的历史。');
 };
 const run=async(auto=false)=>{
  if(job.current||externalBusy)return;if(!profile)return setError('请先添加接口与模型');setError('');setNotice('');
  const task={controller:new AbortController(),ids:new Set(),worldId:world.id},signal=task.controller.signal;job.current=task;let total=0;
  try{
   let base=currentWorld(task.worldId);if(auto){base=forkBranch(base,base.activeBranchId,{name:`自动演进 ${base.branches.length}`});saveWorld(base);}
   const branchId=base.activeBranchId,rounds=auto?Number(cfg.rounds):1;if(!Number.isInteger(rounds)||rounds<1||rounds>10)throw new Error('自动轮数需为1—10');
   for(let round=0;round<rounds;round++){
    if(signal.aborted)throw Object.assign(new Error('任务已停止'),{code:'STOPPED'});const snapshot=currentWorld(task.worldId),runId=uid(),fingerprint=worldFingerprint(snapshot,branchId),record={id:runId,branchId,fingerprint,status:'running',model:profile.model,createdAt:new Date().toISOString(),instruction:cfg.instruction,round:round+1};
    saveWorld({...snapshot,runs:[...snapshot.runs,record]});setBusy({label:`第${round+1}轮准备推演`,calls:total});
    try{
     const result=await proposeNext(snapshot,branchId,{runId,protagonistId:cfg.protagonistId,authorPlan:projectWorldPlan(currentProject()),actorIds:cfg.actorIds??snapshot.seed.characters.slice(0,4).filter(c=>branchState(snapshot,branchId).characters[c.id].alive).map(c=>c.id),horizon:Number(cfg.horizon),candidateCount:Number(cfg.candidateCount),maxCalls:Number(cfg.maxCalls)-total,instruction:cfg.instruction,signal,onProgress:progress=>{if(alive.current)setBusy({...progress,calls:total+progress.calls,round:round+1});},request:async(messages,{call})=>{
      assertMessageCapacity(messages,profile,{});const taskId=`world-${task.worldId}-${runId}-${call}`;task.ids.add(taskId);return api.aiChat({profileId:profile.id,provider:profile.provider,protocol:profile.protocol,endpoint:profile.endpoint,apiKey:profile.apiKey,requiresApiKey:profile.requiresApiKey,model:profile.model,reasoningEffort:profile.reasoningEffort,messages,taskId,resultEnvelope:true});
     }});
     total+=result.usage.calls;if(signal.aborted)throw Object.assign(new Error('任务已停止'),{code:'STOPPED',trace:result.trace,usage:result.usage});
     let live=currentWorld(task.worldId);if(!live||worldFingerprint(live,branchId)!==fingerprint)throw Object.assign(new Error('世界依据已经改变，结果保留在记录中，请重新推演'),{code:'WORLD_STALE',trace:result.trace});
     for(const c of result.routes)live=addCandidate(live,branchId,c);
     live.runs=live.runs.map(r=>r.id===runId?{...r,status:'completed',trace:result.trace,usage:result.usage,rejected:result.rejected,finishedAt:new Date().toISOString()}:r);
     if(auto)live=commitCandidate(live,branchId,result.routes[0].id);saveWorld(live);
    }catch(e){const live=currentWorld(task.worldId);if(live)saveWorld({...live,runs:live.runs.map(r=>r.id===runId?{...r,status:signal.aborted?'cancelled':'failed',error:e.message,trace:e.trace||[],usage:e.usage,finishedAt:new Date().toISOString()}:r)});throw e;}
   }
   if(alive.current)setNotice(auto?'自动演进已完成，结果保存在独立分支；可比较并选择是否采用到新作。':'候选路线已生成，请选择一条采用后继续。');
  }catch(e){if(alive.current)setError(e.message);}finally{if(job.current===task)job.current=null;if(alive.current)setBusy(null);}
 };
 const openSeed=()=>{setDraft(JSON.stringify(world?.seed||source.seed,null,2));setEditor({kind:'seed'});};
 const intervene=e=>{setDraft(JSON.stringify(e,null,2));setEditor({kind:'event',eventId:e.id,branchId:branch.id});};
 const writeBack=()=>attempt(()=>{const p=currentProject(),w=currentWorld();const next=applyWorldStory(p,w,w.activeBranchId);modifyProject(live=>live===p?next:applyWorldStory(live,currentWorld(),w.activeBranchId));setNotice('已采用到新作大事件；原有正文和版本保留。');});
 const exportText=()=>attempt(()=>api.saveTxt({name:`${project.name}-${branch.name}-主角人生`,content:exportLife(world,branch.id,cfg.protagonistId||world.seed.characters[0].id)}).catch(e=>setError(e.message)));
 const upload=async event=>{const file=event.target.files?.[0];event.target.value='';if(!file)return;try{const content=await file.text(),doc=chunkDocument({id:uid(),name:file.name,content});updateWorld(w=>({...w,documents:[...w.documents,doc]}));setNotice('原文保留完整范围，作为作者参考；未自动写成世界事实或角色记忆。');}catch(e){setError(e.message);}};
 const snapshot=world?branchState(world):null,diff=world&&compareId&&world.branches.some(b=>b.id===compareId)?compareBranches(world,compareId,branch.id):null;
 return <section className="world-workbench" aria-label="大世界模拟项目"><header className="world-header"><div><h2><Globe size={22}/>大世界模拟项目</h2><p>从保存的世界起点继续发展，作者选择路线、干预过去，查看人物与因果的变化。</p></div><div className="world-actions"><button className="secondary" disabled={!!busy} onClick={openSeed}><Plus size={15}/>{world?'新世界起点':'完善世界档案'}</button>{world&&<button className="secondary" onClick={exportText}><Download size={15}/>导出主角人生</button>}</div></header>
 {error&&<p className="world-error" role="alert">{error}</p>}{notice&&<p className="world-notice" role="status">{notice}</p>}
 {!world?<div className="world-start"><h3>先确认这个世界从哪里开始</h3><p>导入已确认的新作规则和人物；推演同时参考本项目灵感、人物关系及大小事件。未来大纲作为故事计划，原有模拟仍可使用。</p>{source.warnings.map(w=><p key={w}>{w}</p>)}{!source.seed.characters.length&&<div className="world-two"><label>主角姓名<input aria-label="世界主角姓名" value={heroName} onChange={e=>setHeroName(e.target.value)}/></label><label>主角当前目标<input aria-label="世界主角目标" value={heroGoal} onChange={e=>setHeroGoal(e.target.value)}/></label></div>}<button className="primary" onClick={()=>attempt(()=>startWorld(copy(source.seed)))}>确认并建立世界</button></div>:<div className="world-layout">
 <aside className="world-directory"><label>世界项目<select aria-label="选择世界项目" value={world.id} disabled={!!busy} onChange={e=>selectWorld(e.target.value)}>{ws.worlds.map(w=><option key={w.id} value={w.id}>{w.name}</option>)}</select></label><h3>人生路线</h3>{world.branches.map(b=><button className={b.id===branch.id?'active':''} key={b.id} disabled={!!busy} onClick={()=>updateWorld(w=>({...w,activeBranchId:b.id}))}><GitBranch size={15}/><span>{b.name}<small>{b.events.length} 件已发生 · {b.pending.length} 件待重推</small></span></button>)}<button className="secondary" disabled={!!busy} onClick={()=>attempt(()=>updateWorld(w=>forkBranch(w,branch.id,{name:`新路线 ${w.branches.length}`})))}>从当前时点分叉</button><details><summary>原文档案 · {world.documents.length}</summary><label className="world-upload">导入 TXT / Markdown<input aria-label="导入世界原文" type="file" accept=".txt,.md,.text" onChange={upload}/></label>{world.documents.map(d=><p key={d.id}>{d.name} · {d.content.length.toLocaleString()} 字符 · {d.chunks.length} 块</p>)}</details><details><summary>世界档案 · {world.seed.characters.length} 人物</summary><pre>{JSON.stringify(world.seed,null,2)}</pre></details></aside>
 <div className="world-timeline"><div className="world-section-heading"><h3>{branch.name}</h3><span>{timeLabel(snapshot.time)}</span></div>{world.source.fingerprint!==sourceFingerprint(project)&&<p className="world-error">新作依据已变化，此世界可独立继续；采用到新作前请重新核对世界起点。</p>}
 {!branch.events.length&&<p className="world-empty">这个世界还没有已经发生的事件。先给出要求，推演下一阶段。</p>}
 {branch.events.map(e=><article className="world-event" key={e.id}><header><span>{timeLabel(e.time)}</span><b>{e.title}</b><button className="ghost" disabled={!!busy||e.locked} onClick={()=>intervene(e)}>修改并看蝴蝶效应</button></header><p>{e.summary}</p><small>人物：{e.actorIds?.map(id=>snapshot.characters[id]?.name||id).join('、')||'世界背景'}{e.dependsOn?.length?` · 因果：${e.dependsOn.map(id=>branch.events.find(v=>v.id===id)?.title||'前置事件').join(' → ')}`:''}</small>{e.effects?.length>0&&<details><summary>状态变化与依据</summary><pre>{JSON.stringify({reads:e.reads,effects:e.effects,observations:e.observations},null,2)}</pre></details>}</article>)}
 {branch.pending.length>0&&<details open className="world-pending"><summary>{branch.pending.length} 件后续失效，等待重新推演</summary>{branch.pending.map(e=><p key={e.id}><b>{e.title}</b>：{e.reason}</p>)}</details>}{branch.scheduled.length>0&&<details><summary>{branch.scheduled.length} 件无关未来事件保留</summary>{branch.scheduled.map(e=><p key={e.id}>{timeLabel(e.time)} · {e.title}</p>)}</details>}
 <div className="world-section-heading"><h3>下一步候选路线</h3><small>选择采用后，才发生在当前分支</small></div><div className="world-candidate-grid">{world.candidates.filter(c=>c.branchId===branch.id&&c.status==='pending').slice(-8).map(c=><article className="world-candidate" key={c.id}><h4>{c.name}</h4><p>{c.reasoning}</p><small>{c.conditions}</small>{c.events.map(e=><p key={e.id}><b>{e.title}</b> · {e.summary}</p>)}<button className="primary" disabled={!!busy||c.fingerprint!==worldFingerprint(world,branch.id)} onClick={()=>attempt(()=>updateWorld(w=>commitCandidate(w,branch.id,c.id)))}><Check size={15}/>{c.fingerprint!==worldFingerprint(world,branch.id)?'依据已过期':'采用这条路线'}</button></article>)}</div>
 <details><summary>对照另一条人生路线</summary><select aria-label="比较人生路线" value={compareId} onChange={e=>setCompareId(e.target.value)}><option value="">选择对照路线</option>{world.branches.filter(b=>b.id!==branch.id).map(b=><option key={b.id} value={b.id}>{b.name}</option>)}</select>{diff&&<div><p>变化 {diff.changed.length} · 新增 {diff.added.length} · 待重推 {diff.pending.length}</p>{diff.pending.map(e=><p key={e.id}>{e.title}：{e.reason}</p>)}<pre>{JSON.stringify(diff.states,null,2)}</pre></div>}</details>
 <details><summary>任务记录 · {world.runs.length}</summary>{world.runs.slice().reverse().map(r=><details key={r.id}><summary>{r.status} · {r.model} · {r.usage?.calls||0} 次调用</summary><p>{r.error||r.instruction}</p>{r.rejected?.map((e,i)=><p key={i}>{e.name}：{e.error}</p>)}{r.trace?.map((entry,i)=><details key={i}><summary>{entry.label}</summary><pre>{entry.output||entry.error}</pre></details>)}</details>)}</details>
 </div><aside className="world-controls"><div className="world-controls-content"><h3>作者干预与推演</h3><label>接口与 Agent<select aria-label="大世界模拟接口" value={profile?.selectionId||''} disabled={!!busy} onChange={e=>configure({selection:e.target.value})}>{!profile&&<option value="">请配置模型</option>}{options.map(o=><option key={o.selectionId} value={o.selectionId}>{o.name} · {o.model}</option>)}</select></label><label>主角<select aria-label="模拟主角" value={cfg.protagonistId||world.seed.characters[0]?.id} onChange={e=>configure({protagonistId:e.target.value})}>{world.seed.characters.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label><label>你的要求<textarea aria-label="大世界作者要求" rows={5} value={cfg.instruction} disabled={!!busy} placeholder="希望谁做出什么选择？保留什么结果？也可以让世界自由发展。" onChange={e=>configure({instruction:e.target.value})}/></label><div className="world-two"><label>向后推演（分钟）<input aria-label="世界推演期限" type="number" min="1" max="5256000" value={cfg.horizon} disabled={!!busy} onChange={e=>configure({horizon:Number(e.target.value)})}/></label><label>候选路线数<input aria-label="世界候选数量" type="number" min="1" max="5" value={cfg.candidateCount} disabled={!!busy} onChange={e=>configure({candidateCount:Number(e.target.value)})}/></label><label>最多模型调用<input aria-label="模拟调用上限" type="number" min="1" max="100" value={cfg.maxCalls} disabled={!!busy} onChange={e=>configure({maxCalls:Number(e.target.value)})}/></label><label>自动推进轮数<input aria-label="自动推进轮数" type="number" min="1" max="10" value={cfg.rounds} disabled={!!busy} onChange={e=>configure({rounds:Number(e.target.value)})}/></label></div><fieldset><legend>本轮活动人物（最多8人）</legend>{world.seed.characters.map(c=><label className="world-actor" key={c.id}><input type="checkbox" disabled={!!busy||!snapshot.characters[c.id].alive} checked={(cfg.actorIds??world.seed.characters.slice(0,4).map(c=>c.id)).includes(c.id)} onChange={e=>{const ids=cfg.actorIds??world.seed.characters.slice(0,4).map(c=>c.id);configure({actorIds:e.target.checked?[...ids,c.id]:ids.filter(id=>id!==c.id)});}}/>{c.name}</label>)}</fieldset><p className="world-small">人物只读取自己的可知信息。1天=1440世界分钟；自动模式在独立分支采用第一条通过校验的路线。</p></div><div className="world-control-actions">{busy?<button className="secondary" onClick={stop}><Square size={15}/>停止并保留进展</button>:<><button className="primary" disabled={!profile||externalBusy} onClick={()=>run()}><Sparkles size={15}/>{branch.pending.length?'重推受影响后续':'推演下一阶段'}</button><button className="secondary" disabled={!profile||externalBusy} onClick={()=>{if(window.confirm(`在独立分支自动推进${cfg.rounds}轮，并采用第一条通过校验的候选，最多${cfg.maxCalls}次模型调用？`))run(true);}}><RefreshCw size={15}/>自动演进</button></>}{busy&&<p role="status">{busy.label} · {busy.calls} 次调用</p>}<button className="secondary" disabled={!!busy||!branch.events.length||!!branch.pending.length} onClick={writeBack}><Check size={15}/>采用到新作大事件</button></div></aside>
 </div>}
 {editor&&<CreatorDialog title={editor.kind==='seed'?'世界起点档案':'修改事件与蝴蝶效应'} onClose={()=>setEditor(null)} className="world-editor-dialog"><p>{editor.kind==='seed'?'可声明地点、路线时长、资源、关系与知情事实。保存为独立的新世界，旧世界保留。':'保持事件ID和时间，修改行动、结果及状态变化。保存会创建新分支，并标记受影响后续。'}</p><textarea aria-label="世界结构编辑" rows={16} value={draft} onChange={e=>setDraft(e.target.value)}/>{error&&<p role="alert" className="world-error">{error}</p>}<footer><button className="secondary" onClick={()=>setEditor(null)}>取消</button><button className="primary" onClick={()=>attempt(()=>{const raw=JSON.parse(draft);if(editor.kind==='seed')startWorld(raw);else {updateWorld(w=>forkAt(w,editor.branchId,editor.eventId,raw,{name:`作者干预 ${w.branches.length}`}));setEditor(null);setNotice('新分支已建立；旧路线保留。查看失效后续，再点击重推。');}})}>保存并检查</button></footer></CreatorDialog>}
 </section>;
}
